Add warning about construction work in docs
zkSNACKs/WasabiDoc pull request #1020
Opened 2021-12-20 16:47 UTC by BTCparadigm

Would not want to be a negative Nelly but looking at this repo now makes me even more confident that it's harder to change everything while not braking things too badly, than to use the other repo and copy required pieces to it one by one.

Other thoughts:
Should we say Wasabi Wallet 2.0 everywhere?
Should we destroy for example "Why Wasabi" section to keep 2.0 docs simple? 
Is the time period that docs would remain unreliable and confusing too much?

2021-12-21 23:13 UTC, BTCparadigm commented
Updated repository main README.md to 2.0 and to inform Github users that construction work has begun, so all info might not be up to date.
Also removed shields part because in 2.0 we have different shield.

2021-12-22 11:40 UTC, BTCparadigm commented
Newest plans for docs in #1022 so forget my first comment.

This PR contains warnings for this repositorys README.md and for the websites [landing page](https://wasabiwallet.io/). 
It changes the website message from `config.js` module (I think), adds a picture and updates README.md's to 2.0.

These can't easily be added as dropdown box, hence screwing up with current in-use website is risky. I have not yet had time to test run this but PR is here in case someone wants to run it or add something.

This PR contains stupid commits because I was trying things out, like adding and deleting a pic.

2021-12-22 13:31 UTC, yahiheb requested changes

2021-12-22 13:31 UTC, yahiheb commented on README.md
> +## Note that [Wasabi Wallet documentation](https://docs.wasabiwallet.io/) is under renovation, which means some content you may want to work on is about to be obsoleted and some of the information yo
```suggestion
### Note that [Wasabi Wallet documentation](https://docs.wasabiwallet.io/) is under renovation, some content is about to be obsoleted and some information might not be up to date.
```

2021-12-22 13:31 UTC, yahiheb commented on README.md
> -    <img src="docs/.vuepress/public/WasabiWalletDocs.png" alt="Wasabi Wallet Documentation" title="Wasabi Wallet Documentation" class="Image" />
When replacing a file or a picture, make sure it gets deleted if it is not used elsewhere.

2021-12-22 13:31 UTC, yahiheb commented on README.md
> +[Wasabi Wallet](https://wasabiwallet.io) is an open-source, non-custodial, privacy focused Bitcoin wallet for desktop. It implements a trustless privacy technique, called [WabiSabi CoinJoin](https://
How about this?

```suggestion
[Wasabi Wallet](https://wasabiwallet.io) is an open-source, non-custodial, privacy focused Bitcoin wallet for desktop. It implements a trustless privacy technique, called [CoinJoin](https://en.bitcoin.it/Privacy#CoinJoin).
```

2021-12-22 13:31 UTC, yahiheb commented on README.md
> +    <img src="docs/.vuepress/public/Under_Construction.png" alt="Documentation under construction" title="Documentation under construction" class="Image" />
I don't think we should change the tags:

```suggestion
    <img src="docs/.vuepress/public/Under_Construction.png" alt="Wasabi Wallet Documentation" title="Wasabi Wallet Documentation" class="Image" />
```

2021-12-22 13:31 UTC, yahiheb commented on docs/.vuepress/config.js
> +  description: "Wasabi Wallet documentation is currently under construction because of the upcoming 2.0 release. Be aware that some of the content might not yet be up to date.",
We shouldn't change these IMO. Maybe just add something that says it is under construction.

```suggestion
  title: "Wasabi Docs",
  description: "An archive of knowledge about Wasabi Wallet, an open-source, non-custodial and privacy-focused Bitcoin wallet for desktop.",
```

2021-12-22 13:31 UTC, yahiheb commented on docs/README.md
> +actionLink: /building-wasabi/README.md
We shouldn't change this IMO.

```suggestion
heroText: Wasabi Documentation
heroImage: /Logo_without_text.png
actionText: Reclaim Your Privacy →
actionLink: /using-wasabi/ELI5.md
```

2021-12-22 18:54 UTC, yahiheb approved these changes

2021-12-23 21:41 UTC, BTCparadigm commented
Change in plans. Docs 2.0 will be built in [another branch](https://github.com/zkSNACKs/WasabiDoc/tree/docs-2.0).
CLosing this.

2021-12-23 21:41 UTC, closed without merging