[Docs-2.0] Remove unnecessary files from Building-Wasabi
zkSNACKs/WasabiDoc pull request #1035
Opened 2022-01-05 16:40 UTC by BTCparadigm

Removes ContributionGame.md, Credits.md and WasabiResearchClub.md. 
Moves WasabiResearchClub.md content to ContributionChecklist.md.

2022-01-05 18:42 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +- Wasabi Research Club is a weekly meeting focused mostly on Bitcoin privacy.
```suggestion
- Wasabi Research Club is a weekly online call, focused mainly on Bitcoin privacy.
```

2022-01-05 18:42 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +Anyone is welcome to join the discussions, however being familiar with the topic, if there is such, is recommended.
```suggestion
Everyone is welcome to join the discussions. However, being familiar with the topic (if there is such) is recommended.
```

2022-01-05 18:42 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +Discussions might be recorded and published later in Wasabi Wallet Youtube channel.
```suggestion
Discussions might be recorded and published on the Wasabi Wallet [YouTube](https://www.youtube.com/c/wasabiwallet) [channel](https://www.youtube.com/c/wasabiwallet).
```

2022-01-05 18:42 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +You can find all the information, past recordings, slides, links, and much more [here](https://github.com/zkSNACKs/WasabiResearchClub/).
```suggestion
You can find past recordings, slides, links and more info related to the Wasabi Research Club [here](https://github.com/zkSNACKs/WasabiResearchClub/).
```

2022-01-05 18:46 UTC, MarnixCroes approved these changes

2022-01-06 12:16 UTC, BTCparadigm commented on docs/building-wasabi/ContributionChecklist.md
> +Discussions might be recorded and published later in Wasabi Wallet Youtube channel.
Why 2 separate links [Youtube] and [channel] to the same page?
Maybe just [YouTube channel](https://www.youtube.com/c/wasabiwallet).

2022-01-06 12:19 UTC, BTCparadigm commented on docs/building-wasabi/ContributionChecklist.md
> +You can find all the information, past recordings, slides, links, and much more [here](https://github.com/zkSNACKs/WasabiResearchClub/).
How about:

You can find the schedule, call link, past recordings and more from [Wasabi Research Club repository](https://github.com/zkSNACKs/WasabiResearchClub/).

2022-01-08 13:27 UTC, yahiheb requested changes
@BTCparadigm References to the deleted files should be removed or edited.

Whenever you delete a file, picture, etc, you should also delete all references to it or anything related to it in the repository.

If you use git bash you can use this command for example `git grep 'ContributionGame'`  to get all occurrences of the word `ContributionGame` in the repository.

Alternatively you can use the github search bar to search in this repository:

![Rafe](https://user-images.githubusercontent.com/52379387/148645838-6065b8c6-7817-4ed7-881a-d699f83bb093.PNG)

Shouldn't we keep the content of the contribution game document somehow?

2022-01-09 17:26 UTC, BTCparadigm commented
> References to the deleted files should be removed or edited.

@yahiheb Done.

I dont think we need a separate page for that at this point. We can fit info about current ones in ContributionChecklist. Keeping the old info doesnt seem useful but actually bad.

2022-01-10 09:48 UTC, MarnixCroes requested changes

2022-01-10 09:48 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +With that said, it's a good idea to consult with other Wasabikas via Slack, GitHub, or other communication channels before setting out on any serious contribution effort. It might be helpful to make
```suggestion
With that being said, it's a good idea to consult with other Wasabikas via Slack, GitHub, or other communication channels before setting out on any serious contribution effort. It might be helpful to make sure your contribution is:
```

2022-01-11 00:06 UTC, yahiheb requested changes
If we should delete the contribution game content then the `ContributionGame.png` file should be removed.

2022-01-11 07:09 UTC, BTCparadigm commented on docs/building-wasabi/ContributionChecklist.md
> +Everyone is welcome to join the discussions. However, being familiar with the topic (if there is such) is recommended.
It's ok. I'll do it.

2022-01-11 11:25 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
> +Everyone is welcome to join the discussions. However, being familiar with the topic (if there is such) is recommended.
I meant should we remove that convention?

2022-01-11 11:30 UTC, BTCparadigm commented on docs/building-wasabi/ContributionChecklist.md
> +Everyone is welcome to join the discussions. However, being familiar with the topic (if there is such) is recommended.
Nah

2022-01-11 11:31 UTC, yahiheb requested changes
I still think maybe we should keep the history of the previous contribution games.

2022-01-11 11:31 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
> +However, being familiar with the topic (if there is such) is recommended.
I guess this should be:
```suggestion
However, being familiar with the topic (if there is any) is recommended.
```

2022-01-11 11:31 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
> +With that being said, it's a good idea to consult with other Wasabikas via Slack, GitHub, or other communication channels before setting out on any serious contribution effort. It might be helpful to
If we should keep the one-sentence per line writing convention then this should be:
```suggestion
With that being said, it's a good idea to consult with other Wasabikas via Slack, GitHub, or other communication channels before setting out on any serious contribution effort.
It might be helpful to make sure your contribution is:
```

2022-01-11 12:36 UTC, BTCparadigm commented on docs/building-wasabi/ContributionChecklist.md
> +However, being familiar with the topic (if there is such) is recommended.
> I still think maybe we should keep the history of the previous contribution games.

I think we dont want to keep up and list all of them in docs.
I also don't think it's good for privacy reasons. 
There's some things that shouldn't be considered Contribution Games but things zkSNACKs rewards users for, like helping out in support or creating  GIFs. 
I have another PR waiting that changes things in ContributionChecklist and it includes mentioning all the current things users should contribute to and that they could get rewarded from.

2022-01-11 23:33 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
>  - something that the relevant maintainers would be likely to merge;
```suggestion
- something that the maintainers would be likely to merge;
```

2022-01-11 23:34 UTC, yahiheb approved these changes

2022-01-11 23:35 UTC, merged