Add Taproot
zkSNACKs/WasabiDoc pull request #1036
Opened 2022-01-09 16:57 UTC by MarnixCroes

Add Taproot to the glossary. 
If you have any improvements, feel free to share

2022-01-10 22:41 UTC, yahiheb commented
How about rephrasing that using the key highlights in https://river.com/learn/what-is-taproot/?

2022-01-12 15:24 UTC, BTCparadigm commented
Combined the best of what @MarnixCroes wrote and what was in river.com.

> Taproot is an upgrade to Bitcoin which was activitated via a softfork in 2021. 
> Taproot integrated the Schnorr digital signature scheme into Bitcoin, upgrading Bitcoin’s core cryptography.
> Taproot built on the SegWit upgrade to improve Bitcoin’s scalability, privacy and smart contract functionality. 
> The Taproot softfork adds another output type called "Pay to Taproot" (P2TR).

2022-01-19 14:01 UTC, BTCparadigm commented
@yahiheb can you confirm the text in the comment above is ok?

2022-01-19 14:22 UTC, yahiheb commented
> @yahiheb can you confirm the text in the comment above is ok?

If @MarnixCroes approves that, then he should update the PR, and then we can further review it.

2022-01-20 06:53 UTC, BTCparadigm commented on docs/glossary/Glossary-GeneralBitcoin.md
> +The Taproot softfork adds another output type called "Pay to Taproot" (P2TR).
Trying to avoid tautology.
```suggestion
Taproot is an upgrade which was activitated via a softfork in 2021 to the Bitcoin consensus rules.
It set the stage for extra functionality to Bitcoin by optimizing scalability, privacy and smart contract functionality.
The Taproot upgrade contains three distinct upgrades to the Bitcoin protocol: Schnorr Signatures, Taproot, and Tapscript.
It also added another output type called "Pay to Taproot" (P2TR) and another address type that starts with "bc1p...".
```

2022-01-20 19:10 UTC, yahiheb commented on docs/glossary/Glossary-GeneralBitcoin.md
> +The Taproot softfork adds another output type called "Pay to Taproot" (P2TR).
This confuses me more than it helps me understand what Taproot is.

It says that Taproot is an upgrade, then it says Taproot contains three distinct upgrades and one of them is something called Taproot, and what is Tapscript?

Is it important to mention when it was activated?

Why not just simply:

```
Taproot is an upgrade to Bitcoin which introduced several new features.
Taproot integrated the Schnorr digital signature scheme into Bitcoin, upgrading Bitcoin’s core cryptography.
Taproot built on the SegWit upgrade to improve Bitcoin’s privacy and lower transaction fees.
Taproot made future Bitcoin upgrades easier by reforming Bitcoin’s scripting language.
```

2022-01-22 01:30 UTC, yahiheb requested changes

2022-01-22 01:30 UTC, yahiheb commented on docs/glossary/Glossary-GeneralBitcoin.md
> +Taproot builts on the SegWit upgrade to improve Bitcoin’s privacy and lower transaction fees.
```suggestion
Taproot integrates the Schnorr digital signature scheme into Bitcoin, upgrading Bitcoin’s core cryptography.
Taproot builds on the SegWit upgrade to improve Bitcoin’s privacy and lower transaction fees.
```

2022-01-22 13:43 UTC, yahiheb approved these changes

2022-01-22 13:46 UTC, merged