Addition: address reuse prevention NEW GUI
zkSNACKs/WasabiDoc pull request #1037
Opened 2022-01-09 18:52 UTC by MarnixCroes

Added some more info about how Wasabi tries to help prevent users from address reuse (with the new GUI).

2022-01-10 11:37 UTC, yahiheb requested changes

2022-01-10 11:37 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +A new Bitcoin address will be generated automatically at the `Receive` tab (using the GUI).
What do you mean by this? I think this should be removed.

2022-01-10 11:37 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +Previously generated address, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.
```suggestion
Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`. 
```

2022-01-10 11:41 UTC, MarnixCroes commented on docs/why-wasabi/AddressReuse.md
> +A new Bitcoin address will be generated automatically at the `Receive` tab (using the GUI).
I meant to clarify (for real newbie users) that there will always be a new address being generated.

2022-01-10 18:49 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +A new Bitcoin address will be generated automatically at the `Receive` tab (using the GUI).
Addresses will not be generated automatically.

2022-01-10 19:04 UTC, MarnixCroes commented on docs/why-wasabi/AddressReuse.md
> +A new Bitcoin address will be generated automatically at the `Receive` tab (using the GUI).
I see,
*a new*  is what I mean. Maybe a real newbie user could think it would always be the same address that would show up.
But i get your point, if you think we should delete it, that's ok

2022-01-10 22:52 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +A new Bitcoin address will be generated automatically at the `Receive` tab (using the GUI).
Then we can simply remove the word `at the `Receive` tab (using the GUI)` which is confusing:

```suggestion
A new Bitcoin address will be generated at the `Receive` tab (using the GUI).
```

2022-01-11 21:18 UTC, yahiheb requested changes

2022-01-11 21:18 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +Wasabi encourages users to not reuse addresses. This is done in the following way:
> Every sentence must start in a new line.

https://github.com/zkSNACKs/WasabiDoc#writing-conventions

```suggestion
Wasabi encourages users to not reuse addresses.
This is done in the following way:
```

2022-01-11 21:18 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.
```suggestion
Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.
```

2022-01-11 23:08 UTC, yahiheb approved these changes

2022-01-12 17:17 UTC, BTCparadigm reviewed
Added some stuff to be more spesific.

2022-01-12 17:17 UTC, BTCparadigm commented on docs/why-wasabi/AddressReuse.md
> +This is done in the following way:
No need for this line.

2022-01-12 17:17 UTC, BTCparadigm commented on docs/why-wasabi/AddressReuse.md
>  It is deterministic because the same parent secret always calculates the same child private keys.
This line could also be removed.

2022-01-12 17:17 UTC, BTCparadigm commented on docs/why-wasabi/AddressReuse.md
> +A new Bitcoin address will be generated at the `Receive` tab (using the GUI).
(Achtually user has to also click continue...).

```suggestion
A new Bitcoin address will be generated after user types in the receiver-label.
Even when the same label is being written multiple times, Wasabi always generates a new receive address.
```

2022-01-12 17:17 UTC, BTCparadigm commented on docs/why-wasabi/AddressReuse.md
> +Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.
Just to be spesific, how about:

```suggestion
Previously generated addresses, which haven't received bitcoin yet according to the Bitcoin blockchain, are displayed at `Unused Receive Addresses`.
```

2022-01-12 17:17 UTC, BTCparadigm commented on docs/why-wasabi/AddressReuse.md
> +An address will automatically be removed from the `Unused Receive Addresses` list when that address has received any funds.
```suggestion
When the wallet recognizes a transaction to one of its addresses, the corresponding address will automatically be removed from the `Unused Receive Addresses` list.
```

2022-01-13 18:44 UTC, MarnixCroes commented on docs/why-wasabi/AddressReuse.md
> +Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.
> according to the Bitcoin blockchain

I guess the address will be 'gone' of the list when the wallet gets know of an incoming tx, it does not have to have a confirmation. So I think it's not "according to the blockchain": tx doesn't have to be in the blockchain yet to be recognized

2022-01-13 18:58 UTC, MarnixCroes commented on docs/why-wasabi/AddressReuse.md
> +An address will automatically be removed from the `Unused Receive Addresses` list when that address has received any funds.
```suggestion
When the wallet recognizes a transaction to an address at the "Unused Receive Addresses" list, that address will automatically be removed from the list.
```

2022-01-13 19:12 UTC, BTCparadigm commented on docs/why-wasabi/AddressReuse.md
> +Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.
You are right in the case that receiver has Wasabi open at the time of sending. Otherwise the address gets removed when tx confirms.

2022-01-13 19:32 UTC, MarnixCroes commented on docs/why-wasabi/AddressReuse.md
> +Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.
Right. I think we should keep it general, so which is correct for both the options

2022-01-13 22:51 UTC, BTCparadigm commented on docs/why-wasabi/AddressReuse.md
> +Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.
Actually it's better if we dont even need to go to such details. Just keep it general.

2022-01-15 01:03 UTC, yahiheb commented
IMO we should remove all the BIP 44 details, so this is how it should be:

```
### Remove used address from GUI

Wasabi encourages users to not reuse addresses.

You get a new Bitcoin address whenever you generate one.

Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.

An address is automatically removed from the `Unused Receive Addresses` list once that address receives any funds.
```

2022-01-15 10:06 UTC, MarnixCroes commented
> IMO we should remove all the BIP 44 details, so this is how it should be:
> 
> ```
> ### Remove used address from GUI
> 
> Wasabi encourages users to not reuse addresses.
> 
> You get a new Bitcoin address whenever you generate one.
> 
> Previously generated addresses, which haven't received bitcoin yet, are displayed at `Unused Receive Addresses`.
> 
> An address is automatically removed from the `Unused Receive Addresses` list once that address receives any funds.
> ```

@yahiheb Do you know if BIP 44 is mentioned somewhere else in the docs? If not, we should move it to an other section, because it is something that should be in the docs IMO

2022-01-15 13:30 UTC, yahiheb commented
> @yahiheb Do you know if BIP 44 is mentioned somewhere else in the docs? If not, we should move it to an other section, because it is something that should be in the docs IMO

It is mentioned here:

https://docs.wasabiwallet.io/using-wasabi/BIPs.html#what-is-supported
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#why-is-it-bad-to-re-use-addresses
https://docs.wasabiwallet.io/why-wasabi/AddressReuse.html#intentionally-malicious

2022-01-15 13:35 UTC, yahiheb commented
@MarnixCroes  Check this https://github.com/zkSNACKs/WasabiDoc/pull/1035#pullrequestreview-847156010 to look up for words/sentences, or use the search bar in the docs website

2022-01-15 15:38 UTC, MarnixCroes commented
> @MarnixCroes Check this [#1035 (review)](https://github.com/zkSNACKs/WasabiDoc/pull/1035#pullrequestreview-847156010) to look up for words/sentences, or use the search bar in the docs website

My bad. I was looking in the wrong repo. Thanks

2022-02-21 18:12 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +A new Bitcoin address will be generated after the user types in the receiver-label.
This line is just redundant of the previous one.

2022-02-21 18:15 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +You get a new Bitcoin address whenever you generate one.
This allows us to remove the next two lines which are just redundant.

```suggestion
You always get a new Bitcoin address whenever you generate one.
```

2022-02-21 18:19 UTC, yahiheb requested changes

2022-02-21 18:19 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +Even when the same label is being written multiple times, Wasabi always generates a new receive address.
This also should be removed, it is just redundant information.

```suggestion
```

2022-02-21 18:19 UTC, yahiheb commented on docs/why-wasabi/AddressReuse.md
> +When the wallet recognizes a transaction to an address displayed at "Unused Receive Addresses", that address will automatically be removed from the list.
Saying the same thing is less words.

```suggestion
An address is automatically removed from the `Unused Receive Addresses` list once that address receives any funds.
```

2022-02-21 19:06 UTC, yahiheb commented
@MarnixCroes This LGTM, I would just suggest you to open a new PR to replace this one given that this has so many unrelated commits.

2022-02-23 18:20 UTC, closed without merging