[Docs-2.0] Update `ContributionChecklist.md`
zkSNACKs/WasabiDoc pull request #1038
Opened 2022-01-12 14:17 UTC by BTCparadigm

2022-01-12 14:30 UTC, yahiheb commented
@BTCparadigm You need to fix the conflicts

2022-01-13 19:28 UTC, MarnixCroes requested changes
Small improvements

2022-01-13 19:28 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +:::tip Embrace the open-source cryptoanarchy!
```suggestion
:::tip Embrace the open-source crypto-anarchy!
```

2022-01-13 19:28 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +Contributors who have their own ideas are free to work in their own forks on whatever they wish, however they wish, and without any permission from anyone.
```suggestion
Contributors who have their own ideas are free to work at their own forked version on whatever they wish, however they wish and without any permission from anyone.
```

2022-01-13 19:28 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +You can create wallet tutorial videos, insightful recorded discussions, articles or memes about Wasabi and privacy.
```suggestion
You can create wallet tutorials, record insightful discussions, write articles or make memes about Wasabi and privacy.
```

2022-01-13 19:28 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +3. **Helping and teaching new users**, once you are familiar with the software, is something that can't be underestimated.
```suggestion
3. **Helping and teaching new users**, being familiar with the software is something that can't be underestimated.
```

2022-01-13 19:28 UTC, MarnixCroes commented on docs/building-wasabi/ContributionChecklist.md
> +:::tip [zkSNACKs Ltd.](https://zksnacks.com/) is known for compensating some of the educators when they consistently help out new users or create good content.
```suggestion
:::tip [zkSNACKs Ltd.](https://zksnacks.com/) is known for compensating educators who consistently help out new users or create good content. 
```

2022-01-15 00:48 UTC, yahiheb requested changes

2022-01-15 00:48 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
> +Contributors who have their own ideas are free to work at their own forked version on whatever they want, however they wish and without any permission from anyone.
How about this:

```suggestion
No one is here to tell you what to do, and it is not required to work on an existing issue to contribute to Wasabi.
Contributors are free to work on their own forked versions on whatever they want, however they wish and without any permission from anyone.
```

2022-01-15 00:48 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
> -
Why removing these empty lines?
We have them in all documents so we better be consistent and keep them after the titles.

2022-01-15 00:48 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
> -- Follow [@WasabiWallet](https://twitter.com/wasabiwallet) on Twitter and subscribe to the [Wasabi YouTube channel](https://www.youtube.com/channel/UCobsrSexTuVkL39mbrQ35VQ) to stay up-to-date.
Why this got removed?

2022-01-15 00:48 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
> +- Learn what Wasabikas have planned for the [future Of Wasabi Wallet](/building-wasabi/FutureOfWasabiWallet.md).
At this point there is no such document.

2022-01-15 00:48 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
> +The better UX and privacy Wasabi provides, the more there will be users, because of [network effect](https://en.wikipedia.org/wiki/Network_effect).
Do you want these to be on separate lines? If yes then you need to separate them by an empty line or better to use `-` at the start of each line.

2022-01-15 00:48 UTC, yahiheb commented on docs/building-wasabi/ContributionChecklist.md
> +In case you have been contributing already, feel free to let other Wasabikas know by sending us a link in [Slack](https://join.slack.com/t/tumblebit/shared_invite/enQtNjQ1MTQ2NzQ1ODI0LWIzOTg5YTM3YmNk
Which link?

2022-01-15 06:54 UTC, BTCparadigm commented on docs/building-wasabi/ContributionChecklist.md
> -
Consistency was what I was aiming for. I'll add a space then

2022-01-15 06:55 UTC, BTCparadigm commented on docs/building-wasabi/ContributionChecklist.md
> -- Follow [@WasabiWallet](https://twitter.com/wasabiwallet) on Twitter and subscribe to the [Wasabi YouTube channel](https://www.youtube.com/channel/UCobsrSexTuVkL39mbrQ35VQ) to stay up-to-date.
Didnt see following Wasabi Twitter or Youtube as necessary for new contributors.

2022-01-15 06:56 UTC, BTCparadigm commented on docs/building-wasabi/ContributionChecklist.md
> +- Learn what Wasabikas have planned for the [future Of Wasabi Wallet](/building-wasabi/FutureOfWasabiWallet.md).
Can we leave it as a placeholder?
It was there to remind me.

2022-01-15 06:58 UTC, BTCparadigm commented on docs/building-wasabi/ContributionChecklist.md
> +In case you have been contributing already, feel free to let other Wasabikas know by sending us a link in [Slack](https://join.slack.com/t/tumblebit/shared_invite/enQtNjQ1MTQ2NzQ1ODI0LWIzOTg5YTM3YmNk
Link to their content but I guess that can be explained a bit better.

2022-01-15 15:14 UTC, yahiheb approved these changes
LGTM

2022-01-15 17:54 UTC, merged