[Docs-2.0] Update ELI5.md
zkSNACKs/WasabiDoc pull request #1049
Opened 2022-01-31 11:02 UTC by BTCparadigm

Update ELI5 to WW2

2022-01-31 12:33 UTC, MarnixCroes reviewed
Small improvements

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +If you don't like that your employer knows about where you spend your money, or that a merchant can find out how much money you have, using Wasabi is the obvious choise because it by default coinjoin
```suggestion
If you don't like that your employer knows about where you spend your money, or that a merchant can find out how much money you have, using Wasabi is the obvious choice because, by default, it coinjoins your coins, thus breaking it's transaction history link.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +By default, the wallet automatically starts coinjoining UTXO's larger than 1M sat after few minutes have passed from the transaction being confirmed.
```suggestion
By default, the wallet automatically starts coinjoining UTXO's larger than 0.01 BTC, after a few minutes have passed since the transaction was confirmed. 
```
might be better to use BTC instead of sat because _sat_ nomination is not yet implemented.

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +At this point, Wasabi will deduct  0,3% of coordinator fees from that total UTXO balance and the necessary Bitcoin networks coinjoin transaction fees.
```suggestion
At this point, Wasabi will deduct  0,3% from that total UTXO balance as coordinator fee and the necessary Bitcoin network transaction fee. 
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically mix the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees won't be charged from the user again
```suggestion
The wallet will then automatically mix the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the user again. Although, Bitcoin network transaction fees still apply.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +In case the user has only smaller than 1M sat UTXO's, the wallet will which to Plebs Don't Pay -mode, which means it wont automatically coinjoin users coins.
```suggestion
When the user only has UTXO's smaller than 0.01 BTC, the wallet will switch to _Plebs Don't Pay -mode_, which means it won't automatically coinjoin the users coins.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +See [this chapter](/using-wasabi/CoinJoin.md) for a thorough analysis of coinjoin, details on the Wasabi implementation and best practices how to use it properly.
```suggestion
See [this chapter](/using-wasabi/CoinJoin.md) for a thorough analysis of coinjoin, details on the Wasabi implementation and best practices on how to use it properly.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +In Wasabi, you can use `Send` button to give your bitcoins to someone else, or send them to another wallet of yours.
```suggestion
In Wasabi, you can use the `Send` button to give your bitcoin to someone else or send them to another wallet of yours.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +1. Click `Send` button from top right corner of the main view.
```suggestion
1. Click the `Send` button (top right corner) at the main view.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +4. From `Advanced options` you can set a custom transaction fee, otherwise the wallet automatically estimates it.
```suggestion
4. At `Advanced options` you can set a custom transaction fee, otherwise the wallet automatically estimates it.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +6. Verify that everything is correct and click `Confirm` or adjust the transaction.
```suggestion
6. Check if everything is filled in correctly and click `Confirm`.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +7. Optionally you can click the shield image from the top right corner of the `Transaction Preview` to see suggestions on how to avoid generating a change output in this payment.
```suggestion
7. Optionally, you can click the shield image (top right corner) at `Preview Transaction` to see suggestions on how to avoid generating a change output in this payment.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +10. You should see a pop-up window telling you that the transaction was broadcasted to the Bitcoin network.
```suggestion
10. You will now see a pop-up window telling you that the transaction is broadcasted to the Bitcoin network.
```

2022-01-31 12:33 UTC, MarnixCroes commented on docs/using-wasabi/ELI5.md
> +See [this chapter](/using-wasabi/Send.md) for more details on sending bitcoins and the privacy nuances of it.
```suggestion
See [this chapter](/using-wasabi/Send.md) for more details about sending bitcoin and the privacy nuances of it.
```

2022-02-01 03:09 UTC, yahiheb requested changes

2022-02-01 03:09 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +4. At `Advanced options` you can set a custom transaction fee, otherwise the wallet automatically estimates it.
```suggestion
4. At `Advanced options` you can set a custom transaction fee rate, otherwise the wallet automatically estimates it.
```

2022-02-01 03:09 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +6. Check if everything is filled in correctly and click `Confirm`.
We should mention at `Preview Transaction` here.

2022-02-01 06:53 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +When the user only has UTXO's smaller than 0.01 BTC, the wallet will switch to _Plebs Don't Pay -mode_, which means it won't automatically coinjoin the users coins.
Coordinator doesnt know links between users inputs so UTXO is correct IMO

2022-02-01 06:55 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +But first, you must label it with the names of any observers who know about this transaction.
True. Didnt figure out how to explain it shortly. Will figure something out.

2022-02-01 07:00 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +By default, the wallet automatically starts coinjoining UTXO's larger than 0.01 BTC, after a few minutes have passed since the transaction was confirmed.
I think it is correct because of the delays before auto mixing starts, which was just merged. 
I think we should explain shortly the Plebs dont pay and manual coinjoining  because there is 2 ways the wallet works by default.

2022-02-01 07:02 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +Once all or some of these coins are mixed, they will show up in the software's main view as "private coins".
Arent they under the main balance?
At least for me they are shown as "Private coins"

2022-02-01 07:47 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +But first, you must label it with the names of any observers who know about this transaction.
Why change something that was already correct and clear?

2022-02-01 07:51 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +By default, the wallet automatically starts coinjoining UTXO's larger than 0.01 BTC, after a few minutes have passed since the transaction was confirmed.
> I think it is correct because of the delays before auto mixing starts, which was just merged.

It is after a few minutes that the wallet was loaded not "after a few minutes have passed since the transaction was confirmed."

> I think we should explain shortly the Plebs Dont Pay and "manual" coinjoining because there is 2 ways the wallet works by default.

This is just a brief explanation how the wallet works, there is no need for details.

2022-02-01 07:54 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +Once all or some of these coins are mixed, they will show up in the software's main view as "private coins".
Do you see the coins themselves? or do you just see the total value of those coins?

2022-02-01 07:59 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +But first, you must label it with the names of any observers who know about this transaction.
Hmm. Not sure what was I thinking. Will change it back.

2022-02-01 08:03 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +By default, the wallet automatically starts coinjoining UTXO's larger than 0.01 BTC, after a few minutes have passed since the transaction was confirmed.
I was thinking about this from the first-time-user perspective but you are right in the case where user already has confirmed coins in the wallet.

2022-02-01 08:32 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +By default, the wallet automatically starts coinjoining UTXO's larger than 0.01 BTC, after a few minutes have passed since the transaction was confirmed.
What is the other default way? I am not sure I get what you mean.

We can simply say "By default, the wallet automatically coinjoins your bitcoin."

2022-02-01 08:34 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +At this point, Wasabi will deduct  0,3% from that total UTXO balance as coordinator fee and the necessary Bitcoin network transaction fee.
There is no need for these details.

If you look at the text that you are trying to edit, it didn't mention any detail, it just explained how to use coinjoin.

2022-02-01 08:54 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +Once all or some of these coins are mixed, they will show up in the software's main view as "private coins".
Talking about value of a coin might confuse newbies more by making them think of USD price or something but I changed it a bit so its hopefully clear now.

2022-02-01 09:08 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +By default, the wallet automatically starts coinjoining UTXO's larger than 0.01 BTC, after a few minutes have passed since the transaction was confirmed.
> What is the other default way? I am not sure I get what you mean.

I mean, it either does automatically coinjoin users bitcoin or it doesnt, depending on how big UTXO's do they have.
It would be very confusing for user with less than 0.01 BTC if we said the wallet automatically coinjoins their coins even if it actually does not.

> We can simply say "By default, the wallet automatically coinjoins your bitcoin."

I agree we might not need to specify that starting the coinjoin takes a moment but I do think we have explain the limit.

2022-02-01 12:27 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +By default, the wallet automatically starts coinjoining UTXO's larger than 0.01 BTC, after a few minutes have passed since the transaction was confirmed.
This is just an ELI5 document, we shouldn't complicate things.
We should have documents where everything is explained in details.

2022-02-01 12:37 UTC, yahiheb requested changes
@BTCparadigm This is just an ELI5 document, we should keep it as simple as possible, there is no need to mention all the use cases here.
At the end of each section there is a link for more details if the reader wants to learn more how sending or conjoining work.

2022-02-03 06:53 UTC, BTCparadigm commented
@yahiheb You are right, I went in to details.
I simplified sending process explanation but IMHO coinjoin part is ok, because it's good to mention wallets default behaviour differences with more or less than 0.01 BTC UTXO.

2022-02-03 12:47 UTC, yahiheb commented
> but IMHO coinjoin part is ok, because it's good to mention wallets default behaviour differences with more or less than 0.01 BTC UTXO.

I don't agree with that. One or two sentences saying that coinjoin happens automatically by default with WW2 is better, maybe we can mention it is possible to turn that off.

The previous coinjoin explanation didn't mention any min amount to coinjoin and that was good for this document.

2022-02-06 22:06 UTC, yahiheb requested changes

2022-02-06 22:06 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +In Wasabi, you can use the `Send` button to give your bitcoin to someone else or send them to another wallet of yours.
IMO we should just remove this sentence.

```suggestion
```

2022-02-06 22:06 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +7. You will now see a pop-up window telling you that the transaction is broadcasted to the Bitcoin network.
```suggestion

You will now see a pop-up window telling you that the transaction is broadcasted to the Bitcoin network.
```

2022-02-06 22:06 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +If you don't like that your employer knows about where you spend your money, or that a merchant can find out how much money you have, using Wasabi is the obvious choice.
Just remove this IMO.
```suggestion
```

2022-02-06 22:50 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +If you don't like that your employer knows about where you spend your money, or that a merchant can find out how much money you have, using Wasabi is the obvious choice.
Lol. After +46 comments for changing ~25 lines I'm at a point that I could commit any suggestions just to avoid arguing but I do think explanation for 5y old should include these basic reasonings, even if the kid doesnt know UTXO model. 
That sentence makes one learn.

2022-02-06 22:57 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically coinjoin the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the us
I think this suggestion is confusing. 
Nothing indicates that all coins might not get mixed in one round, making the user wonder why the amount in `private coins` doesnt move much.
I tried avoid using the word "hop" and to explain what it means in a way that a 5y old might understand.
Do you have strong feelings about this one?

2022-02-07 01:28 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically coinjoin the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the us
> Nothing indicates that all coins might not get mixed in one round, making the user wonder why the amount in `private coins` doesnt move much.

Nothing in your suggestion indicate that either.

> I tried avoid using the word "hop" and to explain what it means in a way that a 5y old might understand.

I don't think that a 5y old would understand what a UTXO or a confirmed transaction is.
Also the wallet does not automatically start coinjoining received UTXO's few minutes after the transaction is confirmed.

2022-02-07 01:29 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +If you don't like that your employer knows about where you spend your money, or that a merchant can find out how much money you have, using Wasabi is the obvious choice.
We could avoid the back and forth by keeping things very simple and precise and changing only what really needs to be changed.

So saying `using Wasabi is the obvious choice` can be misleading, because if you use Wasabi without coinjoining then that will not help you hide what you do with your money from your employer.

The previous sentence `then you should CoinJoin your bitcoin, as this breaks the transaction history` was more precise and clear.

2022-02-07 07:20 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically coinjoin the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the us
> Nothing in your suggestion indicate that either.

This part is supposed to do that. `Once all or some of these funds are properly coinjoined...`

> wallet does not automatically start coinjoining received UTXO's few minutes after the transaction is confirmed

How come?

2022-02-07 15:43 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically coinjoin the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the us
> These were supposed to do that. `Once all or some of these funds are properly coinjoined...` and `wallet will then automatically coinjoin the remaining coins`.

Nothing in those mention anything about rounds.

`Once all or some of these funds are properly coinjoined` for me this sentence talks about the received UTXO's that the wallet automatically started coinjoinig in the precedent sentence, so it does not talk about all the coins.

> > wallet does not automatically start coinjoining received UTXO's few minutes after the transaction is confirmed
> 
> How come?

There are many details when and how the wallet automatically starts coinjoining, but there is nothing that makes confirmed UTXOs wait few minutes.

> IMHO, your comment suggestion gives an impression that everything should get mixed in 1 coinjoin round.

My comment is not to explain how coinjoin works in detail.

2022-02-07 16:59 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +If you don't like that your employer knows about where you spend your money, or that a merchant can find out how much money you have, using Wasabi is the obvious choice.
"breaks the transaction history" sounds wrong. Edited.

2022-02-07 18:52 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically coinjoin the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the us
> To me your version gives an impression that everything happens in one coinjoin.

My opinion is just to say how coinjoin works in WW2 without any detail.

> Delay AutoCoinJoin [zkSNACKs/WalletWasabi#7122 (comment)](https://github.com/zkSNACKs/WalletWasabi/issues/7122#issue-1115037094)

`The idea is to wait a few minutes after the wallet loaded and then start mixing.`

This is delay is after you open the wallet, it has nothing to do with confirmed UTXOs.

2022-02-07 23:56 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically coinjoin the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the us
> Wait a while before the wallet starts mixing automatically.

From this and from general concept for delays, I would assume the delay is also for received coins. 
The reasoning is the same than when delaying after opening the wallet or when in `send` tab - user might want to do something with these coins so we should wait a moment. 
Not sure if that's how it's implemented though.
Ping @molnard ?

2022-02-08 00:06 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically coinjoin the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the us
Even if all what you are saying is correct we don't need to mention all of that, it is just details and nuance for this specific document.

2022-02-08 23:50 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically coinjoin the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the us
Lets leave this one unresolved for a moment
https://github.com/zkSNACKs/WalletWasabi/issues/7122#issuecomment-1033173396

2022-02-09 00:17 UTC, BTCparadigm commented on docs/using-wasabi/ELI5.md
> +The wallet will then automatically coinjoin the remaining coins or the change outputs that the user receives back after creating transactions, but the coordinator fees will not be charged from the us
Meh, updated the section anyway. We can make an addition later about the delay if needed and if the delay concept is solid.

2022-02-11 00:50 UTC, yahiheb requested changes

2022-02-11 00:50 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +6. Type in your password and click `Continue`.
This is not how send works now.

2022-02-11 00:50 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +If you don't like that your employer knows about where you spend your money, or that a merchant can find out how much money you have, then you should coinjoin your bitcoin, as this breaks link to its
```suggestion
If you don't like that your employer knows where you spend your money, or that a merchant can find out how much money you have, then you should coinjoin your bitcoin, as this breaks link to its transaction history.
```

2022-02-11 00:50 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +Once a coin achieves enough ambiguity, the corresponding amount will show up in the software's main view as "private coins".
```suggestion
Once a coin achieves enough anonymity, the corresponding amount will show up in the software's main view as "private coins".
```

2022-02-11 00:50 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +The wallet will also automatically coinjoin the change output that the user gets back after creating a transaction, but the coordinator fees will not be charged again.
This is confusing, it is like coordinator fees are free for any change transaction which is not the case.

2022-07-07 15:21 UTC, yahiheb requested changes

2022-07-07 15:21 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
> +In case you want to coinjoin these coins, click Play in the main views musicbox and choose a fitting profile setting for your wallet.
```suggestion
In case you want to coinjoin these coins, click Play in the main view's musicbox and choose a fitting profile setting for your wallet.
```

2022-07-07 15:21 UTC, yahiheb commented on docs/using-wasabi/ELI5.md
>  6. Type in your password and click `Continue`.
```suggestion
5. Type in your password and click `Continue`.
```

2022-07-07 17:49 UTC, yahiheb approved these changes
Good job @BTCparadigm

2022-07-07 18:11 UTC, MarnixCroes approved these changes
ACK

2022-07-08 15:14 UTC, merged