Update CoinJoin.md
zkSNACKs/WasabiDoc pull request #1051
Opened 2022-02-09 00:55 UTC by BTCparadigm

Started updating this file and realized it's a bad idea at this point.
Creating PR anyway for the updated part.

2022-02-11 01:15 UTC, yahiheb requested changes

2022-02-11 01:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +WabiSabi enables centrally coordinated coinjoins with variable amounts in a trustless (meaning nobody can steal) and private (meaning even the coordinator cannot spy) manner, as described in [WabiSab
```suggestion
WabiSabi enables centrally coordinated coinjoins with variable amounts in a trustless (meaning nobody can steal) and private (meaning even the coordinator cannot spy) manner, as described in [WabiSabi protcol](https://eprint.iacr.org/2021/206).
```

2022-02-11 01:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +By default, Wasabi starts automatically coinjoining the funds whenever there's more than 0.01 BTC in total.
```suggestion
By default, Wasabi starts automatically coinjoining the funds whenever there's more than 0.01 BTC non private in total.
```

2022-02-11 01:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +Wallets with less than 0.01 BTC are in _PlebStop-mode_, where funds are not coinjoined automatically.
```suggestion
Wallets with less than or equal to 0.01 BTC are in _PlebStop_ mode, where funds are not coinjoined automatically.
```

2022-02-11 01:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +User can change the limit from the settings and boost the wallets privacy for one session if wanted.
This is not in the settings yet, and why only for one session?

2022-02-11 01:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +In the first coinjoin, a 0.3% coordinator fee will be taken from UTXO's bigger than 0.01 BTC.
```suggestion
In the first coinjoin, a 0.3% coordinator fee will be taken from UTXOs bigger than 0.01 BTC.
```

2022-02-11 01:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The round starts either as soon as 100 inputs have been registered, or after one hour has elapsed since the last round.
Is it limited to 100 inputs or participants?

2022-02-11 01:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +So if you send a payment and receive a change output, Wasabi will automatically remix it without you having to pay coordinator fees again.
Saying that a change output will be automatically remixed is wrong. There are many variables for a coin to be selected for coinjoin.

2022-02-11 01:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The recipient of the payment will also be able to coinjoin the funds he recieved with only the cost of network fees, as long he/she is also using Wasabi or other WabiSabi compatible Bitcoin wallet.
> as long he/she is also using Wasabi

This is not correct, I might be using another bip 39 compatible wallet, and recover it in Wasabi, so I can coinjoin without paying coordinator fee.

2022-02-11 01:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +Once a coin achieves enough ambiguity, the corresponding amount will show up in the software's main view as "private coins".
```suggestion
Once a coin achieves enough anonymity, the corresponding amount will show up in the software's main view as "private coins".
```

2022-02-11 10:35 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +The round starts either as soon as 100 inputs have been registered, or after one hour has elapsed since the last round.
100 inputs. The coordinator doesn't know about participants.
https://tumblebit.slack.com/archives/CFBJX6MN0/p1644575203714149

2022-07-10 02:24 UTC, BTCparadigm commented
Will need help to finish this PR. 
Can't convert to draft but WIP.

2022-07-12 05:59 UTC, yahiheb requested changes

2022-07-12 05:59 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +User can change the limit from settings or turn coinjoin on manually by pressing the play button in main views "music box".
```suggestion
User can change the limit from the settings or turn coinjoin on manually by pressing the play button of the music box in the main view.
```

2022-07-12 05:59 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +A 0.3% coordinator fee will be taken from fresh UTXOs bigger than 0.01 BTC.
```suggestion
A 0.3% coordinator fee will be taken from fresh coins bigger than 0.01 BTC.
```

2022-07-12 05:59 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The round starts either as soon as 300 inputs have been registered, or after the input registration time has ran out and as long as there's at least 150 inputs registered.
I am not sure if we should mention the exact numbers here, because they might change.

2022-07-12 05:59 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +These coins need to be confirmed on the Bitcoin blockchain unless they are from a Wasabi coinjoin and the robot is re-register them.
```suggestion
These coins need to be confirmed on the Bitcoin blockchain unless they are from a Wasabi coinjoin and the robot is re-registering them.
```

2022-07-12 05:59 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +In the background, Wasabi generates an input proofs, signatures over a challenge message with the private key that locks up the coins.
```suggestion
In the background, Wasabi generates input proofs, signatures over a challenge message with the private key that locks up the coins.
```

2022-10-07 06:41 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +The round starts either as soon as 300 inputs have been registered, or after the input registration time has ran out and as long as there's at least 150 inputs registered.
```suggestion
The round starts either as soon as enough inputs have been registered, or after the input registration time is reached and as long as the minimum number of inputs are registered.
```

2022-10-07 06:41 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +WabiSWabi protocol requires 5 steps to successfully create and broadcast a coinjoin transaction to the bitcoin network.
```suggestion
WabiSabi protocol requires 5 steps to successfully create and broadcast a coinjoin transaction to the bitcoin network.
```

2022-10-07 06:42 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +These coins need to be confirmed on the Bitcoin blockchain unless they are from a Wasabi coinjoin and the robot is re-register them.
```suggestion
These coins need to be confirmed on the Bitcoin blockchain.
```

2022-10-07 06:43 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +In the background, Wasabi generates an input proofs, signatures over a challenge message with the private key that locks up the coins.
```suggestion
In the background, Wasabi generates input proofs, a signatures over a challenge message with the private key that locks up the coins.
```

2022-10-07 06:45 UTC, yahiheb commented
@BTCparadigm Open a new PR to the master branch.

2022-10-07 06:45 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +The recipient of the payment will also be able to coinjoin the funds he recieved with only the cost of network fees, as long he/she is also using Wasabi or other WabiSabi compatible Bitcoin wallet.
```suggestion
The recipient of the payment will not have to pay coordinator fee, as long he is making coinjoins with the same coordinator.
```

2022-10-07 06:45 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +The recipient of the payment will also be able to coinjoin the funds he recieved with only the cost of network fees, as long he/she is also using Wasabi or other WabiSabi compatible Bitcoin wallet.
```suggestion
The recipient of the payment will not have to pay coordinator fee, as long he is making coinjoins with the same coordinator.
```

2022-10-07 06:58 UTC, yahiheb commented
@BTCparadigm This PR seems to be good, open a new one to the master branch.

2022-10-07 06:58 UTC, closed without merging

2022-10-07 07:52 UTC, BTCparadigm commented
Was going to but apparently @MaxHillebrand did it first.