Update README.md
zkSNACKs/WasabiDoc pull request #1075
Opened 2022-05-19 16:33 UTC by BTCparadigm

Inform users about ongoing construction work and use new repo pic.
Please suggest a better text if you have something in mind.

Removing some extra text.

2022-05-19 21:19 UTC, yahiheb requested changes

2022-05-19 21:19 UTC, yahiheb commented on README.md
> +DOCUMENTATION FOR WASABI 2.0 HAS ONLY BEGUN. BE AWARE THAT MANY PAGES HAVE NOT YET BEEN UPDATED TO MATCH THE NEW SOFTWARE RELEASE!
How about adding this text before the image?

2022-06-14 17:42 UTC, BTCparadigm commented
#1081 apparently is a duplicate of this. @yahiheb please close the one you like less

2022-06-15 00:43 UTC, yahiheb commented
> #1081 apparently is a duplicate of this. @yahiheb please close the one you like less

Merged #1081

2022-06-15 00:44 UTC, closed without merging