[Docs-2.0] TechnicalOverview.md into FutureOfWasabiWallet.md V2
zkSNACKs/WasabiDoc pull request #1087
Opened 2022-07-09 23:01 UTC by BTCparadigm

I got confused with the old PR #1029 so I recreated this from up to date Docs-2.0 branch.

Big document and many things are still not 100% clear. 
Laying out future plans is very important, especially for new contributors, but as its impossible for me to write everything down at once, I suggest we keep improving this file gradually. 
Lots of input needed especially from @MaxHillebrand and @nopara73

2022-07-10 07:21 UTC, MarnixCroes requested changes
updated some outdated info, some typos, some nits

2022-07-10 07:21 UTC, MarnixCroes commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +For now, WabiSabi is only enabled for testnet clients, which means there is very little incentive for malicious attackers to reveal if they see a problem in the protocol.
```suggestion
Improvements are still being made.
```

2022-07-10 07:21 UTC, MarnixCroes commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Currently Wasabi only shows cluster control window when user doesn't have enough of it's balance as private.
```suggestion
Currently Wasabi only shows the cluster control window when the user doesn't have enough of it's balance as private.
```

2022-07-10 07:21 UTC, MarnixCroes commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Wasabi should enable users to make payments to multiple addresses in the same transaction, in a convenient and privacy presenving way.
```suggestion
Wasabi should enable users to make payments to multiple addresses in the same transaction, in a convenient and privacy preserving way. 
```

2022-07-10 07:21 UTC, MarnixCroes commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### WAT?
?

2022-07-10 08:58 UTC, MaxHillebrand requested changes
Well done!

But should this file even be in the documentation? It seems more adequate as a blog post.

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +  "description": "This document aims to describe some ideas for the future of Wasabi Wallet and to explain the reasoning behind going towards these objectives. Plans might change without notice and t
This description is shown in the link preview, it should be highly relevant and short.


```suggestion
  "description": "This document aims to describe some ideas for the future of Wasabi Wallet and to explain the reasoning behind going towards these objectives. This is the Wasabi documentation, an archive of knowledge about the open-source, non-custodial and privacy-focused Bitcoin wallet for desktop.",
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Wasabi does not support and does not plan to support other currencies in the future.
```suggestion
Wasabi does not support and does not plan to support other currencies in the future, it will always be bitcoin-only.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Whenever mainchain coinjoin release candidate comes out, we will likely see a lot of new testers with a bunch of issues and improvement ideas.
```suggestion
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Change amount and maybe in some cases the payment amount should be grinded in to next lower standard denomination, making it very difficult to the recipient to figure out anything about the sender.
```suggestion
Being able to send payments in coinjoin is a great blockspace efficiency and privacy improvement for both the sender and the receiver.
Change amount and maybe in some cases the payment amount should be split into standard denominations.
With Wabisabi pay to endpoint users can send each other money without the sender knowing the address of the receiver, or the receiver knowing the inputs of the sender.
This also enables anonymous transaction batching.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Because Bitcoin blocks have size limit and every input and output in a coinjoin has weight, it is not possible to add thousands of transactions to a coinjoin round.
```suggestion
Because bitcoin blocks have a size limit, it is not possible to add thousands of inputs and outputs to a coinjoin transaction.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### P2M
```suggestion
#### Transaction batching
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +This would save users some sats in transaction fees but it comes with the cost of all recipients being able to see the other outputs in the transaction.
```suggestion
This would save users sats in mining fees but it comes with the cost of all recipients being able to see the other outputs in the transaction.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +If the transaction doesn't have a lot of them, this might be a privacy issue.
```suggestion
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Some users might be ok with that but combining P2M with Send in Coinjoins would definitely make it more private for everyone.
```suggestion
Some users might be ok with that but making batched payments inside coinjoin would definitely make it more private for everyone.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +
```suggestion

This allows users to speed up the confirmation time of transactions, and even cancel unconfirmed payments.

Fee bumping coinjoin transactions is expensive, but possible for any output.
A service provider can spend his coinjoin output in an rbf transaction, and then fee bump that spending transaction whenever users pay him off-chain.

```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +However, this is happening in a low Bitcoin fee environment, so this is not to be taken for granted in the future.
```suggestion
However, this is happening in a low transaction fee environment, so this is not to be taken for granted in the future.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Currently Wasabi Wallet uses bech32 addresses (bc1q...) only but developers are working on enabling P2TR (bc1p...).
```suggestion
Currently Wasabi Wallet uses only segwit v0 addresses (bc1q...) but developers are working on enabling taproot addresses (bc1p...).
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Improving the user friendliness of the software, the accuracy of coin awareness, and presenting what happens on the blockchain can be beneficial.
```suggestion
Improving the user friendliness of the software, the accuracy of coin awareness, and presenting what happens on the blockchain can be beneficial.

The default UX should be very simple and intuitive, with a lot of concepts abstracted and under the hood.
But at each point the user can opt-in to more insight and control.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Wasabi Wallet contributors are encouraged to participate and maybe even create Bitcoin and privacy related events, to make sure they stay up to date about the latest research and features.
```suggestion
Wasabi Wallet contributors are encouraged to participate and create bitcoin and privacy related events, to make sure they stay up to date about the latest research and features.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Wasabi offers a daemon and an RPC interface.
```suggestion
Wasabi currently offers a rudimentary RPC interface.
This should be improved in architecture and functionality.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Full information can be found [here](/using-wasabi/Daemon.md) and [here](/using-wasabi/RPC.md).
```suggestion
Full information can be found [here](/using-wasabi/RPC.md).
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Full information can be found [here](/using-wasabi/Daemon.md) and [here](/using-wasabi/RPC.md).
```suggestion
Wasabi should be able to start and run in a headless daemon mode with full wallet functionality via the RPC server.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### WAT?
```suggestion
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Working on it!
```suggestion
There should be a comprehensive documentation with guides of how to use the software, and more information about how it works under the hood.
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +By them integrating WabiSabi, they receive sats everytime their users participates in a coinjoin and pays coordinator fees.
```suggestion
```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +
```suggestion
But WabiSabi should be easily usable by software written in other languages.

```

2022-07-10 08:58 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Wasabi should continue developing and implementing new in-house features that has become industry standards during the years, like discreet mode, coin control and coinjoins.
```suggestion
Wasabi should continue researching and implementing new concepts and features.
```

2022-07-10 11:59 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Wasabi does not support and does not plan to support other currencies in the future, it will always be bitcoin-only.
This is not true. Wasabi is bitcoin-only, because Bitcoin is going to be the most likely winner of the currency wars. We should certainly not be religious about it and if Bitcoin is losing its market share, this position must be reconsidered.

https://github.com/zkSNACKs/Meta#bitcoin-only

2022-07-10 12:02 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +![Future of Wasabi Wallet in 2021 December](https://user-images.githubusercontent.com/51679301/147867076-bc6e74ed-13f6-455e-8fdb-72ff8e6a03d7.jpg)
Please censor the companies in there. They may not want this to be public and we should respect that.

2022-07-10 12:04 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Being able to send payments in coinjoin is a great blockspace efficiency and privacy improvement for both the sender and the receiver.
The privacy improvement is none to little.

2022-07-10 12:06 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +With Wabisabi pay to endpoint users can send each other money without the sender knowing the address of the receiver, or the receiver knowing the inputs of the sender.
Hmm. I wonder if this is feasible at all.

2022-07-10 12:06 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Being able to send payments in coinjoin is a great blockspace efficiency and privacy improvement for both the sender and the receiver.
Ok, well, this is convincing: https://github.com/zkSNACKs/WasabiDoc/pull/1087/files#r917386032

2022-07-10 12:07 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +If that doesn't happen enough by default, the coordinator has ways to incentivize users, for example by giving fee discounts for remixed inputs.
This happens by default, so this section can be removed.

2022-07-10 12:08 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### Coin Control
Coin control is obsolete. Remove this.

2022-07-10 12:09 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### Simple Send Improvements
Meh

2022-07-10 12:10 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### P2M
It's meh too. Not because I don't want this, but because it's like a miniscule feature just like the previous ones. This document should focus on higher level and more useful things, rather than all kinds of little things.

2022-07-10 12:11 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### Sweep Private Key
Another meh. I want it, but it's super uninportant.

2022-07-10 12:12 UTC, MaxHillebrand requested changes

2022-07-10 12:12 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Wasabi does not support and does not plan to support other currencies in the future, it will always be bitcoin-only.
```suggestion
```

2022-07-10 12:12 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Being able to send payments in coinjoin is a great blockspace efficiency and privacy improvement for both the sender and the receiver.
It is a substantial improvement, the receiver does not know which inputs or other outputs the sender has.

2022-07-10 12:12 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +If that doesn't happen enough by default, the coordinator has ways to incentivize users, for example by giving fee discounts for remixed inputs.
```suggestion
```

2022-07-10 12:12 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### Coin Control
Only obsolete in the default UX, not in the wallet as a whole though.

2022-07-10 12:12 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +## Marketing
You can remove this section. It's has no place in "technical overview"

2022-07-10 12:13 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +The concept of network-analysis resistant smartphone wallets is not yet proven.
It is proven already. See Breez wallet.

2022-07-10 12:13 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +If we attempted to port Wasabi's code today, the wallet would use too much storage space, battery and network.
I don't like this. It's not really about the timing, it's about how much work it is :)

2022-07-10 12:14 UTC, MaxHillebrand requested changes

2022-07-10 12:14 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Wasabi Wallet contributors are encouraged to participate and create bitcoin and privacy related events, to make sure they stay up to date about the latest research and features.
```suggestion
```

2022-07-10 12:14 UTC, MaxHillebrand commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Besides of the online Bitcoin privacy that Wasabi Wallet offers, we could spin up a merchandise store that offers shirts, mugs, hats and some of the best meat-space privacy tools like curtains and un
```suggestion
```

2022-07-10 12:15 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### Libraries
It means software libraries, not real world ones :D

2022-07-10 12:15 UTC, nopara73 reviewed
This is a wishlist, not technical plans.

2022-07-10 12:17 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +Being able to send payments in coinjoin is a great blockspace efficiency and privacy improvement for both the sender and the receiver.
They don't know already. Users coinjoin before send and after send.

2022-07-10 12:18 UTC, nopara73 commented on docs/building-wasabi/FutureOfWasabiWallet.md
> +#### Coin Control
It's obsolete as a privacy technology.

2022-07-10 12:20 UTC, BTCparadigm commented
Lol.
I made 1 commit and few hours later I wake up to see 55 comments and 32 commits 

https://user-images.githubusercontent.com/51679301/178144640-52c8acf8-6c1f-4cda-bc35-7d1a54279d95.mp4

2022-07-10 12:27 UTC, BTCparadigm commented
Just kidding, good that you guys are reviewing.

@nopara73 The idea was to change this TechnicalOverview document in to FutureOfWasabiWallet, as its part of `Building Wasabi`. 
Giving new and existing contributors an idea of what are we aiming for could be really helpful. As mentioned in the beginning, its only a loose guideline that might change without further notice or update. 
In case it becomes a wishlist, good. Contributors will know how they can score some extra points.

Previous TechnicalOverview was a detailed explanation of exacly that + a bunch of future ideas, so it was confusing.

2022-07-10 12:31 UTC, BTCparadigm commented
If we can get a cACK for this, let's merge it and nitpick/add/remove on separate PR.
Idea is, if its better than before, ACK or improve more. 
Otherwise we are going to just recreate the previous +100 comment PRs and get stuck.

2022-10-07 06:54 UTC, yahiheb commented
@BTCparadigm If you want make a new PR to the master branch.

2022-10-07 06:54 UTC, closed without merging

2022-11-14 12:05 UTC, MarnixCroes commented
> @BTCparadigm If you want make a new PR to the master branch.

@BTCparadigm what's up with this?

2022-11-20 11:50 UTC, BTCparadigm commented
Feel free to update or salvage if you want.