[Docs-2.0] Update Receive.md
zkSNACKs/WasabiDoc pull request #1088
Opened 2022-07-10 00:45 UTC by BTCparadigm

Deleted bunch of non-receive related stuff.
Update to 2.0

2022-07-12 18:40 UTC, MaxHillebrand commented on docs/using-wasabi/Receive.md
> +In Wasabi it is mandatory to give every receive address a label, so that later auto coinjoin-robot knows where you got the coin from and what to do with it.
```suggestion
In Wasabi it is mandatory to give every receive address a label, so that later you know where you got the coin from and what to do with it. 
```

2022-07-12 18:40 UTC, MaxHillebrand approved these changes
nice.

2022-07-12 18:57 UTC, MarnixCroes requested changes

2022-07-12 18:57 UTC, MarnixCroes commented on docs/using-wasabi/Receive.md
> -Wasabi is not like other Bitcoin wallets, it is a privacy-oriented wallet and every feature and every design decision is based mainly (sometimes exclusively) on privacy costs/benefits analysis.
this is an important piece of information, maybe keep it?

2022-07-12 18:57 UTC, MarnixCroes commented on docs/using-wasabi/Receive.md
> +2. Click `Receive` button in the main views top right corner.
```suggestion
2. Click the `Receive` button in the main view's top right corner.
```

2022-07-12 18:58 UTC, MarnixCroes commented
for the `Receive Address` image, I would use a mainnet address instead of tesnet. to prevent confusion

2022-07-13 02:29 UTC, yahiheb commented
> for the `Receive Address` image, I would use a mainnet address instead of tesnet. to prevent confusion

I agree with this.

2022-07-14 14:33 UTC, BTCparadigm commented
I agree but let's not worry about the network settings yet. 
https://github.com/zkSNACKs/WasabiDoc/issues/1022#issuecomment-1184515964

2022-07-18 01:15 UTC, yahiheb requested changes

2022-07-18 01:15 UTC, yahiheb commented on docs/using-wasabi/Receive.md
> -For that reason, many of its features depend on each other and a correct understanding of how they play together is critical to achieve and improve the privacy of our transactions.
I agree with @MarnixCroes. IMO we should keep this, and the sentence after it ofc.

2022-07-18 01:15 UTC, yahiheb commented on docs/using-wasabi/Receive.md
> -The label has to tell us who are the observers that know about that coin.
I guess we should keep this one also, as it explains the importance of labeling.

2022-07-18 22:05 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet address' QR code](/ReceiveAddress.png "Wasabi Wallet address' QR code")
What do you mean? 
We dont have ReceiveAddressDropDownMenu in 2.0, so I changed the pic in to the next closest thing.

2022-07-21 23:15 UTC, yahiheb commented on docs/using-wasabi/Receive.md
> +3. Type in the name of the entities who know about this address. Optionally you can click on the suggested labels, in case you've used them before.
> If a user has already used a label before I think we should emphasize that it is better to choose from the suggested labels, to avoid typos.

I think this is very important to add.

2022-07-28 00:15 UTC, BTCparadigm commented on docs/using-wasabi/Receive.md
> -The label has to tell us who are the observers that know about that coin.
The whole `The importance of labeling` section explains exactly that.

2022-07-28 00:19 UTC, BTCparadigm commented on docs/using-wasabi/Receive.md
> -### Clusters
Cluster is not a concept used in the wallet as its difficult to measure, so I'd move it do glossary or something.
We use pockets, which should be explained but maybe in a separate PR.

2022-07-28 00:25 UTC, BTCparadigm commented on docs/using-wasabi/Receive.md
> -For that reason, many of its features depend on each other and a correct understanding of how they play together is critical to achieve and improve the privacy of our transactions.
I dont think that texts belongs to `Receive.md`.

2022-08-03 17:24 UTC, yahiheb requested changes

2022-08-03 17:24 UTC, yahiheb commented on docs/using-wasabi/Receive.md
> +Optionally you can click on the suggested labels, in case you've used them before.
```suggestion
If you have already used a label before, simply choose it from the suggested labels.
```

2022-10-01 21:37 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet address details](/ReceiveAddress.png "Wasabi Wallet address details")
What do you mean?
We dont have ReceiveAddressDropDownMenu in 2.0, so I changed the pic in to the next closest thing.

2022-10-02 00:16 UTC, yahiheb commented
Open a new PR to edit the master branch

2022-10-02 00:39 UTC, closed without merging