[Docs-2.0] Update `Testnet.md` to 2.0
zkSNACKs/WasabiDoc pull request #1091
Opened 2022-07-10 13:43 UTC by BTCparadigm

2022-07-12 18:36 UTC, MarnixCroes requested changes

2022-07-13 02:15 UTC, yahiheb requested changes
The pictures should have the default values IMO.
For example `SettingsBitcoin.png` should be replaced where the default dust threshold is shown.
Same for the `SettingsGeneral.PNG` file.

2022-07-14 14:34 UTC, BTCparadigm commented
I agree but let's not worry about the settings yet.
https://github.com/zkSNACKs/WasabiDoc/issues/1022#issuecomment-1184515964

2022-07-14 17:45 UTC, yahiheb approved these changes
LGTM

2022-07-14 17:45 UTC, merged