[Docs-2.0] Update FAQ generate wallet
zkSNACKs/WasabiDoc pull request #1094
Opened 2022-07-14 19:54 UTC by BTCparadigm

Currently coinjoin strategy selection is in the wallet creation workflow, which makes it complicated to explain. Tried to do it bluntly and without repeating same things as in pictures.
https://github.com/zkSNACKs/WalletWasabi/issues/8714

Ping @MarnixCroes use whatever you like here in the WalletGeneration.md
In the end, this FAQ section should be just pointing to that one to avoid repetition in the documentation.

2022-07-15 06:32 UTC, MarnixCroes requested changes

2022-07-15 06:32 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Just click `Add Wallet` button in the bottom left corner of the main view to start the process.
```suggestion
Click the `Add Wallet` button in the bottom left corner of the main view or in the searchbar.
```

2022-07-15 06:32 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Make sure that you are precise so that you know what this wallet is for ande click `Continue`.
```suggestion
Make sure that you are precise so that you know what this wallet is for and click `Continue`.
```

2022-07-15 06:32 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Set up a password that will be used to encrypt the private key (extracted from the extended private key) on the computer.
```suggestion
Add a password. It is used to encrypt the private key (extracted from the extended private key) on the computer and needed to open the wallet.
```

2022-07-15 06:32 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Once you've typed the same password to both rows, click `Continue`.
```suggestion
Confirm the password and click `Continue`.
```

2022-07-15 06:32 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Once you're done, 'click `Continue` or skip the verification by clicking `Skip`.
skip is only on testnet

2022-07-15 06:32 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +If you do not want to set this wallet a strategy right now, dont click any of the options but just `Continue` to skip this phase for now.
I think you can't skip it

2022-07-19 15:30 UTC, MarnixCroes approved these changes

2022-08-08 23:02 UTC, yahiheb commented
We might remove the coinjoin profile selection completely.

https://github.com/zkSNACKs/WalletWasabi/issues/8880

2022-09-28 07:07 UTC, MarnixCroes commented
the images are already added, maybe remove them 
or open new PR with only the FAQ text?

2022-10-01 22:33 UTC, BTCparadigm commented
"code"
![image](https://user-images.githubusercontent.com/51679301/193430706-0672d807-3652-4a0a-b995-540b28714b8c.png)

2022-10-02 00:07 UTC, yahiheb commented
Make a new PR to the master branch.

2022-10-02 00:39 UTC, closed without merging