[Docs-2.0] FAQ-UseWasabi small update 1
zkSNACKs/WasabiDoc pull request #1095
Opened 2022-07-14 20:21 UTC by BTCparadigm

Part of a series of PRs required to update FAQ-UsingWasabi

2022-07-18 09:43 UTC, MarnixCroes requested changes

2022-07-18 09:43 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Wasabi stores only the BIP38 encrypted blob, so you'll need to type in the password to spend or coinjoin from Wasabi.
```suggestion
Wasabi stores only the BIP38 encrypted blob, so you'll need to type in the password to open the wallet and to spend from Wasabi.
```

2022-07-19 15:27 UTC, MarnixCroes requested changes

2022-07-19 15:27 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +You know that Tor and backend is properly connected when you see a checkmark at the bottom right corner of the synchronization page.
```suggestion
You know that Tor and the backend are properly connected when you see a check mark at the bottom right corner of the synchronization page.
```

2022-07-19 15:27 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +All the block filters and all the relevant blocks are downloaded and the wallet is synchronized when the timer of the page runs out.
```suggestion
The timer of the page runs out when all the block filters and all the relevant blocks are downloaded and the wallet is synchronized.
```

2022-08-07 16:14 UTC, yahiheb requested changes

2022-08-07 16:17 UTC, yahiheb requested changes

2022-08-07 16:17 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +You know that Tor and the backend are properly connected when you see a check mark at the bottom right corner of the synchronization page.
```suggestion
Once Tor and backend are properly connected and you have peers, you will see a checkmark at the bottom right corner of the main view.
```

2022-08-07 16:33 UTC, yahiheb approved these changes

2022-08-07 16:33 UTC, merged