[Docs-2.0] FAQ-UseWasabi small update 2
zkSNACKs/WasabiDoc pull request #1096
Opened 2022-07-14 22:54 UTC by BTCparadigm

Part of a series of PRs required to update FAQ-UsingWasabi
![i-am-once-again-asking-for-your-pull-request-approval-15667-1](https://user-images.githubusercontent.com/51679301/179104323-1e11afeb-a8f2-454c-a677-62b3be9f4325.jpg)

2022-07-18 09:46 UTC, MarnixCroes requested changes

2022-07-18 09:46 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Then you can click on `Continue` which will now show you the address, and immediately copy it to the clipboard.
```suggestion
Then you can click on `Continue` which will now show you the address, and you can copy it to the clipboard.
```

2022-07-18 09:46 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Then you can click on `Continue` which will now show you the address, and immediately copy it to the clipboard.
That's only when auto copy is on

2022-07-18 12:20 UTC, MarnixCroes approved these changes

2022-08-08 22:31 UTC, yahiheb requested changes

2022-08-08 22:31 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
>  You can generate a new bech32 address in the `Receive` tab of Wasabi Wallet.
```suggestion
You can generate a new bech32 address in the `Receive` dialog of Wasabi Wallet.
```

2022-08-08 22:31 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
>  First you must set a label for it, so that you later know who has sent you bitcoin to this address.
```suggestion
First you must set a label for it, so that you later know who knows that this address is yours.
```

2022-08-08 22:31 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Thus receiving addresses and sending transactions should be carefully labeled with the observers who knows that this address belongs to you.
```suggestion
Thus receiving addresses and sending transactions should be carefully labeled with the observers who know that this address belongs to you.
```

2022-08-08 22:48 UTC, yahiheb requested changes

2022-08-08 22:48 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Open the wallet folder via search bar -> Wallet Folder.
```suggestion
Open the wallet folder by typing `Wallet Folder` in the search bar.
```

2022-08-08 22:48 UTC, yahiheb approved these changes

2022-08-08 22:56 UTC, merged