[Docs-2.0] FAQ-UseWasabi small update 3
zkSNACKs/WasabiDoc pull request #1098
Opened 2022-07-15 00:18 UTC by BTCparadigm

Part of a series of PRs required to update FAQ-UsingWasabi
![image](https://user-images.githubusercontent.com/51679301/179122047-16575cad-6183-4e4a-9950-76f7776c8638.png)

2022-07-18 09:48 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +For example, due to the malleability fix of SegWit, you can now remix coinjoin outputs which are currently unconfirmed.
```suggestion
For example, due to the malleability fix of SegWit, you can now remix coinjoin outputs which are currently unconfirmed.
```
```suggestion
For example, due to the malleability fix of SegWit, you can now remix coinjoin outputs which are currently unconfirmed.
```
```suggestion
For example, due to the malleability fix of SegWit, you can now remix coinjoin outputs which are currently unconfirmed.
```

2022-07-18 09:51 UTC, MarnixCroes requested changes

2022-07-18 09:51 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +For example, due to the malleability fix of SegWit, you can now remix coinjoin outputs which are currently unconfirmed.
in 2.0 only confirmed coins can coinjoin

2022-07-18 09:51 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +You can see the address and its QR code when you create it through `Receive` tab.
```suggestion
You can see the address and its QR code when you create it through the `Receive` dialog.
```

2022-07-19 15:42 UTC, MarnixCroes approved these changes

2022-07-19 15:42 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +This can be done through `Reveive->Unused Receive Addresses->Edit`, in the right side of the label.
```suggestion
Go to the Unused Receive Addresses list:  `Receive->Unused Receive Addresses`, and click on the pencil icon to edit the labels.
```

2022-08-08 23:27 UTC, yahiheb requested changes

2022-08-08 23:27 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
>  On TestNet and RegTest Wasabi uses `m/84'/0'/0'`, and not the standard `m/84'/1'/0'`.
```suggestion
On TestNet Wasabi uses the path `m/84'/1'/0'`.
On RegTest it uses `m/84'/0'/0'`, and not the standard `m/84'/1'/0'` path.
```

2022-08-08 23:27 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Go to the Unused Receive Addresses list:  `Receive->Unused Receive Addresses`, and click on the pencil icon to edit the labels.
```suggestion
Go to the Unused Receive Addresses list:  `Receive` -> `Unused Receive Addresses`, and click on the pencil icon to edit the labels.
```

2022-08-08 23:27 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Wasabi was created after the activation of SegWit, and it made sense to support the most advanced address type, which has numerous benefits.
```suggestion
Wasabi was created after the activation of SegWit, and it made sense to support the most advanced address type, which has numerous benefits, like large savings on mining fees for SegWit transactions.
```

2022-08-09 00:36 UTC, yahiheb requested changes

2022-08-09 00:36 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet address' QR code](/ReceiveAddress.png "Wasabi Wallet address' QR code")
There is no such a file `ReceiveAddress.png`

2022-09-28 07:06 UTC, MarnixCroes commented
can we merge this?

2022-10-01 21:40 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet address' QR code](/ReceiveAddress.png "Wasabi Wallet address' QR code")
True. Its in https://github.com/zkSNACKs/WasabiDoc/pull/1088/files

2022-10-02 00:13 UTC, yahiheb commented
@BTCparadigm Make a new PR to the master branch

2022-10-02 00:39 UTC, closed without merging