[Docs-2.0] FAQ-UseWasabi small update 4
zkSNACKs/WasabiDoc pull request #1100
Opened 2022-07-15 13:32 UTC by BTCparadigm

Part of a series of PRs required to update FAQ-UsingWasabi
Mostly Send related stuff. 
Deleted "How can I use the MAX button?" as we dont have one.

2022-07-18 09:56 UTC, MarnixCroes approved these changes
good. two nits

2022-07-18 11:53 UTC, MarnixCroes approved these changes

2022-07-31 23:03 UTC, yahiheb requested changes

2022-10-01 21:54 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +`To` in the `Send` view.
I believe I'm answering the weird question.

2022-10-02 00:09 UTC, yahiheb commented
This PR was made to edit the doc2.0 branch.
Make a new one to the master branch.

2022-10-02 00:39 UTC, closed without merging