add WabiSabi to glossary
zkSNACKs/WasabiDoc pull request #1102
Opened 2022-07-17 20:40 UTC by MarnixCroes

the `Read more` could link to a future explainer in the docs
I think it is ok for now.

2022-07-17 22:00 UTC, yahiheb requested changes

2022-07-17 22:00 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +Read more: [WabiSabi](https://github.com/zkSNACKs/WabiSabi)
How about linking to the latest version of the WabiSabi paper:

```suggestion
Read more: [WabiSabi](https://github.com/zkSNACKs/WabiSabi/releases/latest/download/WabiSabi.pdf)
```

2022-07-18 15:23 UTC, BTCparadigm approved these changes

2022-07-18 22:38 UTC, yahiheb approved these changes

2022-07-18 22:43 UTC, merged