[2.0] FAQ: update fees for coinjoin
zkSNACKs/WasabiDoc pull request #1128
Opened 2022-08-01 13:40 UTC by MarnixCroes

credits @BTCparadigm https://github.com/zkSNACKs/WasabiDoc/pull/1125#pullrequestreview-1057274879

2022-08-02 01:10 UTC, yahiheb requested changes

2022-08-02 01:10 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Coinjoining UTXOs with a value above 0.01 BTC costs 0.3% as a [coordinator](https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi.Backend) fee + [mining fees](https://mempool.space/).
I don't see a reason to link to those:

```suggestion
Coinjoining UTXOs with a value above 0.01 BTC costs 0.3% as a coordinator fee + mining fees.
```

2022-08-02 19:47 UTC, yahiheb requested changes

2022-08-02 19:47 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Thus, a payment made with coinjoined funds allows the sender and the recipient to remix their coins without paying any coordinator fees.
How about this tweak:

```suggestion
Coinjoin fees are composed of coordination fees and mining (network) fees.
Coins with a value above 0.01 BTC pay 0.3% as a coordination fee + mining fees.
Coins of 0.01 BTC or below don't pay coordination fees.
Remixes, even after one transaction, also don't pay coordination fees. 
Thus, a payment made with coinjoined funds allows the sender and the recipient to remix their coins without paying any coordination fees.
```

2022-08-02 19:50 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Thus, a payment made with coinjoined funds allows the sender and the recipient to remix their coins without paying any coordinator fees.
good.
imo `UTXO` is better fit in this context instead of `coins`?

2022-08-03 00:21 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Thus, a payment made with coinjoined funds allows the sender and the recipient to remix their coins without paying any coordinator fees.
I think coins is easier to understand for the average person.
I have updated the suggestion to say `Coins (UTXOs)`.

2022-08-05 04:15 UTC, yahiheb approved these changes

2022-08-05 04:15 UTC, merged