FAQ UseWasabi: add privacy progress
zkSNACKs/WasabiDoc pull request #1136
Opened 2022-08-04 15:20 UTC by MarnixCroes

2022-08-27 17:01 UTC, yahiheb requested changes

2022-08-27 17:01 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The privacy progress indicates the percentage of the wallet balance in coins above the anonscore target.
This is not correct. Even if all your coins did not reach your anonscore target you will get some privacy progress.

```suggestion
The privacy progress tile represents the percentage of how much private the wallet is.

It considers the anonymity score weighted amounts instead of just amounts that reached the anonymity score threshold.

The private value is the total amount that reached the anonscore threshold.
```

2022-08-30 01:09 UTC, jesse-marks commented on docs/FAQ/FAQ-UseWasabi.md
> +The privacy progress indicates the percentage of the wallet balance in coins above the anonscore target.
Minor edit to the line 195 suggestion by @yahiheb. 

```suggestion
The privacy progress tile represents the percentage of how private the wallet is.
```
or
```suggestion
The privacy progress tile represents the percentage of how much privacy the wallet has.
```

2022-08-30 07:31 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The privacy progress indicates the percentage of the wallet balance in coins above the anonscore target.
Thanks, I would go with the first one.

2022-08-31 08:15 UTC, yahiheb requested changes

2022-08-31 08:15 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The privacy progress tile represents the percentage of how much private the wallet is.
```suggestion
The privacy progress tile represents the percentage of how private the wallet is.
```

2022-08-31 08:16 UTC, yahiheb approved these changes

2022-08-31 08:16 UTC, merged