FAQ UseWasabi: update What is dust threshold
zkSNACKs/WasabiDoc pull request #1142
Opened 2022-08-04 18:37 UTC by MarnixCroes

2022-08-05 02:33 UTC, yahiheb requested changes

2022-08-05 02:33 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Specifically in the context of Wasabi, with the dust threshold settings you can limit the value of coins shown in the GUI as coins *below* the dust threshold are not shown.
```suggestion
Specifically in the context of Wasabi, with the dust threshold settings you can limit the value of coins shown in the GUI.
Coins that you receive from other wallets which are *less than or equal to* the dust threshold in value are not shown.
```

2022-08-05 02:33 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +For example: When you set it to `0.0000 5000 BTC`, and when you receive a coin worth `0.0000 4000 BTC`, then this transaction and the coin in the coin list will not be shown.
```suggestion
For example: When you set it to `0.0000 5000 BTC`, and when you receive a coin worth `0.0000 4000 BTC`, then this transaction and the coin will not be shown in the coin list.
```

2022-08-05 06:13 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Specifically in the context of Wasabi, with the dust threshold settings you can limit the value of coins shown in the GUI as coins *below* the dust threshold are not shown.
it it got changed for 2.0, as for the 5000 cj outputs to be shown.
so *below* /less than is correct here

2022-08-06 02:03 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Specifically in the context of Wasabi, with the dust threshold settings you can limit the value of coins shown in the GUI as coins *below* the dust threshold are not shown.
If you receive a 5000 sats coin from another wallet it won't be shown.

What has changed/fixed now is that any coin you receive from your own wallet will be shown even if it is 1000 sats, and that is why the 5000 cj outputs are shown.

2022-08-06 18:14 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Specifically in the context of Wasabi, with the dust threshold settings you can limit the value of coins shown in the GUI as coins *below* the dust threshold are not shown.
ok I wasn't aware of that thanks

2022-08-06 18:15 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +For example: When you set it to `0.0000 5000 BTC`, and when you receive a coin worth `0.0000 4000 BTC`, then this transaction and the coin in the coin list will not be shown.
?

2022-08-07 15:19 UTC, yahiheb approved these changes

2022-08-07 15:19 UTC, merged