Update PayJoin to 2.0
zkSNACKs/WasabiDoc pull request #1147
Opened 2022-08-15 08:42 UTC by MarnixCroes

2022-08-15 22:13 UTC, yahiheb requested changes
I would replace the `PayJoinSend.png` image with the following one:

![asasa](https://user-images.githubusercontent.com/52379387/184727039-2abb81bb-0f81-428d-8863-6a7490b91896.PNG)

2022-08-15 22:13 UTC, yahiheb commented on docs/using-wasabi/PayJoin.md
> +![PayJoin indicator](/PayJoinIndicator.png "PayJoin indicator")
I would replace this image with one that you used for `PayJoinSend.png`

2022-08-18 22:18 UTC, MarnixCroes commented on docs/using-wasabi/PayJoin.md
> +![PayJoin indicator](/PayJoinIndicator.png "PayJoin indicator")
[a41c9c6](https://github.com/zkSNACKs/WasabiDoc/pull/1147/commits/a41c9c6279886dbfdafc65cd2c7c7ca0ca695128)

2022-08-18 22:44 UTC, MarnixCroes commented
@yahiheb I fixed your comments

2022-08-18 23:22 UTC, yahiheb requested changes
> I would replace the `PayJoinSend.png` image with the following one:
> 
> ![asasa](https://user-images.githubusercontent.com/52379387/184727039-2abb81bb-0f81-428d-8863-6a7490b91896.PNG)

How about using this picture, because it has the payjoin indicator?

2022-08-20 07:45 UTC, MaxHillebrand approved these changes

2022-08-20 13:38 UTC, yahiheb requested changes

2022-08-20 13:38 UTC, yahiheb commented on docs/using-wasabi/PayJoin.md
>  ![Send Bitcoin PayJoin transaction in Wasabi Wallet](/PayJoinSend.png "Send Bitcoin PayJoin transaction in Wasabi Wallet")
This should be below the 2nd or 3rd point IMO

2022-08-20 13:45 UTC, yahiheb requested changes

2022-08-20 13:45 UTC, yahiheb commented on docs/using-wasabi/PayJoin.md
> +![PayJoin indicator](/PayJoinIndicator.png "PayJoin indicator")
IMO we don't need this or its image.

2022-08-20 14:15 UTC, MarnixCroes commented on docs/using-wasabi/PayJoin.md
>  ![Send Bitcoin PayJoin transaction in Wasabi Wallet](/PayJoinSend.png "Send Bitcoin PayJoin transaction in Wasabi Wallet")
that was forgotten because of the renemaing
fixed in latest commit

2022-08-20 14:15 UTC, MarnixCroes commented on docs/using-wasabi/PayJoin.md
> +![PayJoin indicator](/PayJoinIndicator.png "PayJoin indicator")
fixed

2022-08-20 16:10 UTC, yahiheb approved these changes

2022-08-20 16:10 UTC, merged