[Docs-2.0] Update to UsingWasabi-Send-Observers section
zkSNACKs/WasabiDoc pull request #1170
Opened 2022-09-06 21:05 UTC by jesseaam

Updates to Observers section. Reworded some sentences and removed a statement that said labels were not required.

2022-09-06 22:03 UTC, yahiheb requested changes

2022-09-06 22:03 UTC, yahiheb commented on docs/using-wasabi/Send.md
> +Wasabi Wallet will provide suggestions to improve the privacy of your transaction on the Preview Transaction page.
I don't understand why all of this was added.

2022-09-06 23:38 UTC, jesseaam commented on docs/using-wasabi/Send.md
> +Wasabi Wallet will provide suggestions to improve the privacy of your transaction on the Preview Transaction page.
You're right - those lines are immaterial  to the Observers section.

2022-09-07 16:47 UTC, jesseaam commented on docs/using-wasabi/Send.md
> +Note that there is an option to manually select and send specific coins using [DeveloperFeatures](https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Documentation/DeveloperFeatures.md)
After our discussion today, it was decided that the sentence about manually selecting coins should not currently be included in this section.

2022-09-07 19:01 UTC, jesseaam commented on docs/using-wasabi/Send.md
> +A coin is an unspent transaction output (UTXO): a chunk of bitcoin that can be sent in a future transaction.
ACK

2022-09-07 23:47 UTC, yahiheb requested changes

2022-09-07 23:47 UTC, yahiheb commented on docs/using-wasabi/Send.md
> +When you want to send some bitcoin you simply enter the amount to send after clicking the `Send` button.
```suggestion
When you want to send some bitcoin you simply enter the amount to send and the address after clicking the `Send` button.
```

2022-09-07 23:47 UTC, merged