FAQUse: add Can I send privately below 100% privacy progress
zkSNACKs/WasabiDoc pull request #1187
Opened 2022-09-12 10:20 UTC by MarnixCroes

2022-09-13 00:49 UTC, yahiheb requested changes
You cannot actually send the private amount because you need to deduct the fees from it.

2022-09-13 00:49 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +So when your wallet is partially private (between 1 and 100% privacy progress) it is a best practice to only send the private available amount, to remain your privacy.
```suggestion
So when your wallet is partially private (between 0 and 100% privacy progress) it is a best practice to only send the private available amount, to protect your privacy.
```

2022-09-13 07:37 UTC, MarnixCroes commented
> You cannot actually send the private amount because you need to deduct the fees from it.

that's why we need https://github.com/zkSNACKs/WalletWasabi/issues/7590 :)

I'll edit

2022-09-13 07:51 UTC, MarnixCroes commented
> I'll edit

done. 
0.0001 BTC is maybe a bit high, but I think it's better to be safe than sorry

2022-09-25 20:08 UTC, yahiheb requested changes

2022-09-25 20:08 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +So that is the amount which can be send privately, even if the privacy progress is not yet 100%.
```suggestion
So that is the amount (minus the mining fees) which can be sent privately, even if the privacy progress is not yet 100%.
```

2022-09-25 20:08 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +When `PRIVATE` is 0.00787086 BTC, that means that I can send 0.00787086 BTC privately.
```suggestion
When `PRIVATE` is 0.00787086 BTC, that means that I can send less than that privately.
```

2022-09-25 20:08 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +So when sending, 0.00787086 - mining fees (±0.00010000 BTC, depending on tx size and fee rate) should be entered as the `Amount` in order to only use the private funds.
```suggestion
So when sending, less than 0.00787086 BTC (to cover the mining fees) should be entered as the `Amount` in order to only use the private funds.
```

2022-09-25 20:11 UTC, yahiheb commented
@MarnixCroes Do you mind opening a new PR to the master branch instead of the docs-2.0?
Feel free to edit anything if you don't agree with my last commit.

2022-09-26 23:48 UTC, yahiheb commented
Replaced by #1200

2022-09-26 23:48 UTC, closed without merging