Update NetworkLevelPrivacy.md
zkSNACKs/WasabiDoc pull request #1196
Opened 2022-09-23 12:24 UTC by MarnixCroes

2022-09-25 19:53 UTC, yahiheb requested changes

2022-09-25 19:53 UTC, yahiheb commented on docs/why-wasabi/NetworkLevelPrivacy.md
> +Wasabi has [partial Bitcoin Knots integration](/using-wasabi/BitcoinFullNode.md).
```suggestion
Wasabi has a [partial Bitcoin Knots integration](/using-wasabi/BitcoinFullNode.md).
```

2022-09-25 19:53 UTC, yahiheb approved these changes

2022-10-01 20:28 UTC, BTCparadigm reviewed
Here's my nitpicks

2022-10-01 20:28 UTC, BTCparadigm commented on docs/why-wasabi/NetworkLevelPrivacy.md
>  Without having to install or configure anything.
```suggestion
This means that it is possible (but not mandatory) to start Bitcoin Knots during the launch of Wasabi, without having to install or configure anything manually.
```

2022-10-01 20:28 UTC, BTCparadigm commented on docs/why-wasabi/NetworkLevelPrivacy.md
>  This means that it is possible (but not mandatory) to start Bitcoin Knots during the launch of Wasabi, without having to install or configure anything.
```suggestion
This means that it is possible (but not mandatory) to start Bitcoin Knots during the launch of Wasabi, without having to install or configure anything manually.
```

2022-10-02 01:44 UTC, yahiheb approved these changes

2022-10-02 01:45 UTC, merged