add BIP 341 Taproot
zkSNACKs/WasabiDoc pull request #1197
Opened 2022-09-23 12:32 UTC by MarnixCroes

2022-09-25 19:54 UTC, yahiheb commented
This is waiting for https://github.com/zkSNACKs/WalletWasabi/pull/9070 I guess.

2023-01-05 07:23 UTC, yahiheb commented
What's up with this one @MarnixCroes ?

2023-01-05 09:53 UTC, MarnixCroes commented
> What's up with this one @MarnixCroes ?

let's merge it afer Taproot is available for the user in the GUI

2023-03-06 08:44 UTC, MarnixCroes commented
let's merge this
> let's merge it afer Taproot is available for the user in the GUI

I've created this issue for this

2023-03-06 18:27 UTC, yahiheb requested changes

2023-03-06 18:27 UTC, yahiheb commented on docs/using-wasabi/BIPs.md
> +- [BIP 341: Taproot](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki)
```suggestion
- [BIP 341: Taproot: SegWit version 1 spending rules](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki)
```

2023-03-07 10:07 UTC, yahiheb approved these changes

2023-03-07 10:07 UTC, merged