denominations odd number fix
zkSNACKs/WasabiDoc pull request #1213
Opened 2022-09-28 06:53 UTC by MarnixCroes

quick fix,
could probably use some improvement in future

2022-09-28 06:53 UTC, MarnixCroes commented
> could probably use some improvement in future

or maybe you can fix it in follow up PR? @MaxHillebrand

2022-09-28 07:00 UTC, MaxHillebrand approved these changes

2022-09-28 07:01 UTC, MaxHillebrand commented
Maybe the question can be entirely removed now, in a follow up cleanup pr.

2022-10-01 19:38 UTC, BTCparadigm requested changes
ACK @MaxHillebrand's suggestion to remove it.

2022-10-02 01:51 UTC, closed without merging