FAQIntro: what is a sufficient anon score
zkSNACKs/WasabiDoc pull request #1218
Opened 2022-09-28 10:31 UTC by MarnixCroes

2022-09-28 10:34 UTC, MaxHillebrand commented on docs/FAQ/FAQ-Introduction.md
>  Furthermore our calculations have shown that with the liquidity of today’s mixers, our mixing rounds would take 1 to 5 minutes with 100 anonymity score.
```suggestion
```

that calculation only makes sense for 1.0 rounds.

2022-10-01 18:33 UTC, BTCparadigm commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus among many privacy researchers is that an anonymity score above 50 could be considered sufficient.
"However, the rough consensus among many privacy researchers is that an anonymity score above 50 could be considered sufficient."

This was for anonymity set. If we say above 50 is sufficient, everything below is insufficient. 
This makes 2 of our default profiles bad and should be considered in https://github.com/zkSNACKs/WalletWasabi/issues/8880

Ping @nopara73

2022-10-02 00:26 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus among many privacy researchers is that an anonymity score above 50 could be considered sufficient.
> On Anonymity
> It seems to me that if you reach anonymity score 5 in Wasabi, then that is practically sufficient against any adversary. However to be sure, for the privacy profile we do anonymity score random(50 to 100) as there's really not even a theoretical edge case is known that might be breaking that setting.

https://www.reddit.com/r/WasabiWallet/comments/xf3o33/comment/iq2qd24/?utm_source=share&utm_medium=web2x&context=3

2022-10-05 07:48 UTC, nopara73 commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus among many privacy researchers is that an anonymity score above 50 could be considered sufficient.
50 was a rough consensus in 2018 and only considered traditional coinjoins. For me, 2 is probably sufficient anonscore with WW2 and I suspect it is for 99% of our users. That being said, we went with 5 to be on the safe side.

2022-10-10 09:22 UTC, MarnixCroes reviewed
ok?

2022-10-10 09:22 UTC, MarnixCroes commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus among many privacy researchers is that an anonymity score above 50 could be considered sufficient.
```suggestion
However, the rough consensus is that with WabiSabi an anonymity score of 2 and above could be considered sufficient.
```

2022-11-01 11:18 UTC, yahiheb requested changes

2022-11-01 11:18 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus is that with WabiSabi an anonymity score of 2 and above could be considered sufficient.
I don't see this rough consensus that an anonymity score of 2 in WabiSabi is considered sufficient.
If it was enough then why do we have 5 by default?
```suggestion
However, with WabiSabi an anonymity score of 5 and above could be considered sufficient.
```

2022-11-07 00:03 UTC, yahiheb commented
In relation to this https://github.com/zkSNACKs/WasabiDoc/issues/1330

2022-11-10 09:19 UTC, nopara73 commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus is that with WabiSabi an anonymity score of 2 and above could be considered sufficient.
> If it was enough then why do we have 5 by default?

Because research hasn't been conducted and we want to be on the safe side.

2022-11-10 10:45 UTC, nopara73 commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus is that with WabiSabi an anonymity score of 2 and above could be considered sufficient.
I think there's a standard way to logically capture expert opinion. You might want to consider fuzzifying it. See how expert banker opinion on credit scoring can be fuzzified then defuzzified: https://www.youtube.com/watch?v=__0nZuG4sTw&ab_channel=MATLAB

Pinging @lontivero in case he has some wisdom to drop here.

2022-11-11 20:45 UTC, lontivero commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus is that with WabiSabi an anonymity score of 2 and above could be considered sufficient.
I'm not sure fuzzy logic is the way to go. Anyway, I have just coded the youtube's explanation just in case someone decides to implement it: https://gist.github.com/lontivero/1be4083fb85373893759a18e9cd5e246

2023-03-21 09:32 UTC, MarnixCroes commented
is this good to go?

2023-03-21 22:10 UTC, yahiheb requested changes

2023-03-21 22:10 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus is that with WabiSabi an anonymity score of 2 and above could be considered sufficient.
```suggestion
However, to be on the safe side, with Wasabi Wallet 2.0 an anonymity score of 5 and above could be considered sufficient.
```

2023-03-23 12:34 UTC, MarnixCroes commented on docs/FAQ/FAQ-Introduction.md
> +However, the rough consensus is that with WabiSabi an anonymity score of 2 and above could be considered sufficient.
imo current is better

2023-05-14 01:36 UTC, yahiheb requested changes

2023-05-14 01:36 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +### What is considered a sufficient anon score?
```suggestion
### What is considered a sufficient anonymity score?
```

2023-05-14 01:43 UTC, yahiheb approved these changes
https://github.com/zkSNACKs/WalletWasabi/issues/10517
https://github.com/zkSNACKs/WalletWasabi/issues/10567

From the above issues/discussions it is clear that an anonymity score 2 is not considered sufficient, and even anonymity score 5 might not be sufficient after all.

The current answer is completely outdated so I will merge this with anonscore 5 and we can improve this in the future.

2023-05-14 01:43 UTC, merged