Remove 10 commandments
zkSNACKs/WasabiDoc pull request #1219
Opened 2022-09-28 10:39 UTC by MaxHillebrand

it's clutter, good idea for a blogpost though.

2022-09-28 10:55 UTC, MarnixCroes requested changes
I'dd also delete it from config.js

2022-09-28 11:01 UTC, MarnixCroes approved these changes

2022-09-28 18:28 UTC, BTCparadigm commented
cACK

2022-10-05 22:03 UTC, yahiheb approved these changes

2022-10-05 22:03 UTC, merged