Delete whonix
zkSNACKs/WasabiDoc pull request #1221
Opened 2022-09-28 10:42 UTC by MaxHillebrand

2.0 no longer works on Whonix because we use the Tor control port.

2022-09-28 10:56 UTC, MarnixCroes requested changes
cACK
should also be deleted from config.js file

2022-09-28 10:59 UTC, MarnixCroes approved these changes

2022-09-28 11:01 UTC, MaxHillebrand commented
I changed FAQ for tails support, and added a non-support faq for whonix.

2022-09-28 11:04 UTC, MarnixCroes submitted a review, later dismissed

2022-09-28 18:28 UTC, BTCparadigm commented
cACK

2022-10-05 22:14 UTC, yahiheb requested changes

2022-10-05 22:14 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +No, it is not possible to install Wasabi on Tails.
```suggestion
No, it is not possible to install Wasabi on Tails, because Wasabi uses the Tor control port, which is not exposed in this operating system.
```

2022-10-05 22:14 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +No, it is not possible to install Wasabi on WHONIX.
```suggestion
### Can I install Wasabi on Whonix?

No, it is not possible to install Wasabi on Whonix, because Wasabi uses the Tor control port, which is not exposed in this operating system.
```

2022-10-05 22:14 UTC, yahiheb requested changes

2022-10-05 22:14 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
>  ### Can I install Wasabi on TAILS?
```suggestion
### Can I install Wasabi on Tails?
```

2022-10-05 22:16 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +### Can I install Wasabi on Tails?
I guess Wasabi can installed and therefore the question here should be `Can I use Wasabi on Tails`? WDYT?

2022-10-05 22:24 UTC, yahiheb requested changes

2022-10-05 22:24 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +### Can I install Wasabi on Tails?
I guess Wasabi can be installed and therefore the question here should be Can I use Wasabi on Tails? WDYT?

```suggestion
### Can I use Wasabi on Tails?
```

2022-10-05 22:24 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +### Can I install Wasabi on Whonix?
Same here.

```suggestion
### Can I use Wasabi on Whonix?
```

2022-10-06 15:58 UTC, merged