radical simplification of change coins
zkSNACKs/WasabiDoc pull request #1222
Opened 2022-09-28 10:55 UTC by MaxHillebrand

It could probably be simplified even more, but this is a good start.

2022-10-02 16:10 UTC, BTCparadigm reviewed
Not directly related to this PR  but I'm confused about the inconsistent usage of a dot at the end of the headers in this document. 
Fixes in suggestions.

2022-10-02 16:10 UTC, BTCparadigm commented on docs/using-wasabi/ChangeCoins.md
>  ### Avoid change in the first place.
```suggestion
### Avoid change in the first place
```

2022-10-02 16:10 UTC, BTCparadigm commented on docs/using-wasabi/ChangeCoins.md
>  ### Make it difficult to deduce the change.
```suggestion
### Make it difficult to deduce the change
```

2022-10-02 16:10 UTC, BTCparadigm commented on docs/using-wasabi/ChangeCoins.md
>  ### Spend the change with another entity, where you don't mind if each of the two knows that you transact with the other entity.
```suggestion
### Spend the change with another entity, where you don't mind if each of the two knows that you transact with the other entity
```

2022-10-02 16:10 UTC, BTCparadigm commented on docs/using-wasabi/ChangeCoins.md
> +### Coinjoin more.
```suggestion
### Coinjoin more
```

2022-10-02 16:10 UTC, BTCparadigm commented on docs/using-wasabi/ChangeCoins.md
>  ### Avoid change in the first place.
```suggestion
### Avoid change in the first place
```

2022-10-07 07:20 UTC, yahiheb requested changes

2022-10-07 07:20 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +In some few cases, especially for the wealthiest user of a coinjoin, there will be a `anonymity score 1` output in a coinjoin transaction.
```suggestion
In some few cases, especially for the wealthiest user of a coinjoin, there will be an `anonymity score 1` output in a coinjoin transaction.
```

2022-10-07 07:20 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +Wasabi will automatically check if you have a coin with the same label for the current payment recipient, and will suggest those coins to be spend.
```suggestion
Wasabi will automatically check if you have a coin with the same label for the current payment recipient, and will suggest those coins to be spent.
```

2022-10-07 07:20 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +### Spend the change with another entity, where you don't mind if each of the two knows that you transact with the other entity
```suggestion
### Spend the change with another entity, where you don't mind if each of the two know that you transact with the other entity
```

2022-10-07 07:24 UTC, yahiheb requested changes
Note that this document still needs to be updated.

2022-10-07 07:24 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +Since Wasabi 2.0 has no minimum amount for coinjoin, any change coin will be automatically registered for the next coinjoin round. If you wait long enough, Wasabi will make sure that you don't have a
There is a minimum amount for coinjoin. https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#what-is-the-minimum-amount-required-to-coinjoin

IMO we should remove this section.

2022-10-07 07:24 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
>  In the `Send` tab you select one or more UTXO, these are the inputs of the transaction.
This assumes that we use coin control which not the case by default.

2022-10-07 07:40 UTC, MaxHillebrand commented on docs/using-wasabi/ChangeCoins.md
> +Since Wasabi 2.0 has no minimum amount for coinjoin, any change coin will be automatically registered for the next coinjoin round. If you wait long enough, Wasabi will make sure that you don't have a
```suggestion
Since Wasabi 2.0 has a minimum amount for coinjoin of only 5000 sats, any change coin will be automatically registered for the next coinjoin round. If you wait long enough, Wasabi will make sure that you don't have any anonscore 1 change coins in your wallet, but only private coins not related to any previous payment.
```

2022-10-07 07:41 UTC, MaxHillebrand commented on docs/using-wasabi/ChangeCoins.md
>  In the `Send` tab you select one or more UTXO, these are the inputs of the transaction.
if you're sending non-private [change] coins, then it will show pocket selection at least.

2022-10-07 07:58 UTC, yahiheb requested changes

2022-10-07 07:58 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +Since Wasabi 2.0 has a minimum amount for coinjoin of only 5000 sats, any change coin will be automatically registered for the next coinjoin round. If you wait long enough, Wasabi will make sure that
I think there is no guarantee that change coins will be registered automatically in the next CJ round, right?

```suggestion
Since Wasabi 2.0 has a minimum amount for coinjoin of only 5000 sats, any change coin with an amount larger than that will be registered in a future coinjoin round.
If you wait long enough, Wasabi will make sure that you don't have any anonscore 1 change coin in your wallet, but only private coins not linked to any previous payment.
```

2022-10-07 07:58 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
>  In the `Send` tab you select one or more UTXO, these are the inputs of the transaction.
```suggestion
In the `Send` dialog you select one or more UTXO, these are the inputs of the transaction.
```

2022-10-07 07:59 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
>  In the `Send` tab you select one or more UTXO, these are the inputs of the transaction.
Not true always (when you send to the same entity) and you do not select UTXOs.

2022-11-25 11:03 UTC, MarnixCroes reviewed
I think this can be merged (after comments are addressed)
furter improvement can be made in follow up PR's

2022-11-25 11:38 UTC, MarnixCroes approved these changes
I agree with this https://github.com/zkSNACKs/WasabiDoc/pull/1222#discussion_r989768407, it can be confusing.
other than that, LGTM

2022-11-25 11:50 UTC, MaxHillebrand commented on docs/using-wasabi/ChangeCoins.md
> +For example, let's assume that you choose an `anonymity score 1` UTXO worth 2 bitcoins.
```suggestion
```

2022-11-25 11:51 UTC, MaxHillebrand reviewed
I'd just merge it, and fix it further in another PR.

2022-11-27 15:14 UTC, yahiheb requested changes

2022-11-27 15:14 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +Wasabi will automatically check if you have a coin with the same label for the current payment recipient, and will suggest those coins to be spent.
```suggestion
Wasabi will automatically check if you have a coin with the same label for the current payment recipient, and will use those coins to be spent.
```

2022-11-27 15:14 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
>  But if you have a trusted relationship with the two, then this is alright, and not part of your thread model.
```suggestion
But if you have a trusted relationship with the two, then this is alright, and not part of your threat model.
```

2022-11-27 15:15 UTC, yahiheb approved these changes

2022-11-27 15:17 UTC, yahiheb approved these changes

2022-11-27 15:17 UTC, merged