clarify for Tails
zkSNACKs/WasabiDoc pull request #1223
Opened 2022-09-28 11:10 UTC by MarnixCroes

to clarify that this is for general, not Wasabi specific
to prevent possible confusion
related to https://github.com/zkSNACKs/WasabiDoc/pull/1221

2022-09-28 11:14 UTC, MaxHillebrand submitted a review, later dismissed

2022-10-01 18:24 UTC, BTCparadigm commented
Does 2.0 work on Tails?
I thought there is a problem with Tor over Tor.

2022-10-07 00:52 UTC, yahiheb requested changes

2022-10-07 00:52 UTC, yahiheb commented on docs/FAQ/FAQ-GeneralBitcoinPrivacy.md
> +To maintain your anonymity, use the Tor Browser or the TAILS operating system, if possible.
```suggestion
To maintain your anonymity, use the Tor Browser or the Tails operating system, if possible.
```

2022-10-07 00:53 UTC, yahiheb approved these changes

2022-10-07 00:53 UTC, merged