Send: remove custom change address
zkSNACKs/WasabiDoc pull request #1229
Opened 2022-09-29 08:45 UTC by MarnixCroes

remove (for now)
https://github.com/zkSNACKs/WalletWasabi/pull/7108

2022-09-30 00:30 UTC, yahiheb requested changes
I guess if we remove it then we should also remove https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/FAQ/FAQ-UseWasabi.md#how-can-i-set-a-custom-change-address and `SettingsCustomChange.png`

But we should add these back once it gets implemented.

2022-09-30 08:05 UTC, MarnixCroes commented
> I guess if we remove it then we should also remove https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/FAQ/FAQ-UseWasabi.md#how-can-i-set-a-custom-change-address and `SettingsCustomChange.png`
> 
> But we should add these back once it gets implemented.

already a PR, https://github.com/zkSNACKs/WasabiDoc/pull/1230

2022-10-02 02:05 UTC, yahiheb approved these changes

2022-10-02 02:05 UTC, merged

2022-10-02 02:06 UTC, yahiheb commented
@MarnixCroes When the custom change address is implemented again we should add back this.