Vuepress 2.x version
zkSNACKs/WasabiDoc pull request #1247
Opened 2022-10-03 07:34 UTC by CAnorbo

Updated Vuepress 2.x version.
Fixed #1239  #1238  #1211 

@yahiheb @MarnixCroes @molnard

2022-10-03 07:38 UTC, yahiheb requested changes
Your branch is not up to date with master.

2022-10-03 07:53 UTC, CAnorbo commented
> Your branch is not up to date with master.

Updated could you check the changes?

2022-10-03 08:10 UTC, yahiheb requested changes
`Logo_with_text.png` is not used anywhere.

Did you mean to make all the changes in `package-lock.json` and in `package.json`?

I do not understand what this PR does, nor how to review it, and from the changes in `variables.js` I believe the branch is still not up-to-date.

I guess it is better to fork the repository again, and then checkout a new branch and make your changes, then make a new PR.

2022-10-03 08:10 UTC, yahiheb commented on docs/.vuepress/enhanceApp.js
> +    { path: '/building-wasabi/Dojo.html', redirect: '/' },
The Dojo file was removed long ago.

2022-10-03 08:10 UTC, yahiheb commented on docs/.vuepress/variables.js
> +  dotnetVersion: '5.0',
This is not up to date.

2022-10-03 08:10 UTC, yahiheb commented on package.json
> +  "license": "ISC",
What is this?

2022-10-03 08:33 UTC, molnard commented
Concept ACK, CI is failing, can you fix it?

2022-10-03 09:19 UTC, CAnorbo commented
> Concept ACK, CI is failing, can you fix it?

Fixed CL

2022-10-03 12:32 UTC, BTCparadigm commented
![images (17)](https://user-images.githubusercontent.com/51679301/193577176-8bee8cc7-3383-43f2-bdd1-641f70df5008.jpg)

2022-10-10 09:08 UTC, molnard commented
I suggest to prioritize this PR before anything else in the repo, otherwise, you will get conflicts again and again.

2022-10-16 22:55 UTC, yahiheb requested changes
@CAnorbo  What is the purpose of this PR? Why do we need to upgrade to Vuepress 2?

I get this error when executing `npm start`:

> TypeError: Cannot destructure property 'themeConfig' of 'ctx' as it is undefined.
>     at module.exports (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\theme-default\index.js:7:11)
>     at file:///C:/Users/chihe/OneDrive/Bureau/WasabiDoc/docs/.vuepress/config.bundled_1665960827483.mjs:19:10
>     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
>     at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
>     at async extractResult (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\bundle-require\dist\index.js:263:13)
>     at async loadConfig (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\core\lib\node\loadConfig.js:30:21)
>     at async App.resolveConfigAndInitialize (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\core\lib\node\App.js:64:24)
>     at async App.process (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\core\lib\node\App.js:103:5)
>     at async dev (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\core\lib\index.js:17:3)

2022-10-25 07:01 UTC, CAnorbo commented
> @CAnorbo What is the purpose of this PR? Why do we need to upgrade to Vuepress 2?
> 
> I get this error when executing `npm start`:
> 
> > TypeError: Cannot destructure property 'themeConfig' of 'ctx' as it is undefined.
> > at module.exports (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules@vuepress\theme-default\index.js:7:11)
> > at file:///C:/Users/chihe/OneDrive/Bureau/WasabiDoc/docs/.vuepress/config.bundled_1665960827483.mjs:19:10
> > at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
> > at async Promise.all (index 0)
> > at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
> > at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
> > at async extractResult (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\bundle-require\dist\index.js:263:13)
> > at async loadConfig (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules@vuepress\core\lib\node\loadConfig.js:30:21)
> > at async App.resolveConfigAndInitialize (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules@vuepress\core\lib\node\App.js:64:24)
> > at async App.process (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules@vuepress\core\lib\node\App.js:103:5)
> > at async dev (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules@vuepress\core\lib\index.js:17:3)

It's fixing 3 issues that I couldn't do on the 1.x version.
Check your node version and make sure it's higher than 16.

2022-10-30 22:27 UTC, yahiheb commented
> Check your node version and make sure it's higher than 16.

I updated Node.js to the version 18.12.0 and I still get the same error and I can't run this locally.

2022-11-02 09:07 UTC, CAnorbo commented
> > Check your node version and make sure it's higher than 16.
> 
> I updated Node.js to the version 18.12.0 and I still get the same error and I can't run this locally.

This should work:
npm install
npm update
npm run start

2022-11-19 20:37 UTC, yahiheb commented
> This should work:
> npm install
> npm update
> npm run start

Yes it worked.

2022-11-19 20:51 UTC, yahiheb requested changes
@CAnorbo Sorry for letting this PR trail for long, it is much better than what I have initially thought, very good job.

Can you fix the conflicts?

2022-11-19 21:01 UTC, yahiheb commented
I have noticed that you remove `:::details` so the FAQs are not longer expandable. Why is that?

2022-11-20 12:17 UTC, yahiheb commented
@CAnorbo I deleted `.idea` folder to leave it out of source control.

2022-11-20 15:41 UTC, yahiheb commented
This PR also fixes #1342 and #1339 because expandable items were removed https://github.com/zkSNACKs/WasabiDoc/pull/1247#issuecomment-1320968300

2022-11-20 21:37 UTC, yahiheb requested changes
**Must be fixed:**

- Variables like current version and zkSNACKs pubkey are not displayed correctly:

  ![doc1](https://user-images.githubusercontent.com/52379387/202927163-daa46991-a5d3-47c9-a99b-2e34f088c593.PNG)

**Nice to have:**

- Read the embedded videos on the docs and don't redirect to youtube.
- Expand/collapse FAQs items. https://github.com/zkSNACKs/WasabiDoc/pull/1247#issuecomment-1320968300
- Change the ugly looking default image of the embedded videos:

  ![doc0](https://user-images.githubusercontent.com/52379387/202927310-574a3dfc-5607-4717-93f8-d88b3fa73b3a.PNG)

2022-11-21 15:32 UTC, jesseaam commented
On the index page, when I change from dark to light, some of the text is no longer visible.

<details>
<summary>Expand screenshots</summary>

## Dark mode view
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/18119820/203093630-fccd5b7b-8466-42c8-8b08-1afb4a86db53.png">

<br><br>
`open-source` `non-custodial` and `privacy-focused`  you can't see now in light-mode.
## Light mode view
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/18119820/203093819-0d532b03-52bf-4513-9954-0c9008b47b61.png">
</details>

2022-11-21 16:04 UTC, jesseaam commented
"Edit this page" link is broken.

<img width="1904" alt="Screen Shot 2022-11-21 at 10 47 06 AM" src="https://user-images.githubusercontent.com/18119820/203101816-0b1d15b0-a378-41c4-affd-fcb335f18116.png">

### leads me to here
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/18119820/203102106-4298d246-dac8-44df-9046-8e43afe284e1.png">

2022-11-21 16:06 UTC, jesseaam commented
Also, can we remove the Contributors section?

2022-11-21 16:16 UTC, CAnorbo commented
> **Must be fixed:**
> 
> * Variables like current version and zkSNACKs pubkey are not displayed correctly:
>   ![doc1](https://user-images.githubusercontent.com/52379387/202927163-daa46991-a5d3-47c9-a99b-2e34f088c593.PNG) **=> Tried to resolve it but no solution yet.**
> 
> **Nice to have:**
> 
> * Read the embedded videos on the docs and don't redirect to youtube. **=> This won't work. Spent a lot of hours on this topic before.**
> * Expand/collapse FAQs items. [#1247 (comment)](https://github.com/zkSNACKs/WasabiDoc/pull/1247#issuecomment-1320968300) **=> They were removed by me because of the better readability.**
> * Change the ugly looking default image of the embedded videos:
>   ![doc0](https://user-images.githubusercontent.com/52379387/202927310-574a3dfc-5607-4717-93f8-d88b3fa73b3a.PNG) **=> This problem comes from youtube, we have to set a good image on youtube for this video. It's not a code problem.**

2022-11-21 16:17 UTC, CAnorbo commented
> > > On the index page, when I change from dark to light, some of the text is no longer visible.
> > > Expand screenshots
> > 
> > 
> > fixed.
> 
> @CAnorbo It is not fixed for me.

This should fix => https://github.com/zkSNACKs/WasabiDoc/pull/1247/commits/a50a690ee0fae729197d6241c91397c03e1470e8

2022-11-21 16:38 UTC, yahiheb commented
> This should fix => [a50a690](https://github.com/zkSNACKs/WasabiDoc/commit/a50a690ee0fae729197d6241c91397c03e1470e8)

That is what I have tested, and it is not fixed.

2022-11-21 17:35 UTC, jesseaam approved these changes
Tested ACK

2022-11-22 00:15 UTC, yahiheb requested changes
I still have the same issue as @jesseaam here https://github.com/zkSNACKs/WasabiDoc/pull/1247#issuecomment-1322241717
I cannot see some text in the light mode:

![sCapture](https://user-images.githubusercontent.com/52379387/203183792-e8d36094-39c0-49f0-aca4-49ac005ab721.PNG)

2022-11-22 12:39 UTC, yahiheb commented
> I still have the same issue as @jesseaam here https://github.com/zkSNACKs/WasabiDoc/pull/1247#issuecomment-1322241717
I cannot see some text in the light mode:

This is fixed.

2022-12-06 17:46 UTC, jesseaam commented
The videos now open up a new tab in YouTube. They used to be embedded and play within the docs. Is this the new desired behavior?

2022-12-06 20:48 UTC, jesseaam commented
Otherwise, everything else looks good on my end. Nice job everybody!

2022-12-07 04:40 UTC, yahiheb commented
> I can have a look but I think it may make sense to ask in [Discussions](https://github.com/vuepress/vuepress-next/discussions) first to save some time. If we don't have a response in a few days, we can try ourselves.

@CAnorbo Do you mind asking about that as @kiminuo suggested?

2022-12-08 07:39 UTC, CAnorbo commented
> > I can have a look but I think it may make sense to ask in [Discussions](https://github.com/vuepress/vuepress-next/discussions) first to save some time. If we don't have a response in a few days, we can try ourselves.
> 
> @CAnorbo Do you mind asking about that as @kiminuo suggested?

@yahiheb could you try this plugin? https://vuepress-theme-hope.github.io/v2/components/ on the Discussion the community recommended this one, but I can't run it for some reason.

2022-12-08 15:19 UTC, yahiheb requested changes

2022-12-08 15:19 UTC, yahiheb commented on README.md
> +
```suggestion
```

2022-12-08 20:22 UTC, yahiheb commented
> > > I can have a look but I think it may make sense to ask in [Discussions](https://github.com/vuepress/vuepress-next/discussions) first to save some time. If we don't have a response in a few days, we can try ourselves.
> > 
> > 
> > @CAnorbo Do you mind asking about that as @kiminuo suggested?
> 
> @yahiheb could you try this plugin? https://vuepress-theme-hope.github.io/v2/components/ on the Discussion the community recommended this one, but I can't run it for some reason.

That is not a blocker, we can fix that in a follow up PR.

2022-12-08 20:22 UTC, yahiheb approved these changes
tACK. Good job guys

2022-12-08 20:23 UTC, merged