Refactor coinjoin.md
zkSNACKs/WasabiDoc pull request #1266
Opened 2022-10-07 07:35 UTC by MaxHillebrand

A refactor of the coinjoin explanation for 2.0

Takes from #1051 and adds a bunch of additional stuff

2022-10-07 08:12 UTC, MarnixCroes submitted a review, later dismissed
nice

2022-10-07 08:12 UTC, MarnixCroes commented on docs/using-wasabi/CoinJoin.md
> +Autocoinjoin starts whenever there's more than 0.01 BTC non private in your wallet.
```suggestion
Coinjoin starts automatically whenever the amount of non-private funds is above the `Auto-start coinjoin threshold` (0.01 BTC by default).
```

2022-10-07 08:12 UTC, MarnixCroes commented on docs/using-wasabi/CoinJoin.md
> +Once a coin achieves enough privacy, the corresponding amount will show up in the software's main view as "private coins".
```suggestion
Once a coin achieves enough privacy, the corresponding amount will show up in the software's main view as "PRIVATE".
```

2022-10-07 08:12 UTC, MarnixCroes commented on docs/using-wasabi/CoinJoin.md
> +Only when all these checks are valid does the coordinator allow the input.
```suggestion
Only when all these checks are valid, does the coordinator allow this input to be registered.
```

2022-10-07 08:12 UTC, MarnixCroes commented on docs/using-wasabi/CoinJoin.md
> +The coordinator verifies the unique ID from all the Alices, and when everyone is still communicating.
```suggestion
The coordinator verifies the unique ID from all the Alices, and if everyone is still communicating.
```

2022-10-07 21:59 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +Only when all these checks are valid does the coordinator allow the input.
Agreed with Marnix's additional clarification but I want to bring up another nitpick.
The checks are valid. Its about if the input passes the checks so I'd say:

```suggestion
Only when all these checks are passed does the coordinator allow the input to be registered.
```

2022-10-07 23:04 UTC, BTCparadigm requested changes
![FMLzCF-WYAEh_y-](https://user-images.githubusercontent.com/51679301/194673570-2bc438c4-df2d-4cf6-bf6d-638e415ecd8c.png)

2022-10-07 23:04 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +Wasabi saves on mining fees by setting a confirmation target of roughly 24 hours.
Is it the clients who decides it? If not, how about:
```suggestion
To save on mining fees, the target confirmation time is roughly 24 hours.
```

2022-10-07 23:04 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
>  ## Wasabi CoinJoin examples
```suggestion
## Wasabi coinjoin examples
```

2022-10-08 01:43 UTC, yahiheb requested changes

2022-10-08 10:01 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +By default, Wasabi starts automatically coinjoining the funds, or you can toggle to manual coinjoin start in the settings.
IMHO this is not improvement. Please check my suggestion below.

2022-10-08 20:12 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +If you want to coinjoin right now, then click the play button; if you want to stop coinjoin, then click the pause button.
@BTCparadigm  In Max's sentence he talks about toggling (disabling) the `Automatically start coinjoin` and not the limit.
I would edit your first sentence as follow:

```
By default, Wasabi starts automatically coinjoining received funds when the total value of the non-private coins is equal to or above the `Auto-start coinjoin threshold` (0.01 BTC by default).
`Automatically start coinjoin` can be disabled from the coinjoin settings.
```

2022-10-09 21:25 UTC, yahiheb requested changes

2022-10-09 21:25 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
As pointed out here https://github.com/zkSNACKs/WasabiDoc/pull/1266#discussion_r990529452

```suggestion
```

2022-10-09 21:27 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
Removed.

2022-10-09 22:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +After potentially many rounds of reissuance, each client has exactly the amount credential he desires.
```suggestion
After potentially many rounds of reissuance, each client has exactly the amount credential it desires.
```

2022-10-09 22:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +Because the coordinator can verify his own credential, he knows that this credential came into existence after an input of at least this much value was registerd.
```suggestion
Because the coordinator can verify its own credential, it knows that this credential came into existence after an input of at least this much value was registered.
```

2022-10-09 22:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +However, he cannot know which input exactly.
```suggestion
However, it cannot know which input exactly.
```

2022-10-09 22:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +Next, your Wasabi client generates a completely new Tor identity **Bob**, who is in no way tied to Alice.
I am lost here, what is this new Tor identity **Bob** needed for?

I guess we should say:

```suggestion
Next, your Wasabi client generates a completely new Tor identity **Bob** corresponding to each Alice, but who is in no way tied to any Alice.
```

2022-10-09 22:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +First, every client needs to change the value of their credential, to the desired output value.
Are we talking about every Alice here or every client?

2022-10-09 22:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +Because Alice received a credential from the coordinator, and because Bob is a new Tor identity not linked to Alice, the coordinator can verify that nobody is cheating, but he cannot deanonymize the
```suggestion
Because Alice received a credential from the coordinator, and because Bob is a new Tor identity not linked to Alice, the coordinator can verify that nobody is cheating, but it cannot deanonymize the peers.
```

2022-10-09 22:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +If after a timeout not all outputs are registered, then this round is abandoned, the missing peers are temporarily banned, and a new round is started.
Should we say `the missing inputs are temporarily banned` or not?

2022-10-09 22:15 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +Wasabi saves on mining fees by setting a confirmation target of roughly 24 hours.
AFAIK it is not the client that decides.

2022-10-10 05:21 UTC, yahiheb requested changes

2022-10-10 05:21 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The coordinator verifies the unique ID from all the Alices, and if everyone is still communicating.
```suggestion
The coordinator verifies the unique ID from each Alice, and if everyone is still communicating.
```

2022-10-10 06:51 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +* The input has not been registered before, is not banned, is unspent, and that the input proof is valid.
Registered already in the same round.

2022-10-10 06:56 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +Next, your Wasabi client generates a completely new Tor identity **Bob**, who is in no way tied to Alice.
Output registration must not be tied to input registration

2022-10-10 08:48 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +* The input has more than 5000 sats value.
What would you break it in to?

2022-10-11 07:06 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The round starts either as soon as enough inputs have been registered, or after the input registration time is reached and as long as the minimum number of inputs is satisfied.
`as soon as enough inputs have been registered` do you mean `as soon as the number of registered inputs reaches the maximum`?

2022-10-21 21:27 UTC, yahiheb requested changes

2022-10-21 21:27 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The round starts either as soon as enough inputs have been registered, or after the input registration time is reached and as long as the minimum number of inputs is satisfied.
```suggestion
The round starts either as soon as the number of registered inputs reaches the maximum, or after the input registration time is reached and as long as the minimum number of inputs is satisfied.
```

2022-10-27 08:45 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +In the background Wasabi generates input proofs, a signatures over a challenge message with the private key that locks up the coins.
```suggestion
In the background Wasabi generates input proofs, which is a signature over a challenge message with the private key that locks up the coin.
```

2022-10-27 08:54 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +* The input has more than 5000 sats value.
```suggestion
* The input has at least 5000 sats value.
```

2022-10-27 08:54 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +First, every client needs to change the value of their credential, to the desired output value.
Clients.

2022-10-27 08:54 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +First, every client needs to change the value of their credential, to the desired output value.
```suggestion
First, every client needs to change the value of their credentials to the desired output values.
```

2022-10-27 08:54 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +If after a timeout not all outputs are registered, then this round is abandoned, the missing peers are temporarily banned, and a new round is started.
```suggestion
If after a timeout not all outputs are registered, then this round is abandoned, the missing inputs are temporarily banned, and a new round is started.
```

2022-10-27 08:56 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +If after a timeout not all outputs are registered, then this round is abandoned, the missing peers are temporarily banned, and a new round is started.
```suggestion
If after a timeout not all outputs are registered, then this round is abandoned, the missing inputs are temporarily banned, and a new round is started.
```

2022-10-30 15:56 UTC, yahiheb requested changes

2022-10-30 15:56 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +* The input has not been registered before, is not banned, is unspent, and that the input proof is valid.
```suggestion
* The input has not already been registered, is not banned, is unspent, and that the input proof is valid.
```

2022-10-30 15:56 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The output registration phase ends when the value of cleartext outputs is equal to the value of inputs, meaning that all Bobs have registered.
I personally don't understand what does `cleartext outputs` mean.

2022-10-30 15:56 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +With Alice, you send the input and input ownership proof to the coordinator.
What about this one?

2022-10-30 16:09 UTC, yahiheb requested changes

2022-10-30 16:09 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +Next, your Wasabi client generates a completely new Tor identity **Bob**, who is in no way tied to Alice.
```suggestion
Next, for each Alice your Wasabi client generates a completely new Tor identity **Bob**, but who is in no way tied to any Alice.
```

2022-10-30 16:09 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +It sends this transaction to all the Alices of the round.
This is confusing, talking about the client signing the transaction and then Alice sending the signature.
This is how it should be AFAICU:

```
It sends this transaction to all the Alices of the round.
Each Alice does the following:
* Verifies that her input and output are included.
* Signs the transaction with the private key of her input.
* Sends the signature to the coordinator, who verifies this information.
```

2022-10-30 16:18 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +The output registration phase ends when the value of cleartext outputs is equal to the value of inputs, meaning that all Bobs have registered.
The output address, not "blinded"

2022-10-30 21:36 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +Next, your Wasabi client generates a completely new Tor identity **Bob**, who is in no way tied to Alice.
```suggestion
Next, your Wasabi client generates a completely new Tor identity **Bob**, who is in no way tied to any Alice.
```

2022-10-30 21:45 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +With Alice, you send the input and input ownership proof to the coordinator.
![images (14)](https://user-images.githubusercontent.com/51679301/198902967-a9557107-0b18-4777-ab50-dea2af198f1d.jpg)

2022-10-30 22:11 UTC, BTCparadigm commented
Either me and Yahia are monsters...
![image (16)](https://user-images.githubusercontent.com/51679301/198903891-3d56a962-2cd8-4ae4-ae9b-276a25e4493e.png)

Or...
![PR_meme](https://user-images.githubusercontent.com/51679301/198903944-a8d76558-dec6-4201-b873-ad57352e45b6.jpg)

2022-11-02 01:24 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +It sends this transaction to all the Alices of the round.
Fixed

2022-11-02 01:35 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +Next, your Wasabi client generates a completely new Tor identity **Bob**, who is in no way tied to any Alice.
```suggestion
Next, your Wasabi client generates multiple new Tor identities called **Bob**, which are in no way tied to any Alice.
```

2022-11-02 02:14 UTC, BTCparadigm commented on docs/using-wasabi/CoinJoin.md
> +In the background Wasabi generates input proofs, which is a signature over a challenge message with the private key that locks up the coin.
The original sentence sounded weird but I'm not sure if this is any better.
```suggestion
In the background Wasabi generates input proofs, which are signatures over challenge messages, made with the private keys that locks up the coins.
```

2022-11-02 02:47 UTC, yahiheb approved these changes

2022-11-02 02:55 UTC, merged