Update FAQ-UseWasabi.md
zkSNACKs/WasabiDoc pull request #1273
Opened 2022-10-08 13:51 UTC by BTCparadigm

Trying to salvage work already done from #1094

![i-am-once-again-asking-for-your-pull-request-approval-15667-1](https://user-images.githubusercontent.com/51679301/194710866-232215f2-8e54-4ea6-80ff-521980f73cc7.jpg)

2022-10-08 14:05 UTC, MarnixCroes requested changes

2022-10-08 14:05 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +![Name a new wallet in Wasabi](/AddWalletName.png "Name a new wallet in Wasabi")
```suggestion
![Name a new wallet in Wasabi](/AddWalletWalletName.png "Name a new wallet in Wasabi")
```

2022-10-08 14:05 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +![Add a password in Wasabi](/AddWalletPassword.png "Add a password in Wasabi")
```suggestion
![Add a password in Wasabi](/AddWalletAddPassword.png "Add a password in Wasabi")
```

2022-10-08 14:06 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +![Add a password in Wasabi](/AddWalletPassword.png "Add a password in Wasabi")
`AddWalletPassword.png` doesn't exit

2022-10-08 14:35 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +![Add a password in Wasabi](/AddWalletPassword.png "Add a password in Wasabi")
![4gdcznnjxyk71](https://user-images.githubusercontent.com/51679301/194712785-ee559755-8ec1-43d2-8af1-aadd8c76ca96.jpg)

Good job!

2022-10-08 18:22 UTC, yahiheb requested changes

2022-10-08 18:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
>  As with everything in Wasabi, you are required to label this new wallet.
There is a step missing before this one, and is to chose/click `Create a new wallet`

2022-10-08 18:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Add a password.
This step is after confirming the recovery words now.

2022-10-08 18:24 UTC, yahiheb commented
One more thing, to keep the repository clean, one should fork and create branches on their own fork, then open a PR.

2022-10-08 21:05 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +
```suggestion

Click `Create a new wallet`.

![Create a new wallet in Wasabi](/AddWallet.png "Create a new wallet in Wasabi")

```

2022-10-23 14:41 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +Add a password.
https://github.com/zkSNACKs/WasabiDoc/pull/1273/commits/d0ed14c8d8f73733f9966d73bc8029c0720e5eb0

2022-10-23 23:02 UTC, yahiheb requested changes

2022-10-23 23:02 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +:::
```suggestion
```

2022-10-23 23:02 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +![Add a password in Wasabi](/AddWalletAddPassword.png "Add a password in Wasabi")
```suggestion
![Add a password in Wasabi](/AddWalletAddPassword.png "Add a password in Wasabi")

:::danger Careful!!
Without knowledge of the password, you CANNOT spend your bitcoin!!
:::
```

2022-10-23 23:17 UTC, yahiheb requested changes

2022-10-23 23:17 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +In this page you can do a quick check that you've written down your mnemonic seed in the correct order.
```suggestion
In this page you should do a quick check that you've written down your mnemonic seed in the correct order. 
```

2022-10-23 23:17 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +It is used to encrypt the private key (extracted from the extended private key) on the computer and needed to open the wallet.
```suggestion
It is used to encrypt the private key (extracted from the extended private key) on the computer and needed to open the wallet and to recovered it in the future.
```

2022-10-23 23:17 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Make sure, and triple-check that you have done a proper backup of BOTH the password AND the mnemonic.
```suggestion

Make sure, and triple-check that you have done a proper backup of BOTH the password AND the mnemonic.
```

2022-10-23 23:17 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +In order to protect your backup, consider storing the password and recovery words in two different locations.
```suggestion
In order to protect your backup, consider storing the password and recovery words in different locations.
```

2022-10-23 23:17 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Now you get to choose your wallets coinjoin strategy.
```suggestion
Now you get to choose your wallets coinjoin strategy.
Select one and click `Continue`.
```

2022-10-23 23:19 UTC, yahiheb approved these changes

2022-10-23 23:20 UTC, merged