Update FAQ-UseWasabi.md
zkSNACKs/WasabiDoc pull request #1275
Opened 2022-10-08 15:45 UTC by BTCparadigm

Trying to salvage something from #1098

![yall-got-any-more-of-those-pull-request-approvals](https://user-images.githubusercontent.com/51679301/194715877-276b7efd-5412-4fb0-a094-c02093b2b341.jpg)

2022-10-08 18:11 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +### Where can I find my address QR code and the corresponding QR code?
What is the difference?

2022-10-08 18:11 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> -For example, due to the malleability fix of SegWit, you can now remix CoinJoin outputs which are currently unconfirmed.
Why was this example removed?

2022-10-08 21:16 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +### Where can I find my address QR code and the corresponding QR code?
Good question. I prolly got confused while looking at 3 versions of the same file.

2022-10-08 21:22 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> -For example, due to the malleability fix of SegWit, you can now remix CoinJoin outputs which are currently unconfirmed.
Because I can't remix coinjoin outputs which are currently unconfirmed. At least not indefinitely.
![image](https://user-images.githubusercontent.com/51679301/194728194-8d836682-e7a3-44fe-b213-5165954efbe2.png)

2022-10-08 21:24 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +### Where can I find my address QR code and the corresponding QR code?
```suggestion
### Where can I find my address QR code?
```

2022-10-09 01:48 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> -For example, due to the malleability fix of SegWit, you can now remix CoinJoin outputs which are currently unconfirmed.
I think you can.
That messages is probably because you have banned coins.

2022-10-09 01:48 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Implementing Taproot hasn't been a priority, as the benefits of upgrading to it are negligible for Wasabi, at the moment.
But we are currently working on implementing Taproot.

2022-10-09 08:48 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> -For example, due to the malleability fix of SegWit, you can now remix CoinJoin outputs which are currently unconfirmed.
No banned coins. Just a long chain of coinjoins.

2022-10-09 16:55 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> -For example, due to the malleability fix of SegWit, you can now remix CoinJoin outputs which are currently unconfirmed.
AKAIK we do not have anything in the protocol (or the backend configurations) that prevents unconfirmed coinjoin outputs from remixing.
@MaxHillebrand WDYT?

2022-10-22 14:50 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +Implementing Taproot hasn't been a priority, as the benefits of upgrading to it are negligible for Wasabi, at the moment.
Ok I'll leave this section out of this PR
```suggestion
Wasabi was created after the activation of SegWit, and it makes sense to support the most advanced address type, which has numerous benefits.
For example, due to the malleability fix of SegWit, you can now remix CoinJoin outputs which are currently unconfirmed.
There are also large savings on mining fees for SegWit transactions.
```

2022-10-22 14:52 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +Implementing Taproot hasn't been a priority, as the benefits of upgrading to it are negligible for Wasabi, at the moment.
I'll leave this section out of this PR

2022-10-22 14:52 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> -For example, due to the malleability fix of SegWit, you can now remix CoinJoin outputs which are currently unconfirmed.
I'll leave this section out of this PR

2022-10-22 23:26 UTC, yahiheb requested changes

2022-10-22 23:26 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +This is useful when you have generated a receiving address with a specific label, but then the sender has changed.
```suggestion
This is useful when you have generated a receiving address with a specific label, but then the sender (anyone that knows this address is yours) has changed.
```

2022-10-22 23:26 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
>  Take care with whom you have shared this address, because if you send it to several people, they might all send many coins to the same address.
```suggestion
Take care with whom you have shared this address, because if you send it to several people, they all know this address belongs to you, and they might all send many coins to the same address.
```

2022-10-22 23:26 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +It is especially important to **NEVER** send your extended public key to any third party.
```suggestion
It is especially important to **NEVER** send your extended public key to any third party (anyone).
```

2022-10-22 23:27 UTC, yahiheb approved these changes

2022-10-22 23:28 UTC, merged