FAQUse: improve backup wording
zkSNACKs/WasabiDoc pull request #1276
Opened 2022-10-10 08:50 UTC by MarnixCroes

detail,
as we use _Recovery Words_ everywhere, it's better if the warning says that too

2022-10-10 08:57 UTC, MaxHillebrand approved these changes

2022-10-11 03:15 UTC, yahiheb requested changes

2022-10-11 03:15 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +In order to restore a wallet, you need BOTH the Recovery Words AND the password!
```suggestion
In order to restore a wallet, you need BOTH the recovery words AND the password!
```

2022-10-11 03:15 UTC, yahiheb approved these changes

2022-10-11 03:15 UTC, merged