Coinjoin: add Coinjoin Settings
zkSNACKs/WasabiDoc pull request #1295
Opened 2022-10-19 12:27 UTC by MarnixCroes

closes https://github.com/zkSNACKs/WasabiDoc/issues/1138

this is a start
will be fine tuned later on
and maybe go into the details of each coinjoin strategy

2022-10-19 17:36 UTC, MaxHillebrand requested changes

2022-10-19 17:36 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +As the coinjoin settings apply per individual wallet, it is possible to have multiple wallets with different coinjoin settings
```suggestion
As the coinjoin settings apply per individual wallet, it is possible to have multiple wallets with different coinjoin settings.
```

2022-10-19 17:36 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +When this is active, the wallet will automatically start coinjoining when the wallet is opened.
```suggestion
When this is active, the wallet will automatically start coinjoining soon after the wallet is loaded.
```

2022-10-19 17:36 UTC, MaxHillebrand commented on docs/using-wasabi/CoinJoin.md
> +These coinjoin strategies determine settings like how much and when to coinjoin.
Maybe say that it specifically change anonscore target and its vlaues.

Also mention its the fee rate time preference

2022-10-21 08:29 UTC, MarnixCroes commented on docs/using-wasabi/CoinJoin.md
> +These coinjoin strategies determine settings like how much and when to coinjoin.
[2d04a14](https://github.com/zkSNACKs/WasabiDoc/pull/1295/commits/2d04a14af0a3527f402e996b6bd17cc2df6b85c8)

2022-11-09 17:41 UTC, MarnixCroes commented
RFM?

2022-11-14 10:09 UTC, yahiheb requested changes

2022-11-14 10:09 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +Each of these coinjoin strategies contain different configurations.
```suggestion
Wasabi ships with 3 coinjoin strategies: `Minimize Costs`, `Maximize Speed`, and `Maximize Privacy`.
Each of these contain different configurations.
```

2022-11-14 10:18 UTC, yahiheb requested changes

2022-11-14 10:18 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The wallet will not automatically start coinjoining if the non-private balance is less than the `Auto-start coinjoin threshold`, even if the `Automatically start coinjoin` is active.
```suggestion
The wallet will not automatically start coinjoining if the non-private balance is below the `Auto-start coinjoin threshold`, even if the `Automatically start coinjoin` is active.
```

2022-11-14 10:20 UTC, yahiheb requested changes

2022-11-14 10:20 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The wallet will not automatically start coinjoining if the non-private balance is below the `Auto-start coinjoin threshold`, even if the `Automatically start coinjoin` is active.
```suggestion
The default Auto-start coinjoin threshold is 0.01 BTC.

The wallet will not automatically start coinjoining if the non-private balance is below the `Auto-start coinjoin threshold`, even if the `Automatically start coinjoin` is active.
```

2022-11-14 10:20 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The default Auto-start coinjoin threshold is 0.01 BTC.
```suggestion
```

2022-11-14 10:21 UTC, MarnixCroes commented on docs/using-wasabi/CoinJoin.md
> +The default Auto-start coinjoin threshold is 0.01 BTC.
I think it would be good to have all the `active by default` setting as a tip at the bottom of each setting
I can do that in follow up PR

2022-11-14 10:24 UTC, yahiheb requested changes

2022-11-14 10:24 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +It is possible to make your own custom profile by using the customize button.
```suggestion
It is possible to make your own custom strategy by using the customize button. 
```

2022-11-14 10:27 UTC, yahiheb requested changes
`CoinjoinProfileSettings.png`

The picture is not up-to-date, it should show `Coinjoin Strategy Settings`.
The name of the file also should change.

2022-11-14 10:28 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The default Auto-start coinjoin threshold is 0.01 BTC.
I moved it to the top for now, but feel free to make another PR.

2022-11-14 10:35 UTC, MarnixCroes commented
> `CoinjoinProfileSettings.png`
> 
> The picture is not up-to-date, it should show `Coinjoin Strategy Settings`. The name of the file also should change.

fixed

2022-11-14 10:40 UTC, yahiheb approved these changes

2022-11-14 10:40 UTC, merged