update Install Package page
zkSNACKs/WasabiDoc pull request #1300
Opened 2022-10-24 11:42 UTC by peterchaudhary

- The doc is written for "a mother in her mid 40s or 50s" (as discussed with Rafe and Max) as the primary audience. I have filled in the gaps of how exactly to verify a signature.
- Not sure if and where to add Jesse's videos. I don't have the links, but can surely add them in if required.
- New format arranged based on tasks rather than on OS seems to be cleaner
- Brought in and modified the "Build from source" page, since it would technically come under the "Install Wasabi" topic. Plus I'm assuming we are planning to stick with the following outline for Using Wasabi:

1. Install Wasabi
2. Setup wallet
3. Receive bitcoin
4. Send bitcoin
5. Coinjoin
6. Generate wallets
7. Connect hardware-wallet
8. Connect full-node

2022-10-24 11:52 UTC, peterchaudhary commented on docs/using-wasabi/InstallPackage.md
> +GPGTools makes it breeze to import, verify, and sign digital signatures.
a breeze

2022-10-24 12:01 UTC, MarnixCroes requested changes

2022-10-24 12:01 UTC, MarnixCroes commented on docs/using-wasabi/InstallPackage.md
> +# Install Wasabi
the title should not be renamed (for now)

2022-10-24 12:31 UTC, peterchaudhary commented on docs/using-wasabi/InstallPackage.md
> +# Install Wasabi
ok will update this

2022-10-24 21:00 UTC, BTCparadigm commented on docs/using-wasabi/InstallPackage.md
```suggestion
```

2022-10-24 21:02 UTC, BTCparadigm commented on docs/using-wasabi/InstallPackage.md
> +This page contains all the information you will need to safely install the Wasabi Wallet.
```suggestion

This page contains all the information you will need to safely install the Wasabi Wallet. 
```

2022-10-24 21:07 UTC, BTCparadigm commented on docs/using-wasabi/InstallPackage.md
> +Note that the latter section is only meant for experienced users, who know what they are doing, and must be used with extreme caution. For everyone else, the *Install Wasabi Wallet* section is suffic
Start new sentence with a new line
```suggestion
Note that the latter section is only meant for experienced users, who know what they are doing, and must be used with extreme caution. 
For everyone else, the *Install Wasabi Wallet* section is sufficient.
```

2022-10-24 21:09 UTC, BTCparadigm commented on docs/using-wasabi/InstallPackage.md
> +For improved privacy, we recommended that you use the [Tor browser](https://www.torproject.org/) and download the installer from the [official clearnet-website.](http://wasabiukrxmkdgve5kynjztuovbg43
```suggestion
For improved privacy, we recommended that you use the [Tor browser](https://www.torproject.org/) and download the installer from the [Wasabi's official Tor-website.](http://wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okcrsg7gb6jdmbad.onion/)
```

2022-10-25 07:54 UTC, peterchaudhary commented on docs/using-wasabi/InstallPackage.md
> +    dpkg -i /Users/John/Downloads/Wasabi-2.0.1.4.msi
not sure if this is accurate @MarnixCroes @yahiheb

2022-10-25 07:55 UTC, peterchaudhary commented on docs/using-wasabi/InstallPackage.md
> +    dpkg -i /Users/John/Downloads/Wasabi-2.0.1.4.msi
I don't have a Windows machine to verify

2022-10-25 07:58 UTC, peterchaudhary commented on docs/using-wasabi/InstallPackage.md
> -Although there is automatic signature verification on Windows and macOS, it is still recommended to manually **VERIFY PGP SIGNATURES** of the downloaded package with zkSNACKs' PGP public key [${zksna
If there is automatic signature, but we still recommend manual verification, then we might as well tell users how to manually verify

2022-10-25 22:09 UTC, peterchaudhary commented on docs/using-wasabi/InstallPackage.md
> +:::success Congratulations!
not sure if this format is correct

2022-10-25 22:48 UTC, BTCparadigm commented on docs/using-wasabi/InstallPackage.md
> +
```suggestion
```

2022-10-27 00:21 UTC, BTCparadigm reviewed
Suggested a bunch of tiny nitpicks

2022-10-27 00:21 UTC, BTCparadigm commented on docs/using-wasabi/InstallPackage.md
> +## Install Wasabi Wallet
```suggestion
## Install Wasabi Wallet

```

2022-10-27 00:21 UTC, BTCparadigm commented on docs/using-wasabi/InstallPackage.md
> +## Install GPGTools
```suggestion
## Install GPGTools

```

2022-10-27 00:21 UTC, BTCparadigm commented on docs/using-wasabi/InstallPackage.md
> +## Why verify signature?
```suggestion
## Why verify signature?

```

2022-10-27 00:21 UTC, BTCparadigm commented on docs/using-wasabi/InstallPackage.md
> +## Build from source
```suggestion
## Build from source

```

2022-10-27 10:38 UTC, peterchaudhary commented on docs/using-wasabi/InstallPackage.md
> +        3. The act of copying, when GPGTools is open, will cause GPGTools to propmt you to decide whether or not to import the key. Accept the request.
modified the syntax for it to read better

2022-11-02 09:10 UTC, peterchaudhary commented
> this breaks links
I can change the format; however, there will be a lot of repeated content. In fact, there is not much content to really divide up. So, I'm not quite sure how to rearrange the existing material. Plus, this format is the industry standard for tech docs. The steps usually have headings (Download installer, Verify signature, Install), but since we are not going to be referring to these topics outside of this page, I have removed the headings to make the page really concise.

> BuildSource should NOT be moved to the general install doc. it is advanced and ony used by less than 1% of users AND it breaks links

I can surely remove the `Build from source` section, although for retrievability this seems to be the best place. Also, if you don't mind, could you please confirm the outline of the `Using Wasabi` section, to help me understand where topics such as these would go?

The outline I assumed we are working towards is in the description.

2023-08-23 07:26 UTC, MarnixCroes commented
Build from source should not be added to this.

cACK for improving the Install package.
If you plan to continue working on this, please open a new PR

2023-08-23 07:26 UTC, closed without merging