FAQUSe: add How do I start using wasabi
zkSNACKs/WasabiDoc pull request #1307
Opened 2022-10-25 12:25 UTC by MarnixCroes

2022-10-25 17:56 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +5. Enjoy your private bitcoin funds! ([spend](/using-wasabi/Send.md) some, send to your [hardware wallet](/using-wasabi/ColdWasabi.md) (for cold storage) or leave them in Wasabi for a while)
```suggestion
5. Enjoy your private bitcoin funds! ([Spend](/using-wasabi/Send.md) some, send to your [hardware wallet](/using-wasabi/ColdWasabi.md) (for cold storage) or leave them in Wasabi for a while)
```

2022-10-26 14:33 UTC, BTCparadigm submitted a review, later dismissed
LGTM

2022-10-27 01:49 UTC, yahiheb requested changes

2022-10-27 01:49 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +5. Enjoy your private bitcoin funds! ([Spend](/using-wasabi/Send.md) some, send to your [hardware wallet](/using-wasabi/ColdWasabi.md) (for cold storage) or leave them in Wasabi for a while)
```suggestion
1. [Download & Install](/using-wasabi/InstallPackage.md) Wasabi (like with any other software) from the [official website](https://wasabiwallet.io).
2. [Create a new wallet](/using-wasabi/WalletGeneration.md) or use an already existing one, by [importing or recovering](/using-wasabi/WalletRecovery.md) your own wallet.
3. [Receive](/using-wasabi/Receive.md) some bitcoin.
4. Wait, and let the wallet do some [coinjoins](/using-wasabi/CoinJoin.md).
Your wallet's privacy progress % would increase.
5. Enjoy your private bitcoin funds!
[Spend](/using-wasabi/Send.md) some, send to your [hardware wallet](/using-wasabi/ColdWasabi.md) (for cold storage) or leave them in Wasabi for a while.
```

2022-10-27 01:50 UTC, yahiheb approved these changes

2022-10-27 01:51 UTC, merged