ColdWasabi: update using hww step-by-step
zkSNACKs/WasabiDoc pull request #1315
Opened 2022-10-31 09:38 UTC by MarnixCroes

2022-11-10 15:57 UTC, yahiheb requested changes

2022-11-10 15:57 UTC, yahiheb commented on docs/using-wasabi/ColdWasabi.md
> +2. Click on `Connect to hardware wallet` and then connect the hardware wallet via cable. Alternatively, you can import a Coldcard skeleton file via SD card by using `Import Wallet` at the add wallet
```suggestion
2. Click on `Connect to hardware wallet` and then connect the hardware wallet via cable. Alternatively, you can import a Coldcard skeleton file via SD card by using `Import Wallet` at the `Add Wallet` dialog.
```

2022-11-10 15:57 UTC, yahiheb commented on docs/using-wasabi/ColdWasabi.md
> +6. You can [spend](/using-wasabi/Send.md) these coins in the `Send` dialog, though the hardware wallet must be connected via USB to confirm before signing the transaction.
```suggestion
6. You can [spend](/using-wasabi/Send.md) these coins in the `Send` dialog, though the hardware wallet must be connected via USB to sign the transaction.
```

2022-11-10 16:05 UTC, yahiheb commented
How about deleting all of this, it is redundant and #1317 will explain the steps in details.

2022-11-11 09:07 UTC, MarnixCroes commented
> How about deleting all of this, it is redundant and #1317 will explain the steps in details.

imo it's ok to leave this for now
.
This functions as short step overview, where later on each step is collaborated on
note that, most other _using wasabi_ also have these step by step

2022-11-11 21:05 UTC, yahiheb approved these changes

2022-11-11 21:05 UTC, merged