ColdWasabi: update import the wallet
zkSNACKs/WasabiDoc pull request #1317
Opened 2022-10-31 10:07 UTC by MarnixCroes

added the tip, as this is always confusing for newbies

2022-11-10 16:09 UTC, yahiheb requested changes

2022-11-10 16:09 UTC, yahiheb commented on docs/using-wasabi/ColdWasabi.md
> +4. Connect the hardware wallet to the PC and enter the pin on the hardware wallet to unlock it.
```suggestion
4. Connect the hardware wallet to the PC and enter the pin (if one is set up) on the hardware wallet to unlock it.
```

2022-11-10 16:09 UTC, yahiheb commented on docs/using-wasabi/ColdWasabi.md
> +Because you need to sign (confirm) outgoing transactions on the hardware wallet.
```suggestion
Because you need to sign (confirm) the outgoing transactions on the hardware wallet.
```

2022-11-10 16:09 UTC, yahiheb commented on docs/using-wasabi/ColdWasabi.md
> +So, you can see the balance and all it's transactions in Wasabi, but you cannot send without the hardware wallet being connected.
```suggestion
So, you can see the balance and all it's transactions in Wasabi and you can generate addresses, but you cannot send without the hardware wallet being connected.
```

2022-11-11 09:09 UTC, MarnixCroes commented on docs/using-wasabi/ColdWasabi.md
> +4. Connect the hardware wallet to the PC and enter the pin on the hardware wallet to unlock it.
I think the pin is mandatory for all supported hww's?

2022-11-11 21:00 UTC, yahiheb commented on docs/using-wasabi/ColdWasabi.md
> +4. Connect the hardware wallet to the PC and enter the pin on the hardware wallet to unlock it.
I don't think it is mandatory.
Here also it is mentioned that there might not be a PIN:
https://github.com/zkSNACKs/WalletWasabi/pull/9431#discussion_r1011852907

2022-11-11 21:01 UTC, yahiheb approved these changes

2022-11-11 21:01 UTC, merged