FAQInstallation: update how verify signature
zkSNACKs/WasabiDoc pull request #1320
Opened 2022-10-31 16:32 UTC by MarnixCroes

2022-10-31 22:32 UTC, yahiheb requested changes

2022-10-31 22:32 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
IMO we should keep at least that command.

```suggestion
In the terminal, change the directory to the one with the downloaded files, and verify the signature with `gpg --verify Wasabi-${currentVersion}.deb.asc`, or with another command, depending on which operating system you are.
```

2022-11-01 08:39 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
nack

2022-11-01 08:57 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
How would someone who does not know the command know which command to use?

2022-11-01 09:02 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
click on the links underneath for the full guide for each OS, where it is in more detail explained how to for mac, linux and windauws

2022-11-01 11:25 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
In the Windows and macOS there guides there is no mention of any command.
Plus this command works on all OSs.

2022-11-01 11:39 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
verify deb package on macOS or Win?

2022-11-01 14:15 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
Check the updated suggestion.

2022-11-07 11:16 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
> In the terminal, change the directory to the one with the downloaded files, and verify the signature with `gpg --verify` + the corresponding signature file name, depending on which operating system you are.

that's incorrect, you need both both the signature file and the package

2022-11-07 13:39 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
Both of these commands work:
`gpg --verify Wasabi-2.0.2.msi.asc`
`gpg --verify Wasabi-2.0.2.msi.asc Wasabi-2.0.2.msi`

2022-11-07 13:50 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +In the terminal, change the directory to the one with the downloaded files, and verify the signature with the correct commands, depending on which operating system you are.
ok I didn't know that works on win and mac

2022-11-07 13:56 UTC, MaxHillebrand approved these changes

2022-11-07 14:00 UTC, yahiheb approved these changes

2022-11-07 14:02 UTC, yahiheb requested changes

2022-11-07 14:02 UTC, yahiheb approved these changes

2022-11-07 14:03 UTC, merged