FAQUse: Misc update or remove outdated information
zkSNACKs/WasabiDoc pull request #1349
Opened 2022-11-09 15:22 UTC by turbolay

Explanation of changes:

1) Even if I was also a frequent user of https://jochen-hoenicke.de/queue/#0,24h, nowadays https://mempool.space/ UI has more info and is easier to understand
2) `Build Transaction` feature doesn't exist anymore in WW2 (except from RPC). This section is outdated.
3) `InputRegistration` in WW2 is different: 150 inputs min and fixed time frame. I didn't mention that this time frame is 10 minutes because it can change etc etc. If you want me to add please notify I will.
4) Same as 3)
5) https://testnet-faucet.mempool.co/ is dead
6) `if there are a lot of users` this doesn't apply to WW2
7) `How long does it take to mix my coins?` this section was written for WW1, it's completely irrelevant for WW2. We could rewrite it instead of a straight deletion, but other sections below like `How long does it take to make my wallet 100% private?` are already bringing updated info.
8) Non private coins are now grey not red anymore
9) `How can I mix large amounts?` this section was written for WW1, it's completely irrelevant for WW2. We could rewrite it instead of a straight deletion, but other sections are already bringing updated info

2022-11-10 09:47 UTC, MarnixCroes approved these changes
LGTM

2022-11-13 13:31 UTC, yahiheb requested changes

2022-11-13 13:31 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +### After I CoinJoined my coins and reached green anonset, I sent them to my hardware wallet address. When I check my HW via Wasabi, the coins are now grey. Why?
This breaks external links, and the content is still not up to date, let's not edited for now.

```suggestion
### After I CoinJoined my coins and reached green anonset, I sent them to my hardware wallet address. When I check my HW via Wasabi, the coins are now red. Why?
```

2022-11-13 13:31 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
```suggestion
```

2022-11-13 13:58 UTC, turbolay commented
implemented all of your suggestions @yahiheb.
For the faucet, I found another dead link in the doc so I updated also, and I added https://bitcoinfaucet.uo1.net/ below befcause it sends much less coins than the other one.

2022-11-13 14:03 UTC, MaxHillebrand approved these changes

2022-11-13 14:13 UTC, yahiheb requested changes

2022-11-13 14:13 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +Clients since v2.0.1.4 can simply turn on the setting `Auto download new version`, and all the work will be done in the background. More information is available in the dedicated [section](/FAQ/FAQ-I
Usually we write every sentence in a new line. https://github.com/zkSNACKs/WasabiDoc#writing-conventions

```suggestion
Clients since v2.0.1.4 can simply turn on the setting `Auto download new version`, and all the work will be done in the background.
More information is available in the dedicated [section](/FAQ/FAQ-Installation.md#how-does-the-auto-download-new-version).
```

2022-11-13 14:13 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
```suggestion
```

2022-11-13 14:13 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
>  [coinfaucet.eu/en/btc-testnet](https://coinfaucet.eu/en/btc-testnet/)
```suggestion
[coinfaucet.eu/en/btc-testnet](https://coinfaucet.eu/en/btc-testnet/) or [bitcoinfaucet.uo1.net](https://bitcoinfaucet.uo1.net/)
```

2022-11-13 14:15 UTC, yahiheb requested changes

2022-11-13 14:15 UTC, yahiheb commented on docs/using-wasabi/Testnet.md
> +There are [faucets](https://en.bitcoin.it/wiki/Testnet#Faucets) like [this one](https://coinfaucet.eu/en/btc-testnet/) that give a certain amount of testnet bitcoin per time period.
```suggestion
There are [faucets](https://en.bitcoin.it/wiki/Testnet#Faucets) like [this one](https://coinfaucet.eu/en/btc-testnet/) or [bitcoinfaucet.uo1.net](https://bitcoinfaucet.uo1.net/) that give a certain amount of testnet bitcoin per time period.
```

2022-11-13 20:23 UTC, turbolay commented
@yahiheb ready for merge

2022-11-14 02:31 UTC, yahiheb approved these changes

2022-11-14 02:31 UTC, merged