how does Wasabi select which coins to send
zkSNACKs/WasabiDoc pull request #1351
Opened 2022-11-14 10:12 UTC by MarnixCroes

2022-11-14 11:09 UTC, yahiheb requested changes
This is not really correct, it is more nuanced than that.

https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs#L63

It is also worth mentioning this:

> Moreover if you have coins that you received in the past from the same recipient (same label as the receiver) Wasabi will use those before even the private coins.

2022-11-16 11:26 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Wasabi automatically first selects the private coins.
```suggestion
If the user has a coin with the same label, then Wasabi automatically first selects this coin. 
```

2022-11-16 12:59 UTC, yahiheb requested changes

2022-11-16 13:06 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Which non-private coins will be used can be selected by the user, based on the labelling system.
why? the user selects at "who should know about this transaction" which label to use

2022-12-01 13:37 UTC, yahiheb requested changes

2022-12-01 13:37 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +If this is not the case, or the labelled coin is not enough, then Wasabi will select private coins.
```suggestion
If the user has coins with the same label (as the recipient label of the outgoing transaction), then Wasabi automatically selects these coins.
If there are no such coins, or they are not enough, then Wasabi will select private and semi private coins if necessary.
```

2022-12-01 13:37 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +If there are no/not enough private coins for this transaction, then Wasabi will select private coins + non-private coins.
```suggestion
If there are no/not enough private and semi-private coins for this transaction, then Wasabi will select non-private coins also.
```

2022-12-01 13:49 UTC, yahiheb requested changes

2022-12-01 13:51 UTC, yahiheb requested changes

2022-12-01 13:51 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Which non-private coins will be used can be selected by the user, based on the labelling system.
```suggestion
The user can change which non-private coins will be used, based on the labelling system.
```

2022-12-01 13:54 UTC, merged