FAQUse: update why anonscore change after sending (to hww)
zkSNACKs/WasabiDoc pull request #1421
Opened 2023-01-05 11:00 UTC by MarnixCroes

I'm not  sure about the ins and outs of this.
anyway, better than current

yes breaks links, should be changed anyway

2023-01-05 19:42 UTC, yahiheb requested changes

2023-01-05 19:42 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +### After I coinjoined my coins and reached 100% privacy, I sent them to my hardware wallet address. When I check my HWW via Wasabi, the coins are now a lower anonscore or anonscore 1. Why?
```suggestion
### After I coinjoined my coins and reached 100% privacy, I sent them to my hardware wallet and now the coins have anonscore 1. Why?
```

2023-01-05 19:42 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The anonymity score (number) is tied to your wallet that you used to coinjoin, if you send a coinjoined coin to another Wasabi Wallet of yours (hardware wallet or normal wallet) it will have a lower
```suggestion
The anonymity score (number) is tied to your wallet that you used to coinjoin, if you send a coinjoined coin to another Wasabi Wallet of yours (hardware wallet or normal wallet) it will have an anonscore of 1 because this wallet doesn't know all of the coinjoin history.
```

2023-01-05 19:42 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +You should put a meaningful label when you generate a receive address in your hardware wallet, e.g. "coinjoined private" (something that reminds you that you got this utxo from your Wasabi Wallet and
```suggestion
You should put a meaningful label when you generate a receive address in your hardware wallet, e.g. "private utxo" (something that reminds you that you got this utxo from your Wasabi Wallet and it was coinjoined).
```

2023-01-05 19:42 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Because it knows this from the other wallet.
Hmmm idk about this, how does it work?

2023-01-06 10:00 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Because it knows this from the other wallet.
idk how it works, but it happens

2023-01-06 14:09 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Because it knows this from the other wallet.
@BTCparadigm Do you have any idea about this?

2023-01-06 19:43 UTC, BTCparadigm commented on docs/FAQ/FAQ-UseWasabi.md
> +Because it knows this from the other wallet.
Nope. 
@MarnixCroes do you know how to repro?

2023-01-09 09:54 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Because it knows this from the other wallet.
coinjoin and then send to hww.

it has something to do with interoperability of anonscore between wallets.
i.e. when you open an other hot wallet it might (temporarily) decrease anonscore of an other wallet

2023-01-09 21:08 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Because it knows this from the other wallet.
I wouldn't mention this, that might be an issue not a feature.

2023-01-10 10:44 UTC, merged