create Getting Started Guide
zkSNACKs/WasabiDoc pull request #1448
Opened 2023-02-16 15:21 UTC by MarnixCroes

https://github.com/zkSNACKs/WasabiDoc/issues/1383

what' were missing currently is an easy accessible step-by-step page on how to get started

You're a noob, you don't know anything and just want to try Wasasbi, right now you'd have to do multiple clicks to multiple pages.
This `Getting Started` is supposed to be easy newbie friendly step-by-step overview and less overwhelming

I didn't went into too much detail as then it would get very cluttered.
And didn't add images (for now), we could add these later

![image](https://user-images.githubusercontent.com/93143998/219403690-137d083d-2b0e-47ef-a98b-7f4e96af2908.png)

2023-05-23 13:34 UTC, yahiheb requested changes

2023-05-23 13:34 UTC, yahiheb commented on docs/getting-started/README.md
> +How to do this depends per desktop operating system, the detailed guides can be found here: [Windows](/using-wasabi/InstallPackage.md#windows), [Debian/Ubuntu](/using-wasabi/InstallPackage.md#debian-
```suggestion
How to do this depends on the desktop operating system, the detailed guides can be found here: [Windows](/using-wasabi/InstallPackage.md#windows), [Debian/Ubuntu](/using-wasabi/InstallPackage.md#debian-and-ubuntu), [Other Linux](/using-wasabi/InstallPackage.md#other-linux), [macOS](/using-wasabi/InstallPackage.md#macos)
```

2023-05-23 13:34 UTC, yahiheb commented on docs/getting-started/README.md
> +How to do this depends per desktop operating system, the detailed guides can be found here: [Windows](/using-wasabi/InstallPackage.md#windows), [Debian/Ubuntu](/using-wasabi/InstallPackage.md#debian-
```suggestion
How to do this depends on the desktop operating system, the detailed guides can be found here: [Windows](/using-wasabi/InstallPackage.md#windows), [Debian/Ubuntu](/using-wasabi/InstallPackage.md#debian-and-ubuntu), [Other Linux](/using-wasabi/InstallPackage.md#other-linux), [macOS](/using-wasabi/InstallPackage.md#macos)
```

2023-05-23 14:14 UTC, yahiheb requested changes

2023-05-23 14:14 UTC, yahiheb commented on docs/getting-started/README.md
> +
```suggestion

[[toc]]

```

2023-05-23 14:14 UTC, yahiheb commented on docs/getting-started/README.md
> +Please refer to the rest of the documentation for detailed explanations and best practices.
```suggestion

Please refer to the rest of the documentation for detailed explanations and best practices.
```

2023-05-23 14:14 UTC, yahiheb commented on docs/getting-started/README.md
> +-Recover a wallet
```suggestion
- Create a new wallet
- Connect hardware wallet
- Import a wallet
- Recover a wallet
```

2023-05-23 14:14 UTC, yahiheb commented on docs/getting-started/README.md
> +Click on Receive at the top right to [receive](/using-wasabi/Receive.md) some bitcoin to this new wallet.
```suggestion
Click on `Receive` at the top right to [receive](/using-wasabi/Receive.md) some bitcoin to this new wallet.
```

2023-05-23 14:14 UTC, yahiheb commented on docs/getting-started/README.md
> +Now wait while you leave Wasabi running so it can do some coinjoins.
```suggestion

Coinjoin will automatically start after the incoming funds are confirmed.
You need to manually press the play button in the musicbox (at the bottom of the wallet) if you received less than 0.01 BTC.

You know that your wallet is coinjoining if you see the stop button in the musicbox and the spectrum ("waving" color animationn) at the bottom of the wallet.

Now wait while you leave Wasabi running so it can do some coinjoins.
```

2023-05-23 14:14 UTC, yahiheb commented on docs/getting-started/README.md
> +Make sure to check the rest of the documentation for explanations and (privacy) best practices.
```suggestion
```

2023-05-25 07:30 UTC, MarnixCroes commented on docs/getting-started/README.md
> +How to do this depends on the desktop operating system, the detailed guides can be found here: [Windows](/using-wasabi/InstallPackage.md#windows), [Debian/Ubuntu](/using-wasabi/InstallPackage.md#debi
remove it then?
It differs per OS and is explained at the `Install`

2023-05-25 07:31 UTC, MarnixCroes commented on docs/getting-started/README.md
> +or leave them in Wasabi for a while.
imo good to mention it

2023-05-25 08:18 UTC, yahiheb requested changes

2023-05-25 08:18 UTC, yahiheb commented on docs/getting-started/README.md
> +This is short comprehensive guide on how to get started using Wasabi.
```suggestion
This is a short comprehensive guide on how to get started using Wasabi.
```

2023-05-25 08:18 UTC, yahiheb commented on docs/getting-started/README.md
> +
Let's just remove all of this section, it doesn't add much value, it is obvious that a user should click on some application icon/shortcut to open it.
```suggestion
```

2023-05-25 08:45 UTC, MarnixCroes commented on docs/getting-started/README.md
> +
I get your point.

Who knows what to do will not read this (guide).
People who need help will. For them I think this is useful clarification ?

2023-05-25 10:06 UTC, yahiheb commented on docs/getting-started/README.md
> +
If someone doesn't know how to run an application what are they doing using bitcoin and Wasabi?

2023-05-25 10:07 UTC, yahiheb approved these changes

2023-05-25 10:07 UTC, merged

2023-05-25 10:09 UTC, MarnixCroes commented on docs/getting-started/README.md
> +
😃
You are overestimating the average (computer) user (which only knows to open browser and email :D )