add BIP 86 to derivation path
zkSNACKs/WasabiDoc pull request #1450
Opened 2023-02-20 10:42 UTC by MarnixCroes

2023-02-21 22:59 UTC, yahiheb requested changes
Idk, this is confusing to me.
I guess currently we only use `m/84'/0'/0'` for change outputs in coinjoin, so I think we shouldn't say that Wasabi uses that as derivation path.

2023-02-22 12:24 UTC, lontivero commented
Wasabi support of taproot is limited in the sense that we are currently not generating external taproot addresses. Technically specking  there is nothing preventing us to do it but for now we simply didn't want to touch the UI and introduce an address type selection.

2023-03-12 22:46 UTC, yahiheb approved these changes

2023-03-12 22:53 UTC, yahiheb requested changes

2023-03-12 22:53 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
>  On RegTest it uses `m/84'/0'/0'`, and not the standard `m/84'/1'/0'` path.
```suggestion
On TestNet Wasabi uses the paths `m/84'/1'/0'` and `m/86'/1'/0'`.
On RegTest it uses `m/84'/0'/0'` and `m/86'/0'/0'`, and not the standard `m/84'/1'/0'` and `m/86'/1'/0'` paths.
```

2023-03-12 22:56 UTC, yahiheb requested changes

2023-03-12 22:56 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Note that Taproot isn't supported yet so the main path is `m/84'/0'/0'`.
```suggestion

Note that Wasabi is currently not generating external taproot addresses yet so the main path is `m/84'/0'/0'`.
```

2023-03-12 22:56 UTC, yahiheb approved these changes

2023-03-12 22:57 UTC, merged