add Taproot to watch only wallets
zkSNACKs/WasabiDoc pull request #1459
Opened 2023-03-06 09:32 UTC by MarnixCroes

2023-03-06 18:48 UTC, yahiheb requested changes

2023-03-06 18:48 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Then paste your _SegWit Extended Account Public Key_ in-between the quotes of the field `"ExtPubKey": "paste xpub here",` and your _Taproot Extended Account Public Key_ in-between the quotes of the f
```suggestion
Then paste your _SegWit Extended Account Public Key_ in-between the quotes of the field `"ExtPubKey": "paste segwit xpub here",` and your _Taproot Extended Account Public Key_ in-between the quotes of the field `TaprootExtPubKey": "paste taproot xpub here",`
```

2023-03-07 08:59 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Then paste your _SegWit Extended Account Public Key_ in-between the quotes of the field `"ExtPubKey": "paste xpub here",` and your _Taproot Extended Account Public Key_ in-between the quotes of the f
?

2023-03-07 10:10 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Then paste your _SegWit Extended Account Public Key_ in-between the quotes of the field `"ExtPubKey": "paste xpub here",` and your _Taproot Extended Account Public Key_ in-between the quotes of the f
You precisely mentioned  `SegWit Extended Account Public Key`, so I suggest `"paste segwit xpub here"` instead of `"paste xpub here"`.

2023-03-07 10:20 UTC, yahiheb requested changes

2023-03-07 10:20 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Notice that Wasabi only works with native SegWit bech32, and Taproot bech32m addresses.
Maybe this is more accurate, as Max has pointed out here that Taproot is native segwit too. https://github.com/zkSNACKs/WalletWasabi/pull/10221#issuecomment-1451612231.

```suggestion
Notice that Wasabi only works with SegWit v0 bech32, and SegWit v1 bech32m (Taproot) addresses.
```

2023-03-07 10:23 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Then paste your _SegWit Extended Account Public Key_ in-between the quotes of the field `"ExtPubKey": "paste xpub here",` and your _Taproot Extended Account Public Key_ in-between the quotes of the f
ah ok I only saw the change of capital letter

2023-03-07 10:33 UTC, yahiheb approved these changes

2023-03-07 10:33 UTC, merged