add taproot output coinjoin
zkSNACKs/WasabiDoc pull request #1467
Opened 2023-03-13 09:13 UTC by MarnixCroes

closes https://github.com/zkSNACKs/WasabiDoc/issues/1457

2023-03-14 08:09 UTC, yahiheb requested changes

2023-03-14 08:09 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +If running this version or higher, the client registers the output type in a semi-random way (~50% change of receiving Taproot output).
```suggestion
If running this version or higher, the client registers the output type in a semi-random way (~50% chance of receiving Taproot output).
```

2023-03-14 08:11 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +If running this version or higher, the client registers the output type in a semi-random way (~50% chance of receiving Taproot output).
Shouldn't we simply say:
```suggestion
If running this version or higher, the client registers the output type in a random way (~50% chance of receiving Taproot output).
```

2023-03-14 10:03 UTC, MarnixCroes commented on docs/using-wasabi/CoinJoin.md
> +If running this version or higher, the client registers the output type in a semi-random way (~50% chance of receiving Taproot output).
afaik it's not flip a coin, heads or tails 50/50
there is some deterministic randomness

2023-03-15 07:46 UTC, yahiheb approved these changes

2023-03-15 07:47 UTC, merged