update RestoreElectrum
zkSNACKs/WasabiDoc pull request #1479
Opened 2023-04-04 09:45 UTC by MarnixCroes

closes https://github.com/zkSNACKs/WasabiDoc/issues/1452

-remove recovery using master private key
-remove recovery by manually creating wallet file

not possible anymore

2023-04-09 16:59 UTC, yahiheb requested changes
IMO we should keep this (at least for a while) for WW1 users and for WW2 version prior to v2.0.2.1.

2023-04-09 16:59 UTC, yahiheb commented on docs/using-wasabi/RestoreElectrum.md
> +5. Type in your seed.
```suggestion
5. Type in your seed (recovery words).
```

2023-04-12 10:14 UTC, MarnixCroes commented
I think we shouldn't.
We have other places where we decided to have the doc only match the latest release version, like with max coinjoin amount (and not: Wasabi version X do this, Wasabi version X cannot do this etc.).
We should keep it that way.

> Because it is useful for users using any version prior to v2.0.2.

we could have small note and just link to the archive if really needed

2023-04-12 17:20 UTC, yahiheb approved these changes

2023-04-12 17:21 UTC, merged