What do i need to recover wallet + create table
zkSNACKs/WasabiDoc pull request #1482
Opened 2023-04-06 14:02 UTC by MarnixCroes

this question still comes up all the time.
we have similar FAQ listed like _Can I recover my wallet without the password?_
but a general one is missing

I think it would be good to have this with a clear table (for real newbs)
![image](https://user-images.githubusercontent.com/93143998/230400800-e669a8c3-e42c-49fa-bfb7-3f7afa85ed01.png)

2023-04-09 16:31 UTC, yahiheb requested changes

2023-04-09 16:31 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +To recovery your wallet you need your Password + Recovery words, or Password + Wallet File, as shown in the table below.
```suggestion
To recover your wallet you need either your Recovery Words + Password, or the Wallet File + Password, as shown in the table below.
```

2023-04-09 16:31 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +If there was an emtpy password (no password) entered at the wallet creation, then the Recovery Words or Wallet File alone are enough to recover the wallet.
```suggestion
If no password was entered at the wallet creation, then the Recovery Words or Wallet File alone are enough to recover the wallet.
```

2023-04-09 16:35 UTC, yahiheb requested changes

2023-04-09 16:35 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Password | :heavy_check_mark: |  :heavy_check_mark: |
I would add an X to indicate that the recovery words or the wallet file alone is not enough (ofc assuming that a password was used which should be considered the default)

```suggestion
Recovery Words | :x: | :x: | :heavy_check_mark:
Wallet File | :x: | :x: | :heavy_check_mark:
Password | :heavy_check_mark: | :heavy_check_mark: | :x:
```

2023-04-11 08:48 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Password | :heavy_check_mark: |  :heavy_check_mark: |
does that make sense?

2023-04-12 04:59 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Password | :heavy_check_mark: |  :heavy_check_mark: |
For me it does.
What does an empty spot mean?

2023-04-12 13:41 UTC, merged