Daemon
zkSNACKs/WasabiDoc pull request #1509
Opened 2023-04-28 09:27 UTC by MarnixCroes

- previous links are restored
- content will be improved in follow up PR's

2023-04-28 09:27 UTC, MarnixCroes commented
wait for merge until release?

2023-04-28 14:39 UTC, lontivero commented on docs/using-wasabi/Daemon.md
> +This daemon is especially useful for power users mixing bitcoin in the backend of their servers.
This is an opinion and to me is wrong. In fact, the final goal should be to have the daemon running on every desktop.

2023-05-06 23:06 UTC, yahiheb requested changes

2023-05-06 23:06 UTC, yahiheb commented on docs/using-wasabi/Daemon.md
> +---
```suggestion
```

2023-05-06 23:09 UTC, yahiheb reviewed
Shouldn't we add some available commands and how to use the daemon?
Like we had before removing it here https://github.com/zkSNACKs/WasabiDoc/pull/1232/files

2023-06-27 13:45 UTC, MarnixCroes commented
still a WIP

currently I have not mentioned `Environment variables` anywhere, should this be mentioned in the docs here? Does it add anything for the normal user? wdty @lontivero ?

2023-06-29 11:50 UTC, lontivero commented
Environment variables have the same importance than command line switches. For example, these two are equivalent:

```bash
$ wassabee --network=main
```

```bash
$ WASABI_NETWORK=main wassabee
```

However, there are many cases where environment variables are much more convenient. Imagine you want to use a different DATADIR in your environment, how do you do it? Well, you just set the `WASABI_DATADIR` environment variable to wherever you want and that does  the trick. For example:

```
WASABI_DATADIR=Z:/encrypted-folder/wasabi
```

It is impossible to do this using config file and it is not so convenient to do it using command line switches.

2023-07-10 15:08 UTC, MarnixCroes commented
> Is this PR finished @MarnixCroes ?

I need to add how to run on Win and mac as, afaik, you cannot just do `wassabeed` from terminal.
other than that yes.

2023-07-14 10:45 UTC, MarnixCroes commented on docs/using-wasabi/Daemon.md
> +There are a few special switches that are not present in the `Config.json` file and are only available using the command line:
done

2023-07-14 15:27 UTC, yahiheb requested changes

2023-07-14 15:27 UTC, yahiheb commented on docs/using-wasabi/Daemon.md
> + Switch | Command Line| Environment variable|
```suggestion
| Switch | Command Line| Environment variable|
```

2023-07-14 15:27 UTC, yahiheb commented on docs/using-wasabi/Daemon.md
> +Run Wasabi and connect to the testnet Bitcoin network with Tor disabled and accept JSON RPC calls. Store everything in `$HOME/temp/wasabi-1`.
```suggestion
Run Wasabi and connect to the testnet Bitcoin network with Tor disabled and accept JSON RPC calls and ignore P2P transactions.
Store everything in `$HOME/temp/wasabi-1`.
```

2023-07-17 15:24 UTC, MarnixCroes commented on docs/using-wasabi/Daemon.md
> +Depending on your operating system, open the command line and execute:
done 074b818c0

2023-07-17 16:27 UTC, MaxHillebrand submitted a review, later dismissed

2023-07-17 16:49 UTC, thibistaken commented on docs/using-wasabi/Daemon.md
> +Open the terminal, navigate to the WalletWasabi.Daemon directory (inside the cloned repository) and execute the desired commands.
Maybe add that you can use verbose log parameter `--loglevel=debug`?

2023-07-17 16:56 UTC, MaxHillebrand commented on docs/using-wasabi/Daemon.md
> +Open the terminal, navigate to the WalletWasabi.Daemon directory (inside the cloned repository) and execute the desired commands.
See line 62

2023-08-22 06:11 UTC, yahiheb requested changes

2023-08-22 06:11 UTC, yahiheb commented on docs/using-wasabi/Daemon.md
> +The daemon is included in the Wasabi package starting from version 2.0.4 and can be launched using the command line.
```suggestion
The daemon is included in the Wasabi package starting from version [2.0.4](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.4) and can be launched using the command line.
```

2023-08-22 06:11 UTC, yahiheb commented on docs/using-wasabi/Daemon.md
> + Switch | Command Line| Environment variable|
For consistency.

2023-08-22 06:16 UTC, yahiheb commented on docs/using-wasabi/Daemon.md
> + Switch | Command Line| Environment variable|
Update this for consistency.

2023-08-22 07:59 UTC, merged