[release] update verify version, CLI: --version
zkSNACKs/WasabiDoc pull request #1514
Opened 2023-05-02 12:39 UTC by MarnixCroes

2023-05-04 03:49 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
Executing this with the current release (2.0.3) runs Wasabi GUI and doesn't return any version.

2023-05-04 10:46 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
yes because it's not in that release

2023-05-06 22:55 UTC, yahiheb approved these changes
utACK

2023-08-22 05:51 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
This didn't work on Win10, but `wassabeed --version` worked.

2023-08-22 08:04 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
idk, it works on Linux

2023-08-22 10:09 UTC, yahiheb requested changes

2023-08-22 10:09 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
```suggestion
You can also verify the version using the command line by executing `wassabee --version` or `wassabeed --version` depending on your OS.
```

2023-08-23 01:11 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
I am testing the right version:

![image](https://github.com/zkSNACKs/WasabiDoc/assets/52379387/c4a6eeeb-da81-45a5-adca-8eace0a26ad2)

2023-08-23 12:02 UTC, lontivero commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
What¿s the errorlevel?

2023-08-23 21:08 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
I didn't run the command line with master, but with the released version from this path `C:\Program Files\WasabiWallet`.

2023-10-13 23:18 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
> @yahiheb Could you please confirm?

Btw yes I confirm that.

2023-10-14 15:07 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
> We should file an issue for this in the WalletWasabi repo and discuss what to do with that.

Yes I already did it before making that comment: https://github.com/zkSNACKs/WalletWasabi/issues/11688

2024-01-09 11:09 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
what do you mean _depending on your OS_?
I think we should just put a note that `wassabee --version` doesn't work on win.
until it's fixed

2024-01-09 17:23 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
> what do you mean depending on your OS?

I have updated my suggestion to be specific to windows.

2024-01-11 09:22 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`.
I see what you mean.
It will currently give the same result, but these are two different things and could in the future give different result.
this makes it look like wassabeed is specfically a windows command.

2024-01-11 11:15 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`, and `wassabeed --version` for the [Daemon](/using-wasabi/Daemon.md) version.
ACK

2024-01-11 11:59 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`, and `wassabeed --version` for the [Daemon](/using-wasabi/Daemon.md) version.
imho I prefer how it is now

this is the "correct" one, telling people to use daemon version command to check the GUI version, because it doesn't work on one OS feels a bit hacky.

2024-01-11 12:00 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`, and `wassabeed --version` for the [Daemon](/using-wasabi/Daemon.md) version.
anyway, if you still think we should only mention wassabeed --version, then let's use that and not spend more time on this.

2024-01-12 01:01 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`, and `wassabeed --version` for the [Daemon](/using-wasabi/Daemon.md) version.
The correct one is to use `wassabee --version` but currently there is an issue with this on Windows, so a note or a hack is needed anyway.
I think we should simply go with Kimi's suggestion and update this once the issue is fixed.

2024-01-12 14:11 UTC, MarnixCroes commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`, and `wassabeed --version` for the [Daemon](/using-wasabi/Daemon.md) version.
there is a note 
https://github.com/zkSNACKs/WasabiDoc/pull/1514/files#diff-d2d9f0d8f72baaaae52cec35e4602f430e80d72d4c8929f3f11167ff235d8fddR157

2024-01-12 16:20 UTC, yahiheb commented on docs/FAQ/FAQ-Installation.md
> +You can also verify the version using the command line by executing `wassabee --version`, and `wassabeed --version` for the [Daemon](/using-wasabi/Daemon.md) version.
We can simply say: "To check the version execute X command" which should work for all OSs and move on.
All this PR is for a small addition on how to check the version.

2024-01-15 14:21 UTC, yahiheb approved these changes

2024-01-15 14:21 UTC, merged