Add TurboSync entry
zkSNACKs/WasabiDoc pull request #1546
Opened 2023-06-21 06:12 UTC by turbolay

I wrote that, I think that the explanation is exhaustive and good, but maybe a bit too long and technical.
Please someone with better english and better skills to write doc (cc @MarnixCroes) it would be great if you can suggest modifications.

2023-06-21 08:16 UTC, MarnixCroes reviewed
Nice!
Could you make every sentence start on a [new line](https://github.com/zkSNACKs/WasabiDoc/#writing-conventions) plz

2023-06-21 18:49 UTC, yahiheb requested changes
This is good.

Should we use the term `address` instead of `key`?

2023-06-21 18:49 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +As a result, addresses with many derived keys will have to download many false positives, making the synchronization more and more time consuming.
```suggestion
As a result, wallets with many derived keys will have to download many false-positive blocks, making the synchronization more time consuming.
```

2023-06-21 18:49 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +In other terms, once an internal key has been used to receive a coin and then this coin was used as input in a new transaction (the coin has been spent), the key should never be used again, and there
I think we can just remove `and then this coin was used as input in a new transaction (the coin has been spent)`.
WDYM by `higher filters`?

```suggestion
In other terms, once an internal key has been used to receive a coin, it should never be used again, and there is no need to test it against higher filters.
```

2023-06-21 18:49 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +After the wallet will be opened, the skipped keys will then be tested in the background, in the case that some funds have been received on keys skipped.
```suggestion
Once the wallet is opened, the skipped keys will be tested in the background, in the case that some funds have been received on those keys.
```

2023-06-21 18:49 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +Users in that case would see their balance update automatically after some time.
To emphasize that this should be an edge case.

```suggestion
Users in that edge case would see their balance update automatically after some time.
```

2023-06-21 18:49 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +A log message `Wallet is fully synchronized.` indicates when the verification process finishes.
I think we don't have to mention this.

2023-06-21 18:49 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +In that case, go to your wallet configuration file (search for `Wallet Folder` using Wasabi's searchbar then open the file corresponding to your wallet) and set `UseTurboSync` to `false`.
```suggestion
In that case, go to your wallet file (search for `Wallet Folder` using Wasabi's searchbar then open the file corresponding to your wallet) and set `UseTurboSync` to `false`.
```

2023-06-21 22:40 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +In other terms, once an internal key has been used to receive a coin and then this coin was used as input in a new transaction (the coin has been spent), the key should never be used again, and there
> This is factually incorect, as the coin will be used again when spending. Do you think we should ignore that?

What if the key was used just to receive, could it be used again? Is there a need to test it against higher filters?

Maybe I am missing something here, but when we talk about reusing an address/key we mean using the address more than once to receive not about spending of course, otherwise there could be no such a thing as address reuse.
IMO yes we can remove it.

> Higher filters I mean higher height filter (so if the address spent at height 1.000, all filters higher than 1000 don't need to be tested against this key). Please make a new suggestion.

I am definitely missing something here :)

2023-06-21 22:42 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +A log message `Wallet is fully synchronized.` indicates when the verification process finishes.
Will this be displayed in the GUI for the user? Plus this is an edge case AFAIK.

2023-06-21 22:44 UTC, yahiheb commented
> I introduced the term `key` in the first part of the text. If it was not clear enough for you, it won't be clear enough for users. I will update.

It is clear for me, I am asking if we should make this less technical for readers who might get confused by the term `key`.

2023-06-22 07:23 UTC, MarnixCroes commented on docs/using-wasabi/WalletLoad.md
> +A log message `Wallet is fully synchronized.` indicates when the verification process finishes.
We should keep it imo

2023-06-22 07:23 UTC, MarnixCroes commented on docs/using-wasabi/WalletLoad.md
> +During a coinjoin, a new address (key) has to be generated for each output.
will the release be 2.0.4 or 2.1?

2023-06-22 07:24 UTC, MarnixCroes commented on docs/using-wasabi/WalletLoad.md
> +During a coinjoin, a new address (key) has to be generated for each output.
I would add this, as it's reach easier if you know what the purpose is of the feature.
And someone who doesn't understand still gets the point.

2023-06-22 07:58 UTC, MarnixCroes commented on docs/using-wasabi/WalletLoad.md
> +A log message `Wallet is fully synchronized.` indicates when the verification process finishes.
We should keep it imo

2023-06-23 08:55 UTC, MarnixCroes reviewed
ACK, 
add the correct [release number](https://github.com/zkSNACKs/WasabiDoc/pull/1546/files#diff-7dc9f3c35965e2c1ebe5e083be63f635ff013fdbf4874db2f87360410f6899a5R50) & than merge at release

2023-06-23 13:23 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +In other terms, once an internal key has been used to receive a coin and then this coin was used as input in a new transaction (the coin has been spent), the key should never be used again, and there
Thank you for the explanation, now it is clear.
I would revert the part that says `addresses should be used only twice` to `addresses should be used only once`.
Sorry about the confusion.

2023-06-23 13:41 UTC, yahiheb requested changes

2023-06-23 13:41 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +It leverages a simple heuristic: addresses used as coinjoin outputs or as change (internal keys) should only be used twice: one time to receive coins and another time to spend them.
```suggestion
It leverages a simple heuristic: addresses used as coinjoin outputs or as change (internal keys) should only be used once.
```

2023-06-23 13:41 UTC, yahiheb commented on docs/using-wasabi/WalletLoad.md
> +A log message `Wallet is fully synchronized.` indicates when the verification process finishes.
> I am afraid of users stating "Why my balance is incorrect??" because in that case, they should wait until the log message "wallet is fully synchronized"

I do not expect those user to know how TurboSync works and to open the logs file and wait for the message.

I would make it clear that it is a logs message so readers do not expect to see this in the GUI.

```suggestion
Once done the message `Wallet is fully synchronized.` is written to the logs file to indicate that the verification process has finished.
```

2023-06-27 20:15 UTC, MarnixCroes commented on docs/using-wasabi/WalletLoad.md
> +Since Wasabi version 2.x a new feature is added called _TurboSync_.
```suggestion
Since Wasabi version 2.0.4 a new feature is added called _TurboSync_.
```

2023-06-27 20:17 UTC, MarnixCroes commented
> @yahiheb @MarnixCroes TurboSync has been merged [zkSNACKs/WalletWasabi#10896](https://github.com/zkSNACKs/WalletWasabi/pull/10896) This PR can be merged as well.

nah not yet, as changes get immediately deployed.
Waiting for the release, as trying to keep the docs updated with latest release version

2023-08-21 15:13 UTC, MarnixCroes commented on docs/using-wasabi/WalletLoad.md
> +Since Wasabi version 2.0.4 a new feature is added called _TurboSync_.
```suggestion
Since Wasabi version [2.0.4](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.4)a new feature is added called _TurboSync_.
```

2023-08-21 15:16 UTC, MarnixCroes commented on docs/using-wasabi/WalletLoad.md
> +Since Wasabi version [2.0.4](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.4)a new feature is added called _TurboSync_.
```suggestion
Since Wasabi version [2.0.4](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.4) a new feature is added called _TurboSync_.
```

2023-08-21 15:17 UTC, MarnixCroes approved these changes
Thanks!

2023-08-21 15:17 UTC, merged