FAQ: How can i speed up
zkSNACKs/WasabiDoc pull request #1566
Opened 2023-08-09 11:08 UTC by MarnixCroes

todo:

- [ ]  figure out when _speed up tx_ does RBF or CPFP -> add it to the FAQ

- [ ]  remove _how can i bump the fee with CPFP_ FAQ

dediced to do the step-by-step with a dropdown, to not clutter the FAQ too much with these images etc.

2023-08-22 06:45 UTC, yahiheb requested changes
> figure out when speed up tx does RBF or CPFP -> add it to the FAQ

It is worth mentioning when each one is used.

> dediced to do the step-by-step with a dropdown, to not clutter the FAQ too much with these images etc.

We do not use such step-by-step with a dropdown elsewhere in the docs so I wouldn't do that.
I would simply mention the first two steps, the rest is straightforward: Right click on the pending transaction, then confirm you want to pay the additional fee.

2023-08-22 06:45 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +A pending transaction may be bumped with RBF by using the [_Speed Up Transaction_ tool](/FAQ/FAQ-UseWasabi.md#how-can-i-speed-up-a-pending-transaction)
```suggestion
A pending transaction may be bumped (RBF) by using the [_Speed Up Transaction_ feature](/FAQ/FAQ-UseWasabi.md#how-can-i-speed-up-a-pending-transaction)
```

2023-08-22 06:45 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +A pending (unconfirmed) transaction can be speeded up by using the _Speed Up Transaction_ tool by right-clicking on the transaction in the history.
```suggestion
A pending (unconfirmed) transaction can be speeded up by using the _Speed Up Transaction_ feature by right-clicking on the transaction in the history.
```

2023-08-22 06:45 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Since Wasabi version 2.0.4 this FAQ is now obsolete because of the new [_Speed Up Transaction_ tool](/FAQ/FAQ-UseWasabi.md#how-can-i-speed-up-a-pending-transaction) that can be used.
```suggestion
Since Wasabi version [2.0.4](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.4) this FAQ is now obsolete because of the new [_Speed Up Transaction_ feature](/FAQ/FAQ-UseWasabi.md#how-can-i-speed-up-a-pending-transaction) that can be used.
```

2023-08-22 06:45 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +<br>
```suggestion

```

2023-08-22 06:45 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +<summary>Click here to expand for a step-by-step instruction:</summary>
```suggestion
<summary>Click here to expand for a step-by-step instruction guide:</summary>
```

2023-08-22 06:45 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +It will replace the current transaction with one paying a higher fee rate.
Here we can mention when RBF or CPFP is used.

2023-08-22 06:49 UTC, yahiheb requested changes

2023-08-22 06:49 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +<summary>Click here to expand for a step-by-step instruction guide:</summary>
```suggestion
<summary>Click here to expand for a step-by-step instruction guide:</summary>

```

2023-08-22 10:14 UTC, yahiheb commented
> We do not use such step-by-step with a dropdown elsewhere in the docs so I wouldn't do that.
> I would simply mention the first two steps, the rest is straightforward: Right click on the pending transaction, then confirm you want to pay the additional fee.

@MarnixCroes Let's update this to merge the PR.

2023-08-22 11:32 UTC, MarnixCroes commented
@yahiheb you make several edits and then say it is not needed?

2023-08-22 11:33 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +The transaction will be speeded up by sending a new transaction with a higher fee rate.
```suggestion
The transaction will be speeded up by sending a new transaction with a higher fee rate.
```
to keep it simple, this is true for both RBF and CPFP

2023-08-22 11:35 UTC, merged

2023-08-23 02:54 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Read more [here](/using-wasabi/Send.md#speed-up-or-cancel-transaction).
This link here is currently broken.

@MarnixCroes I know that this will be fixed once #1567 is merged, but this is a bad practice to merge PRs with broken links or images.
You could have simply added this line in the follow up PR.