[release] Send: speed up or cancel transaction
zkSNACKs/WasabiDoc pull request #1567
Opened 2023-08-10 14:26 UTC by MarnixCroes

first merge https://github.com/zkSNACKs/WasabiDoc/pull/1566/ as it contains the image file

2023-08-22 11:44 UTC, MarnixCroes commented
the only things that's missing imo is some info about how much it will speed it up

2023-08-23 02:36 UTC, yahiheb requested changes

2023-08-23 02:36 UTC, yahiheb commented on docs/using-wasabi/Send.md
> +Wasabi first tries to utilize [RBF](glossary/Glossary-GeneralBitcoin.html#replace-by-fee-rbf), but if that's not possible it will do [CPFP](glossary/Glossary-GeneralBitcoin.html#child-pays-for-parent
```suggestion
Wasabi first tries to utilize [RBF](glossary/Glossary-GeneralBitcoin.html#replace-by-fee-rbf), if that's not possible it tries to do [CPFP](glossary/Glossary-GeneralBitcoin.html#child-pays-for-parent-cpfp).
```

2023-08-23 02:36 UTC, yahiheb commented on docs/using-wasabi/Send.md
> +Select it and then confirm that you want to pay the additional fee for this action.
```suggestion
Click one of the two options and then confirm that you want to pay the additional fee for this action.
```

2023-08-23 02:36 UTC, yahiheb commented on docs/using-wasabi/Send.md
> +In the history, the transaction will now have a rocket icon (speeded up) or a cross (cancelled).
```suggestion
In the history, the transaction will now have a rocket (speeded up) or a cross (cancelled) icon.
```

2023-08-23 02:36 UTC, yahiheb commented on docs/using-wasabi/Send.md
> +The transaction is still pending, but it will be confirmed sooner than previously.
```suggestion
The transaction is still pending, but it should be confirmed sooner than the initial transaction.
```

2023-08-23 02:45 UTC, yahiheb commented
Since we have an FAQ on how to speed up a transaction, should we add a separate FAQ for how to cancel a transaction?
(This question is not related to this PR)

2023-08-23 07:10 UTC, merged