FAQ: how can I cancel pending TX
zkSNACKs/WasabiDoc pull request #1583
Opened 2023-08-29 12:41 UTC by MarnixCroes

cc86d83a88887b214fd8c5ebeb6ecaa81e32edbc to improve the title of the image, so it's also correct for cancelling: 
`SpeedUpHistory.png` -> `HistoryRightClick.png` 
`SpeedUpConfirm.png` -> `SpeedUpTxConfirm.png`

2023-08-29 13:34 UTC, yahiheb requested changes
Ude `btc` denomination for `CancelTxConfirm.png` instead of sats to be consistent with the other screenshots.

2023-08-29 13:34 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The replacement transaction is sent to an address of the user's wallet, so the bitcoin comes back to the user's wallet and the transaction can be considered "cancelled".
```suggestion
The replacement transaction is sent to an address of the user's wallet, so the bitcoin comes back and the transaction can be considered "cancelled".
```

2023-08-29 13:34 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
>  - Transaction succesfully speeded up!
These are obvious steps that can be removed, and to be consistent.

```suggestion
```

2023-08-29 15:29 UTC, MaxHillebrand submitted a review, later dismissed

2023-09-11 08:26 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
>  - Transaction succesfully speeded up!
Why shouldn't these be removed? And if they shouldn't why not add them to the cancel transaction steps?

2023-09-11 10:08 UTC, merged