update coin list FAQ
zkSNACKs/WasabiDoc pull request #1590
Opened 2023-09-11 07:00 UTC by MarnixCroes

- remove it from `Send` section (it was added there when there was no coin control yet)
- rephrase the question from `how select coins for sending` to `How can I see my wallet's coins`
- kept the image there and mentioning of using it for sending, as that for some cases can still be handy

2023-09-11 07:38 UTC, yahiheb requested changes

2023-09-11 07:38 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +### How can I see my wallet's coins?
For seeing coins, the users can use the privacy ring.
The `Wallet Coins` dialog is not for seeing coins, it is for sending specific coins in full.
If we have to rephrase the question, it would be better to change it to:

```suggestion
### How do I select/spend specific coins?
```

2023-09-11 07:42 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +### How can I see my wallet's coins?
privacy ring lacks information, 
like script type, coinjoining or not, confirmation count, unable to see all labels (when many).

2023-09-11 10:32 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +### How can I see my wallet's coins?
Yes it lacks information, but as I mentioned the purpose of `Wallet Coins` `dialog` is not to see coins.

2023-10-13 22:58 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +### How can I see my wallet's coins?
@MarnixCroes What's up with this one?

2023-10-19 16:50 UTC, closed without merging