clarify speed up and cancel not possbile for coinjoin or hww
zkSNACKs/WasabiDoc pull request #1597
Opened 2023-09-12 09:27 UTC by MarnixCroes

2023-09-12 10:24 UTC, MaxHillebrand commented on docs/FAQ/FAQ-UseWasabi.md
> +> It is not possible to speed up a coinjoin or a transaction sent with a hardware wallet.
Is CPFP flow of incoming tx to hww possible?

2023-09-12 10:43 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +> It is not possible to speed up a coinjoin or a transaction sent with a hardware wallet.
Afaik only if you do it manually, not with the speedup tool

2023-09-12 10:47 UTC, MaxHillebrand requested changes

2023-09-12 10:47 UTC, MaxHillebrand commented on docs/FAQ/FAQ-UseWasabi.md
> +> It is not possible to speed up a coinjoin or a transaction sent with a hardware wallet.
```suggestion
> It is not possible to speed up a coinjoin or a hardware wallet transaction.
```

Its for both incoming and outgoing.

2023-09-12 10:47 UTC, MaxHillebrand commented on docs/FAQ/FAQ-UseWasabi.md
> +> It is not possible to cancel a coinjoin or a transaction sent with a hardware wallet.
```suggestion
> It is not possible to cancel a coinjoin or a hardware wallet transaction.
```

2023-09-12 11:12 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +> It is not possible to speed up a coinjoin or a transaction sent with a hardware wallet.
cack
or maybe  `The speed up tool is not available for coinjoins, or when using a hardware wallet.`

2023-09-13 06:48 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +> It is not possible to speed up a coinjoin or a transaction sent with a hardware wallet.
pushed

2023-09-13 09:44 UTC, merged