Updated search field
zkSNACKs/WasabiDoc pull request #1613
Opened 2023-11-09 11:05 UTC by CAnorbo

The new search field with Agolia can search inside the content. Fix for: #1612

2023-11-09 11:06 UTC, CAnorbo commented
@turbolay

2023-11-09 18:46 UTC, yahiheb requested changes
I get this error when trying to test this:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@vuepress/plugin-docsearch' imported from C:\Users\User\OneDrive\Bureau\WasabiDoc\docs\.vuepress\config.ts.3611753a.mjs
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

2023-11-09 18:47 UTC, CAnorbo commented
Try to run: npm install

2023-11-09 18:55 UTC, turbolay commented
It works for me but I had several problems with it I'm trying to compile them

2023-11-09 19:51 UTC, yahiheb reviewed
> Try to run: npm install

Thanks, that worked.

I tested this a bit and it looks fine, let's wait for Clement's review.

2023-11-09 22:52 UTC, turbolay commented
Sorry I took time I was busy:
- The bar is too small, it was bigger in the past
- There are many cases like this: 
![CleanShot 2023-11-09 at 16 42 59@2x](https://github.com/zkSNACKs/WasabiDoc/assets/16029533/6bc19fa8-bf75-4c4e-a0b0-8b8a84e6803f)
 the link for this blank item is https://docs.wasabiwallet.io/using-wasabi/ColdWasabi.html#cold-wasabi-hardware-wallet-mode
- It is too permissive, it gives us irrelevant results. Better here show no result
<img width="298" alt="CleanShot 2023-11-09 at 16 43 58@2x" src="https://github.com/zkSNACKs/WasabiDoc/assets/16029533/9858c533-dfd9-49cb-b367-3fe3c2b46620">

2023-11-10 11:04 UTC, CAnorbo commented
> Sorry I took time I was busy:
> 
> * The bar is too small, it was bigger in the past
> * There are many cases like this:
>   ![CleanShot 2023-11-09 at 16 42 59@2x](https://user-images.githubusercontent.com/16029533/281902793-6bc19fa8-bf75-4c4e-a0b0-8b8a84e6803f.png)
>   the link for this blank item is https://docs.wasabiwallet.io/using-wasabi/ColdWasabi.html#cold-wasabi-hardware-wallet-mode
> * It is too permissive, it gives us irrelevant results. Better here show no result
> 
> <img alt="CleanShot 2023-11-09 at 16 43 58@2x" width="298" src="https://user-images.githubusercontent.com/16029533/281902902-9858c533-dfd9-49cb-b367-3fe3c2b46620.png">

I made the search bar bigger, but I can't rewrite how is it working. I checked their website and even their search bar works the same.
There are a few options on their documentation but, not for these kinds of things.
https://docsearch.algolia.com/docs/api/#searchparameters
https://www.algolia.com/doc/api-reference/search-api-parameters/

2023-11-10 22:46 UTC, yahiheb requested changes
> I made the search bar bigger, but I can't rewrite how is it working. I checked their website and even their search bar works the same.

The PR is good as is, this can be improved in the future of course

2023-11-10 22:46 UTC, yahiheb commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
![image](https://github.com/zkSNACKs/WasabiDoc/assets/52379387/2713725f-e66e-4999-b7f8-746fe6f69df2)

This looks unnecessarily too big IMO, specially we cannot type in it.

I tested with `80% ` and it looks great.

```suggestion
	width: calc(80% - 250px) !important;
```

2023-11-13 08:21 UTC, CAnorbo commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
With this change, the search field won't be visible on some smaller desktop / tablet screens.

2023-11-13 08:24 UTC, CAnorbo commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
I added a different change that makes the search bar smaller on bigger screens. Maybe this solves the current problem.

2023-11-13 08:34 UTC, yahiheb commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
It is still the same for me.

2023-11-13 08:47 UTC, turbolay commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
On my screen it looks perfect now. On mobile it takes all the length and I think it's cool

2023-11-13 08:52 UTC, CAnorbo commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
> It is still the same for me.

What is your screen size?

2023-11-13 08:56 UTC, turbolay commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
13.6", 3420x2080 
for mobile I use chrome "mobile view"

![CleanShot 2023-11-13 at 02 55 35@2x](https://github.com/zkSNACKs/WasabiDoc/assets/16029533/bd4a83fc-aabb-4541-9c3d-5f38bf6b6823)

2023-11-13 09:12 UTC, CAnorbo commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
I meant Yahiheb. If you have 1590px or wider screen, you'll see the difference if you have smaller, you won't see any changes.

2023-11-13 09:40 UTC, yahiheb commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
17-inch screen, 3840 x 2400

2023-11-13 09:42 UTC, CAnorbo commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
Try to empty cache or rerun the docs, you should see the same as Turbolay.

2023-11-13 15:17 UTC, yahiheb approved these changes
The search field still looks too big for me, but I will merge this and I will ping you @CAnorbo  to improve this if needed.

2023-11-13 15:17 UTC, yahiheb commented on docs/.vuepress/styles/index.scss
> +	width: calc(100% - 250px) !important;
It still the same for me.

2023-11-13 15:17 UTC, merged