RPC: payincoinjoin, listpaymentsincoinjoin, cancelpaymentincoinjoin
zkSNACKs/WasabiDoc pull request #1629
Opened 2024-01-04 13:30 UTC by MarnixCroes

2024-02-16 10:14 UTC, MarnixCroes commented on docs/using-wasabi/RPC.md
> +Payments in coinjoin can in theory be made to any ScriptPubKey, however the zkSNACKs coordinator currently only accepts P2WPKH and P2TR outputs.
changed this in last push.
previously it was something like _it is only possible for native segwit_
this is better and can later easily add P2PKH P2WSH P2SH etc.

2024-03-01 00:25 UTC, yahiheb requested changes

2024-03-01 00:25 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +
```suggestion
```

2024-03-01 00:25 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +Pay to a bitcoin address in a coinjoin.
```suggestion
Pay to a specific bitcoin address in a coinjoin.
```

2024-03-01 00:25 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +Lists current payincoinjoin('s).
```suggestion
Lists the current payments in coinjoins.
```

2024-03-01 00:25 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +{
Same as above, separate between the bash command and the json result.

2024-03-01 00:25 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +Cancel a _paymentincoinjoin_.
```suggestion
Cancels a payment in coinjoin.
```

2024-03-01 00:25 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +{
Same as above.

2024-03-01 00:25 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +The parameter is the paymentId of the pending payment to be cancelled.
```suggestion
The parameter is the paymentId of the pending payment in coinjoin to be cancelled.
```

2024-03-01 00:25 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +
```suggestion
```

2024-03-03 09:37 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +{
I meant to separate the command and the result completely, not just by a line.

2024-03-03 09:38 UTC, yahiheb approved these changes
tACK

2024-03-03 09:38 UTC, merged

2024-03-03 18:54 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +{
https://github.com/zkSNACKs/WasabiDoc/pull/1680