RPC: speeduptransaction & canceltransaction
zkSNACKs/WasabiDoc pull request #1635
Opened 2024-01-09 13:17 UTC by MarnixCroes

2024-03-05 22:02 UTC, yahiheb requested changes

2024-03-07 09:44 UTC, MarnixCroes commented on docs/using-wasabi/RPC.md
> +Speeds up a transaction and returns the transaction hex, ready for broadcast.
not always true, it can also create a CPFP
I added that

2024-03-07 15:03 UTC, yahiheb requested changes

2024-03-07 15:03 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +Builds a transaction with a higher fee rate (or creates a [CPFP](glossary/Glossary-GeneralBitcoin.html#child-pays-for-parent-cpfp) transaction if [RBF](glossary/Glossary-GeneralBitcoin.html#replace-b
This is now more confusing, it says:
- builds a transaction, or
- creates a CPFP if RBF is not possible

```suggestion
Builds a transaction with a higher fee rate (creates a [CPFP](glossary/Glossary-GeneralBitcoin.html#child-pays-for-parent-cpfp) if [RBF](glossary/Glossary-GeneralBitcoin.html#replace-by-fee-rbf) is not possible) and returns its hex, ready for broadcast.
```

2024-03-07 15:03 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +Builds a transaction with a higher fee rate (or creates a [CPFP](glossary/Glossary-GeneralBitcoin.html#child-pays-for-parent-cpfp) transaction if [RBF](glossary/Glossary-GeneralBitcoin.html#replace-b
```suggestion
Builds a transaction with a higher fee rate (creates a [CPFP](glossary/Glossary-GeneralBitcoin.html#child-pays-for-parent-cpfp) if [RBF](glossary/Glossary-GeneralBitcoin.html#replace-by-fee-rbf) is not possible) and returns its hex, ready for broadcast.
```

2024-03-08 08:34 UTC, MarnixCroes commented on docs/using-wasabi/RPC.md
> +Builds a transaction with a higher fee rate (or creates a [CPFP](glossary/Glossary-GeneralBitcoin.html#child-pays-for-parent-cpfp) transaction if [RBF](glossary/Glossary-GeneralBitcoin.html#replace-b
I found the suggestion more confusing than the original,
clarified it in another way [5e572fb](https://github.com/zkSNACKs/WasabiDoc/pull/1635/commits/5e572fbf5e0fc4a70ad765eb3dcd66b788341cd5)

2024-03-11 10:22 UTC, MarnixCroes commented on docs/using-wasabi/RPC.md
> +Builds a transaction with a higher fee rate ([RBF](glossary/Glossary-GeneralBitcoin.html#replace-by-fee-rbf)), or creates a [CPFP](glossary/Glossary-GeneralBitcoin.html#child-pays-for-parent-cpfp) tr
[f448719](https://github.com/zkSNACKs/WasabiDoc/pull/1635/commits/f4487192e7812ca11f76299c1ce1e1fbeb0ce283) is best imo.
keeps it simple "speeds up or cancels transaction" and simply mention first tries RBF, if not possible it will do CPFP

2024-03-12 22:51 UTC, yahiheb approved these changes

2024-03-12 22:51 UTC, merged