create StartupParameters pillar
zkSNACKs/WasabiDoc pull request #1637
Opened 2024-01-10 09:45 UTC by MarnixCroes

as the Start up parameters are not Daemon specific, remove them from the Daemon into a new pillar at Advanced Using Wasabi

2024-01-10 10:05 UTC, MaxHillebrand submitted a review, later dismissed

2024-01-16 23:20 UTC, yahiheb requested changes

2024-01-16 23:20 UTC, yahiheb commented on docs/.vuepress/config.ts
> +                    "/using-wasabi/StartupParameters.md"
I think it is better to put this as the first sub page before the Daemon.

2024-01-17 07:12 UTC, MarnixCroes commented on docs/.vuepress/config.ts
> +                    "/using-wasabi/StartupParameters.md"
done

2024-01-17 16:06 UTC, yahiheb approved these changes

2024-01-17 16:06 UTC, merged