add PlebStopThreshold to glossary
zkSNACKs/WasabiDoc pull request #1638
Opened 2024-01-10 09:55 UTC by MarnixCroes

2024-01-10 10:05 UTC, MaxHillebrand submitted a review, later dismissed

2024-01-10 17:32 UTC, yahiheb requested changes

2024-01-10 17:32 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +The Pleb Stop Threshold is the amount at which the wallet will not automatically start coinjoin, or it will stop coinjoin when the wallet balance is below this amount.
The auto coinjoin won't start if the total wallet balance is less than the plebstop.

```suggestion
The Pleb Stop Threshold is the minimum wallet balance at which coinjoin will automatically start.
```

2024-01-10 18:40 UTC, Kruwed commented on docs/glossary/Glossary-PrivacyWasabi.md
> +The Pleb Stop Threshold is the amount at which the wallet will not automatically start coinjoin, or it will stop coinjoin when the wallet balance is below this amount.
This is called "Auto-start coinjoin threshold" in the wallet UI, shouldn't the docs match for search purposes even if the internal name is "Pleb Stop"?

2024-01-11 09:12 UTC, MarnixCroes commented on docs/glossary/Glossary-PrivacyWasabi.md
> +The Pleb Stop Threshold is the amount at which the wallet will not automatically start coinjoin, or it will stop coinjoin when the wallet balance is below this amount.
could. 

As the _auto-start coinjoin threshold_ is in the UI with a tooltip explainer
![image](https://github.com/zkSNACKs/WasabiDoc/assets/93143998/f7594d00-c49f-47aa-bf85-0ecea5fe5cce)
I thought explaining plebstop makes more sense, as that verb gets used sometimes (in marketing?) but it's not explained anywhere

2024-01-11 11:20 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +The Pleb Stop Threshold is the amount at which the wallet will not automatically start coinjoin, or it will stop coinjoin when the wallet balance is below this amount.
`Auto-start Coinjoin (Pleb Stop) Threshold` is good enough.

2024-01-12 10:18 UTC, yahiheb approved these changes

2024-01-12 10:18 UTC, merged