RPC: loadwallet & listwallets
zkSNACKs/WasabiDoc pull request #1639
Opened 2024-01-10 12:08 UTC by MarnixCroes

2024-01-10 12:08 UTC, MaxHillebrand submitted a review, later dismissed

2024-03-02 01:32 UTC, yahiheb requested changes
LGTM
Fix conflicts to merge this.

It would be better to **Allow edits from maintainers** on the PRs for quick fixes.

2024-03-03 09:42 UTC, yahiheb requested changes
This needs the conflicts to be fixed again.

2024-03-04 10:43 UTC, yahiheb approved these changes

2024-03-04 10:44 UTC, merged