FAQ min coinjoin amount: link to stats page for current round min amount
zkSNACKs/WasabiDoc pull request #1641
Opened 2024-01-11 11:47 UTC by MarnixCroes

follow up https://github.com/zkSNACKs/WasabiDoc/pull/1634

2024-01-11 11:48 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +> The minimum amount can be higher than 5000 sats when mining fees are relatively high, to not create uneconomical outputs. The minimum amount for current coinjoin round(s) is displayed on the https:
thought about adding it as a `:::tip`, but I think it then becomes too crowded (for such a simple question)
so added it here

2024-01-12 00:52 UTC, yahiheb requested changes

2024-01-12 00:52 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +> The minimum amount can be higher than 5000 sats when mining fees are relatively high, to not create uneconomical outputs. The minimum amount for current coinjoin round(s) is displayed on the https:
```suggestion
> The minimum amount can be higher than 5000 sats when mining fees are relatively high, to not create uneconomical outputs.
The minimum amount for current coinjoin round(s) is displayed on the https://stats.wasabiwallet.io/ page at the _Coinjoin main net lobbies_ section. (The _Min input amount_ excludes the additionally required mining fee)
```

2024-01-12 09:12 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +> The minimum amount can be higher than 5000 sats when mining fees are relatively high, to not create uneconomical outputs. The minimum amount for current coinjoin round(s) is displayed on the https:
done

2024-01-12 10:15 UTC, yahiheb requested changes

2024-01-12 10:15 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The minimum amount for current coinjoin round(s) is displayed on the https://stats.wasabiwallet.io/ page at the _Coinjoin main net lobbies_ section. (The _Min input amount_ excludes the additionally
```suggestion
> The minimum amount can be higher than 5000 sats when mining fees are relatively high, to not create uneconomical outputs.
The minimum amount for the current coinjoin round(s) is displayed on the https://stats.wasabiwallet.io/ page at the _Coinjoin main net lobbies_ section. (The _Min input amount_ excludes the additionally required mining fee)
```

2024-01-12 14:09 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +The minimum amount for current coinjoin round(s) is displayed on the https://stats.wasabiwallet.io/ page at the _Coinjoin main net lobbies_ section. (The _Min input amount_ excludes the additionally
done

2024-01-12 16:12 UTC, yahiheb approved these changes

2024-01-12 16:12 UTC, merged