configurable Tor ports
zkSNACKs/WasabiDoc pull request #1647
Opened 2024-01-16 08:50 UTC by MarnixCroes

closes https://github.com/zkSNACKs/WasabiDoc/issues/1645

 branch based upon https://github.com/zkSNACKs/WasabiDoc/pull/1637, that should be merged first

this PR ads 
748fab15cdfbca59b144180b0a35d8ea1af3dae2: add it to startup parameters
75d24119ecfb5d0741a5a40cccb7bdcfd8507464: add configurable port FAQ and create `Advanced Usage` section.
Good to have it mentioned somewhere, wasn't sure where to put it, creating a new _Advanced Usage_ section seems to be the best. Can move more advanced stuff there later

2024-01-19 20:06 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Since Wasabi version [2.0.6](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.6) it is possible to specify the Tor SOCKS5 Port and Tor Control Port.
reminder to check this link when merging/after release, should be ok tho

2024-03-03 20:57 UTC, yahiheb requested changes

2024-03-03 20:57 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +### Can I change the default Tor port?
To be more precise.

```suggestion
### Can I change the default ports for the Wasabi's bundled Tor?
```

2024-03-03 20:57 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Since Wasabi version [2.0.6](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.6) it is possible to specify the Tor SOCKS5 Port and Tor Control Port.
```suggestion
Since Wasabi version [2.0.6](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.6) it is possible to specify the Tor SOCKS5 and the Tor control ports.
```

2024-03-03 20:57 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +## Advanced Usage
I would put this section at last, under that buy anything button section.

2024-03-04 10:17 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +## Advanced Usage
done

2024-03-04 10:42 UTC, yahiheb approved these changes

2024-03-04 10:42 UTC, merged