FAQ-Use: musicbox
zkSNACKs/WasabiDoc pull request #1649
Opened 2024-01-16 09:42 UTC by MarnixCroes

https://github.com/zkSNACKs/WasabiDoc/issues/1602

didn't do all musicbox messages as there are 23, and some are obvious like _Awaiting coinjoin_

> The structure should be something like this, but can be different:
> - Message1
> --What does it mean?
> --What can I do?

left out _What can I do_ , this can become a rabbit hole, what should user do when having banned coins? send them out or something else...
and things like _Insufficient funds eligible for coinjoin_ is something that should be improved in the UI, by telling the user more, i.e. that he has too small coins.

2024-01-16 09:42 UTC, MarnixCroes commented
@CAnorbo

2024-01-16 10:21 UTC, CAnorbo commented
The point of my request was first to inform the user and second to reduce the support requests by giving them the right troubleshooting steps.

Could you add a "Troubleshooting" section to each message?

2024-01-17 00:25 UTC, yahiheb requested changes

2024-01-17 00:25 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +I.e. current coinjoin(s) are not below the median of the time frame.
This was not very clear to me. How about this:

```suggestion
It means your wallet is waiting to participate in cheaper coinjoin rounds because the fee rate of the current coinjoin(s) is higher than the median of the time frame [Coinjoin time preference](/glossary/Glossary-PrivacyWasabi.md#coinjoin-time-preference).
```

2024-01-17 00:25 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +This message is displayed when the coinjoin round failed due to some Alices disrupting the round and it is going into the [blame round](/using-wasabi/CoinJoin.md#blame-round).
```suggestion
If some other participant disrupted the round by failing to sign the coinjoin transaction, this message briefly appears before a new coinjoin known as the [blame round](/using-wasabi/CoinJoin.md#blame-round) is attempted with the responsive participants from the failed round.
```

2024-01-17 00:25 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +This message is displayed when some coin(s) cannot coinjoin because they are [banned](/FAQ/FAQ-UseWasabi.md#why-do-my-coins-occasionally-get-banned-from-participating-in-coinjoin).
```suggestion
If an input has failed to sign for a previous round it registered to, it will be temporarily banned to prevent denial of service attacks.
Coinjoin coordinators may also reject funds for risk management purposes.
You can view the unban time through the `Wallet Coins` dialog via the search bar or with the keyboard shortcut “CTRL + C + D”.
```

2024-01-17 00:28 UTC, yahiheb commented
> didn't do all musicbox messages as there are 23

@kruwed did write an explanation for most of the music box (I used some of them in my suggestions above), I think we can add them as well.
WDYT?

```
Awaiting auto-start of coinjoin
When you open your wallet, there is a 14 minute delay before the automatic coinjoin process begins. This gives you the chance to ensure your intended transactions are completed and your connection is stable before continuing.

Awaiting coinjoin
This message appears if you have specified a long term coinjoin time preference in your settings and mining fees are higher than normal. Automatic coinjoin will resume when transaction fees drop or stabilize. You can change the coinjoin time preference setting to “hours” to register to coinjoin rounds immediately.

Coinjoin is paused/Coinjoin has stopped
While you have funds in your wallet below your anonymity score target, you can pause the automatic coinjoin function during the input registration phase.

Coinjoin successful! Continuing…
Your privacy progress percentage increases after a successful coinjoin. Once all of your coins reach the anonymity score target defined in the settings, your privacy progress reaches 100% and automatic coinjoin ends.

Round ended, awaiting next round
This message results from a coinjoin round ending early due to too many participants. Following this message, coinjoin participants are split into new rounds sorted by amount for greater efficiency.

Insufficient participants, retrying…
A minimum of 150 inputs are required to register for a coinjoin transaction to be built. A new 10 minute timeframe to gather the required participants starts when the previous one ends.

Coinjoin in progress
Signing the coinjoin transaction occurs during this phase. Pausing is not allowed at this point because it would disrupt the round for the other participants. Avoid disconnecting or closing your wallet during this stage, as it will cause your coins to be temporarily banned from participating in future coinjoin rounds.

Awaiting other participants
During this phase, inputs are registered privately with the coinjoin coordinator. You can view the coins that are selected for coinjoin through the UTXOs screen with the keyboard shortcut “CTRL + C + D”.

Awaiting the blame round
If another participant fails to sign the coinjoin transaction, this message briefly appears before a new coinjoin round is attempted with the responsive participants from the previous round.

Coinjoin may be uneconomical. Add more funds or press ‘Play’ to bypass
This message is displayed while your wallet balance is below the auto-start coinjoin threshold specified in the settings (0.01 BTC by default). This prevents coinjoin from starting automatically when transaction fees would have a high cost relative to your current balance.

Insufficient funds eligible for coinjoin
Inputs that have a value below 0.00005000 BTC are not eligible for coinjoin. You can view your input values through the UTXOs screen with the keyboard shortcut “CTRL + C + D”.

Awaiting confirmed funds
Only confirmed coins are able to register for coinjoin rounds. A timer icon appears in your transaction history next to unconfirmed transactions. If a non-coinjoin payment is stuck in an unconfirmed state, you can right click the entry in your transaction history to use the “Speedup Transaction” function to add mining fees.

Some funds are rejected from coinjoining
If an input has failed to sign for a previous round it registered to, it will be temporarily banned to prevent denial of service attacks. Coinjoin coordinators may also reject funds for risk management purposes. You can view the unban time through the UTXOs screen with the keyboard shortcut “CTRL + C + D”.
```

2024-01-18 09:00 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +### What does `Insufficient fund eligible for coinjoin` mean?
done, also applied the other suggestion with minor tweaks

2024-01-18 09:06 UTC, MarnixCroes commented
> > didn't do all musicbox messages as there are 23
> 
> @Kruwed did write an explanation for most of the music box (I used some of them in my suggestions above), I think we can add them as well. WDYT?
> 
> ```
> Awaiting auto-start of coinjoin
> When you open your wallet, there is a 14 minute delay before the automatic coinjoin process begins. This gives you the chance to ensure your intended transactions are completed and your connection is stable before continuing.
> 
> Awaiting coinjoin
> This message appears if you have specified a long term coinjoin time preference in your settings and mining fees are higher than normal. Automatic coinjoin will resume when transaction fees drop or stabilize. You can change the coinjoin time preference setting to “hours” to register to coinjoin rounds immediately.
> 
> Coinjoin is paused/Coinjoin has stopped
> While you have funds in your wallet below your anonymity score target, you can pause the automatic coinjoin function during the input registration phase.
> 
> Coinjoin successful! Continuing…
> Your privacy progress percentage increases after a successful coinjoin. Once all of your coins reach the anonymity score target defined in the settings, your privacy progress reaches 100% and automatic coinjoin ends.
> 
> Round ended, awaiting next round
> This message results from a coinjoin round ending early due to too many participants. Following this message, coinjoin participants are split into new rounds sorted by amount for greater efficiency.
> 
> Insufficient participants, retrying…
> A minimum of 150 inputs are required to register for a coinjoin transaction to be built. A new 10 minute timeframe to gather the required participants starts when the previous one ends.
> 
> Coinjoin in progress
> Signing the coinjoin transaction occurs during this phase. Pausing is not allowed at this point because it would disrupt the round for the other participants. Avoid disconnecting or closing your wallet during this stage, as it will cause your coins to be temporarily banned from participating in future coinjoin rounds.
> 
> Awaiting other participants
> During this phase, inputs are registered privately with the coinjoin coordinator. You can view the coins that are selected for coinjoin through the UTXOs screen with the keyboard shortcut “CTRL + C + D”.
> 
> Awaiting the blame round
> If another participant fails to sign the coinjoin transaction, this message briefly appears before a new coinjoin round is attempted with the responsive participants from the previous round.
> 
> Coinjoin may be uneconomical. Add more funds or press ‘Play’ to bypass
> This message is displayed while your wallet balance is below the auto-start coinjoin threshold specified in the settings (0.01 BTC by default). This prevents coinjoin from starting automatically when transaction fees would have a high cost relative to your current balance.
> 
> Insufficient funds eligible for coinjoin
> Inputs that have a value below 0.00005000 BTC are not eligible for coinjoin. You can view your input values through the UTXOs screen with the keyboard shortcut “CTRL + C + D”.
> 
> Awaiting confirmed funds
> Only confirmed coins are able to register for coinjoin rounds. A timer icon appears in your transaction history next to unconfirmed transactions. If a non-coinjoin payment is stuck in an unconfirmed state, you can right click the entry in your transaction history to use the “Speedup Transaction” function to add mining fees.
> 
> Some funds are rejected from coinjoining
> If an input has failed to sign for a previous round it registered to, it will be temporarily banned to prevent denial of service attacks. Coinjoin coordinators may also reject funds for risk management purposes. You can view the unban time through the UTXOs screen with the keyboard shortcut “CTRL + C + D”.
> ```

fine by me,
but having a separate FAQ for each one is overkill imo

maybe just 
```
### Other music box messages

#### Awaiting auto-start of coinjoin
When you open your wallet, there is a 14 minute delay before the automatic coinjoin process begins. This gives you the chance to ensure your intended transactions are completed and your connection is stable before continuing.

#### Awaiting coinjoin
This message appears if you have specified a long term coinjoin time preference in your settings and mining fees are higher than normal. Automatic coinjoin will resume when transaction fees drop or stabilize. You can change the coinjoin time preference setting to “hours” to register to coinjoin rounds immediately.

...

```

2024-01-19 14:37 UTC, Kruwed commented
ACK.

2024-01-19 16:28 UTC, yahiheb approved these changes
LGTM.

We can add more music box messages later on if necessary.

2024-01-19 16:28 UTC, merged