FAQUse: create Buy Anything Button FAQ's
zkSNACKs/WasabiDoc pull request #1655
Opened 2024-01-22 13:41 UTC by MarnixCroes

Could wait with adding until BAB is merged to master, and it is for sure in next release
or add it now already, as latest release contains it and the plan is to merge to master

2024-01-23 02:12 UTC, yahiheb requested changes
> or add it now already, as latest release contains it and the plan is to merge to master

ACK

2024-01-23 02:12 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The Buy Anything Button does not compromise Wasabi Wallet wallet's privacy.
```suggestion
The Buy Anything Button does not compromise your wallet's privacy.
```

2024-01-23 02:12 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Once Shopinbit has received the bitcoin on the address with a confirmation, they will start processing the order.
```suggestion
Once ShopinBit has received the bitcoin on the address with a confirmation, they will start processing the order.
```

2024-01-23 02:12 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +However, when using the Buy Anything Button and when having provided some personal details like e-mail and shipping address for the order, then Shopinbit is aware of these, the same as when ordering
```suggestion
However, when using the Buy Anything Button and when having provided some personal details like e-mail and shipping address for the order, then ShopinBit is aware of these, the same as when ordering directly from them or any other merchant.
```

2024-01-23 02:12 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +But of course, make sure to use private coins when sending them (/anyone) your bitcoin!
```suggestion
But of course, make sure to use private coins when sending them/anyone your bitcoin!
```

2024-01-23 09:01 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +The Buy Anything Button does not compromise Wasabi Wallet wallet's privacy.
applied the suggestions, also made other minor improvements and typo fix

2024-01-23 09:22 UTC, yahiheb requested changes

2024-01-23 09:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +When clicking on the Buy Anything Button, the user talks with ShopinBit over a new Tor identity (unless Tor is disabled in the Settings).
```suggestion
When clicking on the Buy Anything Button, the user communicates with ShopinBit over a new Tor identity (unless Tor is disabled in the Settings).
```

2024-01-23 09:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +However, when using the Buy Anything Button and when having provided some personal details like e-mail and shipping address for the order, then ShopinBit is aware of these, the same as when ordering
```suggestion
However, when providing some personal details like e-mail and shipping address for the order, ShopinBit is aware of these, the same as when ordering directly from them or any other merchant.
```

2024-01-23 09:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Some services may or may not be available depending on the jurisdiction you're ordering for.
```suggestion
Some services may or may not be available depending on the jurisdiction you're ordering to.
```

2024-01-23 09:23 UTC, yahiheb commented
@Kruwed Can you review this?

2024-01-25 13:59 UTC, Kruwed requested changes

2024-01-26 07:17 UTC, MarnixCroes commented
thanks @Kruwed, I applied the suggestions

2024-01-26 07:18 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +Some services may or may not be available depending on the jurisdiction you're ordering for.
I made this _depending on the jurisdiction_

2024-01-31 23:16 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +You wallet information is never connected to the information used for ordering something.
@MarnixCroes This PR is waiting for this typo fix so it can be merged.

2024-02-01 08:13 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +You wallet information is never connected to the information used for ordering something.
I forgot about this one
done

2024-02-01 09:27 UTC, yahiheb approved these changes

2024-02-01 09:27 UTC, merged