create WCLI doc
zkSNACKs/WasabiDoc pull request #1657
Opened 2024-01-24 10:14 UTC by MarnixCroes

closes https://github.com/zkSNACKs/WasabiDoc/issues/1562

added 715cb0451f1394e89e87d2a6659ab726e63d22ff, updates a link which gives a redirect

2024-01-25 14:26 UTC, yahiheb requested changes

2024-01-26 07:40 UTC, MarnixCroes commented on docs/.vuepress/config.ts
> +                    "/using-wasabi/WCLI.md",
done

2024-01-26 07:40 UTC, MarnixCroes commented on docs/using-wasabi/WCLI.md
> +
removed

2024-01-26 07:42 UTC, MarnixCroes commented on docs/using-wasabi/WCLI.md
> +$ ./wcli.sh command
you mean it's the first time you try the wcli and it doesn't work for you on win?
it's work on Linux.

2024-01-26 14:33 UTC, lontivero commented
Wait wait no. The `wcli` is a script for devs only and the idea is to make things a little bit easier for us to interact with the json rpc server. This is not something for others to know about, it is so so low quality, so buggy and so shitty that it could harm our reputation if people start using it. Also, given they will find hundred million issues they will report those problems for us to solve them when we really don't want to do anything with that script. Please don't document it, keep it unknown and unpublished.

2024-01-26 15:07 UTC, yahiheb commented on docs/using-wasabi/WCLI.md
> +$ ./wcli.sh command
Yes it doesn't work for me on win.

2024-01-26 15:07 UTC, closed without merging