Expose RPC as onion service
zkSNACKs/WasabiDoc pull request #1667
Opened 2024-01-30 14:20 UTC by MarnixCroes

2024-01-30 15:01 UTC, lontivero commented on docs/using-wasabi/RPC.md
> +You then need to specify them in the config file or add them as command line switches.
or var envs

2024-01-30 15:02 UTC, lontivero submitted a review, later dismissed

2024-01-30 16:40 UTC, MaxHillebrand approved these changes

2024-02-29 16:07 UTC, yahiheb requested changes

2024-02-29 16:07 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +The RPC Server can be exposed as an onion service by using the _rpconionenabled=true_ [start up parameter](/using-wasabi/StartupParameters.md) or environment variable.
```suggestion
The RPC Server can be exposed as an onion service by using the _rpconionenabled=true_ [start up parameter](/using-wasabi/StartupParameters.md) or environment variables.
```

2024-02-29 16:07 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +- _RPCOnionEnabled_ is only available as command line switch (start up parameter) and environment variable, it is not available in the config file.
```suggestion
- _RPCOnionEnabled_ is only available as a command line switch (start up parameter) and an environment variable, it is not available in the config file.
```

2024-03-04 18:41 UTC, yahiheb reviewed
LGTM

Fix the conflicts to merge this.

2024-03-04 18:41 UTC, yahiheb commented on docs/using-wasabi/RPC.md
> +- _Tor_ needs to be enabled
```suggestion
- _Tor_ needs to be enabled.
```

2024-03-04 20:05 UTC, yahiheb approved these changes
LGTM

2024-03-04 20:05 UTC, merged