glossary: safety coinjoin
zkSNACKs/WasabiDoc pull request #1671
Opened 2024-02-16 10:34 UTC by MarnixCroes

https://github.com/zkSNACKs/WalletWasabi/pull/10885

adding it here in the gloss is enough I think

could also add something to the FAQ about this concept: _I did a coinjoin and all my coins are above AS target, but my privacy privacy progress is 75%?_

2024-02-16 10:35 UTC, MarnixCroes commented
friendly ping @kruwed

2024-02-27 04:27 UTC, Kruwed requested changes
Looks good, added a few clarifications.

2024-02-27 04:27 UTC, Kruwed commented on docs/glossary/Glossary-PrivacyWasabi.md
> +Safety coinjoin is a concept to do an extra coinjoin when the user registered only _anonymity score_ 1 (non-private) coins.
```suggestion
Safety coinjoin is a concept for doing extra coinjoins after a user registers only _anonymity score_ 1 (non-private) coins in their first round.
```

2024-02-27 04:27 UTC, Kruwed commented on docs/glossary/Glossary-PrivacyWasabi.md
> +This got added in Wasabi [2.0.6 version](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.6) for people who generate a new wallet -> receive a coin -> do one coinjoin -> send all the money
```suggestion
This was added in Wasabi [2.0.6 version](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v2.0.6) to increase privacy for people who generate a new wallet -> receive a coin -> do one coinjoin -> send all the money out.
```

2024-02-27 04:27 UTC, Kruwed commented on docs/glossary/Glossary-PrivacyWasabi.md
> +It aims to prevent possible privacy leaks to dedicated outside observers who do analysis on the amount going in and the amount going out (consolidated) minus fees.
```suggestion
It aims to prevent targeted analysis that compares the value of consolidated coinjoin outputs with the value of one of the coinjoin's inputs.
```

2024-02-27 08:52 UTC, MarnixCroes commented on docs/glossary/Glossary-PrivacyWasabi.md
> +Safety coinjoin is a concept to do an extra coinjoin when the user registered only _anonymity score_ 1 (non-private) coins.
done, except that I kept coinjoin singular.
_an extra coinjoin_, instead of _extra coinjoins_

2024-02-29 15:49 UTC, yahiheb approved these changes

2024-02-29 15:49 UTC, merged