clarify/mention min input count for fresh and blame round
zkSNACKs/WasabiDoc pull request #1682
Opened 2024-03-08 13:24 UTC by MarnixCroes

2024-03-08 13:24 UTC, MarnixCroes commented
friendly ping @turbolay

2024-03-08 13:27 UTC, MaxHillebrand submitted a review, later dismissed

2024-03-08 13:52 UTC, MarnixCroes commented
> Friendly ACK
> 
> BTW, it would be better to use variables for this intstead of hard coded values, to avoid having to track down everything if we change them

done

2024-03-08 14:31 UTC, kristapsk approved these changes

2024-03-08 14:58 UTC, yahiheb requested changes
Min input is mentioned here also, update it:

https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#what-is-happening-in-the-input-registration-phase

Should we also add a variable for the max input count?

2024-03-08 14:58 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The input registration phase ends when either: the number of registered inputs reaches the maximum, or when the time elapsed and the minimum number of inputs (${minInputCountFreshRound}) is satisfied
There is an input registration phase for blame rounds as well.

I would first add this under L78:
`(${minInputCountFreshRound}) for fresh rounds or (${minInputCountBlameRound}) for blame rounds.`

then change this to:

```suggestion
The input registration phase ends when either: the number of registered inputs reaches the maximum, or when the time elapsed and the minimum number of inputs is satisfied, ${minInputCountFreshRound} or ${minInputCountBlameRound}.
```

2024-03-08 15:38 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The input registration phase ends when either: the number of registered inputs reaches the maximum, or when the time elapsed and the minimum number of inputs (${minInputCountFreshRound}) is satisfied
Is there anything wrong in the above suggestion?
It just describes accurately what happens/could happen in the input registration phase.

2024-03-08 16:59 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The input registration phase ends when either: the number of registered inputs reaches the maximum, or when the time elapsed and the minimum number of inputs (${minInputCountFreshRound}) is satisfied
A blame round is not a phase by itself required for a successful coinjoin, it is just a coinjoin round with all phases (fallback mechanism).

The suggestion doesn't break the flow and there is nothing saying that this step-by-step is specific for fresh rounds.
I would rather be precise and accurate when describing these phases specially with blame rounds given that many fresh rounds fail.

2024-03-09 21:07 UTC, yahiheb approved these changes

2024-03-09 21:08 UTC, merged