Update WasabiSetupVM.md
zkSNACKs/WasabiDoc pull request #1692
Opened 2024-03-21 10:23 UTC by sigit-io

Some documentation suggestions following a (successful) Qubes install

2024-03-21 11:18 UTC, yahiheb approved these changes
LGTM

2024-03-21 12:50 UTC, MaxHillebrand submitted a review, later dismissed
Thanks for the contribution!

2024-03-21 13:12 UTC, MarnixCroes reviewed
thank you for taking the time to update this

2024-03-21 16:17 UTC, yahiheb requested changes

2024-03-21 16:17 UTC, yahiheb commented on docs/using-wasabi/WasabiSetupVM.md
> +To make this persistent, add `DOTNET_CLI_TELEMETRY_OPTOUT=1` to the `/etc/environment` file.
```suggestion

To make this persistent, add `DOTNET_CLI_TELEMETRY_OPTOUT=1` to the `/etc/environment` file. 
```

2024-03-21 16:17 UTC, yahiheb commented on docs/using-wasabi/WasabiSetupVM.md
> +Ensure the VM has at least 5GB of disk available for the upcoming build (default is 2gb)
```suggestion
Ensure the VM has at least 5GB of disk available for the upcoming build (default is 2gb).
```

2024-03-21 16:18 UTC, yahiheb approved these changes

2024-03-22 15:20 UTC, MarnixCroes approved these changes
ACK

2024-03-22 15:20 UTC, MarnixCroes commented
thanks @sigit-io

2024-03-22 15:54 UTC, merged