Optimize SEO for images (alt + title tags)
zkSNACKs/WasabiDoc pull request #932
Opened 2020-09-01 08:38 UTC by RiccardoMasutti

This PR adds `alt` and `title` tags to images for SEO.

2020-09-01 10:19 UTC, MaxHillebrand commented
I don't know.
Will merge when there is consensus and it is merged in `/WalletWasabi/`.

2020-09-01 10:21 UTC, RiccardoMasutti commented
> I don't know.
> Will merge when there is consensus and it is merged in `/WalletWasabi/`.

It actually has nothing to do with WalletWasabi repo, the images have already been optimized properly there.

Here, however, the basic SEO tags are missing.

2020-09-01 10:22 UTC, MaxHillebrand commented
Oh, sorry, I got confused and thought I was commenting on #933.
---
concept ACK, this is also useful while editing the file, as now the text shows what the picture is about.

2020-09-01 10:24 UTC, MaxHillebrand commented
please update https://github.com/zkSNACKs/WasabiDoc#embedding-images in this PR.

2020-09-01 10:25 UTC, MaxHillebrand commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet Observers label](/ReceiveLabelingRequired.png "Wasabi Wallet Observers label")
there are inconsistencies with capitalization - how should this be handled?

afaik, in a title, most words are capitalized [other than `the` etc].

2020-09-01 10:32 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet Observers label](/ReceiveLabelingRequired.png "Wasabi Wallet Observers label")
In any case, the `title` tag is something not visible to the end user but only to Google crawler/spider. The alt tag instead is shown only if the image is not loaded.

2020-09-01 10:34 UTC, MaxHillebrand commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet white theme](/WhiteMode.png "Wasabi Wallet white theme")
is it a SEO problem that the title is different to the file name?

2020-09-01 10:36 UTC, MaxHillebrand commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet Observers label](/ReceiveLabelingRequired.png "Wasabi Wallet Observers label")
I see. 
still, can you please update the PR and have for example `observers` lower case?

iirc, the name of the tabs, like `Send` tab, is capitalized in the docs.

2020-09-01 11:42 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet white theme](/WhiteMode.png "Wasabi Wallet white theme")
No it's not.

2020-09-01 19:22 UTC, yahiheb requested changes

2020-09-01 19:22 UTC, yahiheb commented on docs/using-wasabi/InstallPackage.md
> +![Operative systems supported by Wasabi Wallet](/DownloadAll.png "Operative systems supported by Wasabi Wallet")
```suggestion
![Operating systems supported by Wasabi Wallet](/DownloadAll.png "Operating systems supported by Wasabi Wallet")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/using-wasabi/InstallPackage.md
> +![Wasabi Wallet Windows download](/DownloadWindows.png "Wasabi Wallet Windows download")
```suggestion
![Download Wasabi Wallet for Windows](/DownloadWindows.png "Download Wasabi Wallet for Windows")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/using-wasabi/InstallPackage.md
> +![Wasabi Wallet Debian Download](/DownloadDeb.png "Wasabi Wallet Debian download")
```suggestion
![Download Wasabi Wallet for Debian](/DownloadDeb.png "Download Wasabi Wallet for Debian")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/using-wasabi/InstallPackage.md
> +![Wasabi Wallet Linux download](/DownloadTar.png "Wasabi Wallet Linux download")
```suggestion
![Download Wasabi Wallet for Linux](/DownloadTar.png "Download Wasabi Wallet for Linux")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/using-wasabi/InstallPackage.md
> +![Wasabi Wallet macOS download](/DownloadMac.png "Wasabi Wallet macOS download")
```suggestion
![Download Wasabi Wallet for macOS](/DownloadMac.png "Download Wasabi Wallet for macOS")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet minimum mining fees](/SendNoFee.png "Wasabi Wallet minimum mining fees")
```suggestion
![Wasabi Wallet minimum mining fee](/SendNoFee.png "Wasabi Wallet minimum mining fee")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet Custom Change settings](/SettingsCustomChange.png "Wasabi Wallet Custom Change settings")
```suggestion
![Wasabi Wallet custom change address setting](/SettingsCustomChange.png "Wasabi Wallet custom change address setting")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/using-wasabi/Send.md
> +![Wasabi Wallet set custom change address](/SendCustomChange.png "Wasabi Wallet set custom change address")
```suggestion
![Set Custom Change address in Wasabi Wallet](/SendCustomChange.png "Set Custom Change address in Wasabi Wallet")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet seed recovery words](/WalletManagerRecoveryWords.png "Wasabi Wallet seed recovery words")
```suggestion
![Wasabi Wallet recovery words](/WalletManagerRecoveryWords.png "Wasabi Wallet recovery words")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet seed recovery words](/WalletManagerRecoveryWords.png "Wasabi Wallet seed recovery words")
```suggestion
![Wasabi Wallet recovery words](/WalletManagerRecoveryWords.png "Wasabi Wallet recovery words")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/using-wasabi/WalletGeneration.md
> +![Wasabi Wallet seed recovery words](/WalletManagerRecoveryWords.png "Wasabi Wallet seed recovery words")
```suggestion
![Wasabi Wallet recovery words](/WalletManagerRecoveryWords.png "Wasabi Wallet recovery words")
```

2020-09-01 19:22 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +The larger UTXO will (most probably) have a colored shield (<img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonimity set" title="Wasabi Wallet yellow shield anonimity set" class="shiel
```suggestion
The larger UTXO will (most probably) have a colored shield (<img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonymity set" title="Wasabi Wallet yellow shield anonymity set" class="shield" />, <img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonymity set" title="Wasabi Wallet green shield anonymity set" class="shield" /> or <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" /> based on your [Privacy Level Settings](/FAQ/FAQ-UseWasabi.md#how-can-i-change-the-anonset-target)) that indicates the level of the anonymity set achieved in that CoinJoin round.
```

2020-09-01 19:22 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +It is advisable to limit the recombining of <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonimity set" title="Wasabi Wallet green checkmark shield anonimity set" class="
```suggestion
It is advisable to limit the recombining of <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonimity set" title="Wasabi Wallet green checkmark shield anonimity set" class="shield" /> <img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonimity set" title="Wasabi Wallet green shield anonimity set" class="shield" /> <img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonimity set" title="Wasabi Wallet yellow shield anonimity set" class="shield" /> mixed coins because it can only decrease the privacy of these coins.
```

2020-09-01 19:22 UTC, yahiheb commented on docs/using-wasabi/Send.md
>  Wasabi shows you three levels of anonymity sets: <img src="/ShieldYellow.png" alt="yellow" class="shield" />, <img src="/ShieldGreen.png" alt="green" class="shield" /> and <img src="/ShieldCheckmark.
```suggestion
Wasabi shows you three levels of anonymity sets: <img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonimity set" title="Wasabi Wallet yellow shield anonimity set" class="shield" />, <img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonimity set" title="Wasabi Wallet green shield anonimity set" class="shield" /> and <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonimity set" title="Wasabi Wallet green checkmark shield anonimity set" class="shield" />.
```

2020-09-01 21:40 UTC, yahiheb requested changes

2020-09-01 21:40 UTC, yahiheb commented on docs/building-wasabi/TechnicalOverview.md
> +![Wasabi Wallet anonimity set](/SendAnonset.png "Wasabi Wallet anonimity set")
```suggestion
![Wasabi Wallet anonymity set](/SendAnonset.png "Wasabi Wallet anonymity set")
```

2020-09-01 21:40 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +<img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonimity set" title="Wasabi Wallet red shield anonimity set" class="shield" />
```suggestion
<img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" />,
<img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonymity set" title="Wasabi Wallet green shield anonymity set" class="shield" />,
<img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonymity set" title="Wasabi Wallet yellow shield anonymity set" class="shield" /> and
<img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" />
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +For example, let's assume that you choose a <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonimity set" title="Wasabi Wallet red shield anonimity set" class="shield" /> 1 anonymity set UTX
```suggestion
For example, let's assume that you choose a <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" /> 1 anonymity set UTXO worth 2 bitcoins.
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +Let's say that you have a KYC <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonimity set" title="Wasabi Wallet red shield anonimity set" class="shield" /> `anonymity set 1` UTXO, and you r
```suggestion
Let's say that you have a KYC <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" /> `anonymity set 1` UTXO, and you register it for a CoinJoin round.
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +The remaining UTXO(s) will have either a <img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonimity set" title="Wasabi Wallet yellow shield anonimity set" class="shield" />, <img src="/S
```suggestion
One of those will be the change leftover from the round, and it will retain the <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" /> `anonymity set 1` designation.
The remaining UTXO(s) will have either a <img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonymity set" title="Wasabi Wallet yellow shield anonymity set" class="shield" />, <img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonymity set" title="Wasabi Wallet green shield anonymity set" class="shield" /> or <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" /> shield.
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +The other, much smaller UTXO will be the amount (change) that was left over, and it will have a <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonimity set" title="Wasabi Wallet red shield
```suggestion
The other, much smaller UTXO will be the amount (change) that was left over, and it will have a <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" /> indicating an anonymity set of `1` as it does not have the equal value denomination of the CoinJoin.
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +Since your identity was already known in the <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonimity set" title="Wasabi Wallet red shield anonimity set" class="shield" /> `anonymity set 1`,
```suggestion
The small UTXO that is leftover/change from a CoinJoin round is clearly tied to your KYC input UTXO, but the <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" /> UTXO is not.
If afterwards, you combine the <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" /> UTXO with a <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" /> UTXO in a single transaction, then it is clear that both came from the same owner.
Since your identity was already known in the <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" /> `anonymity set 1`, it can now be linked to your coinjoined UTXO.
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/ChangeCoins.md
> +When you take a <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonimity set" title="Wasabi Wallet green checkmark shield anonimity set" class="shield" /> 100 anonset UTXO,
```suggestion
When you take a <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" /> 100 anonymity set UTXO, and you CoinJoin it again in a new 100 participant round, then you receive one <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" /> UTXO with combined anonymity set of 200, and one <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" /> leftover/change UTXO with the same anonymity set as the input UTXO: 100.
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +![Wasabi Wallet green checkmark anonimity set target](/CoinJoinAnonsetTargetCheck.png "Wasabi Wallet green checkmark anonimity set target")
```suggestion
![Wasabi Wallet yellow anonymity set target](/CoinJoinAnonsetTargetYellow.png "Wasabi Wallet yellow anonymity set target")
![Wasabi Wallet green anonymity set target](/CoinJoinAnonsetTargetGreen.png "Wasabi Wallet green anonymity set target")
![Wasabi Wallet green checkmark anonymity set target](/CoinJoinAnonsetTargetCheck.png "Wasabi Wallet green checkmark anonymity set target")
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/ColdWasabi.md
> +![Wasabi Wallet anonimity set levels](/SettingsAnonLevels.png "Wasabi Wallet anonimity set levels")
```suggestion
![Wasabi Wallet anonymity set levels](/SettingsAnonLevels.png "Wasabi Wallet anonymity set levels")
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/Send.md
> +Wasabi shows you three levels of anonymity sets: <img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonimity set" title="Wasabi Wallet yellow shield anonimity set" class="shield" />, <img
```suggestion
Wasabi shows you three levels of anonymity sets: <img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonymity set" title="Wasabi Wallet yellow shield anonymity set" class="shield" />, <img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonymity set" title="Wasabi Wallet green shield anonymity set" class="shield" /> and <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" />.
```

2020-09-01 21:40 UTC, yahiheb commented on docs/using-wasabi/Send.md
> +![Wasabi Wallet anonimity set](/SendAnonset.png "Wasabi Wallet anonimity set")
```suggestion
![Wasabi Wallet anonymity set](/SendAnonset.png "Wasabi Wallet anonymity set")
```

2020-09-01 21:40 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
>  ### Shield (or anonset shield)
```suggestion
### Shield (or anonymity set shield)
```

2020-09-01 22:07 UTC, yahiheb requested changes

2020-09-01 22:07 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The coin will have an anonymity set > 1, and typically will have a <img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonimity set" title="Wasabi Wallet green shield anonimity set" class="s
```suggestion
The coin will have an anonymity set > 1, and typically will have a <img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonymity set" title="Wasabi Wallet green shield anonymity set" class="shield" /> shield.
```

2020-09-01 22:07 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +This change is marked <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonimity set" title="Wasabi Wallet red shield anonimity set" class="shield" /> and has an anonymity set = 1 (with a coup
```suggestion
This change is marked <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" /> and has an anonymity set = 1 (with a couple of small exceptions regarding remixing).
```

2020-09-01 22:07 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The anonymity set info (number) is tied to your wallet that you used to CoinJoin, if you send a mixed coin to another Wasabi Wallet of yours (hardware wallet or normal wallet) it will have an anonymi
```suggestion
The anonymity set info (number) is tied to your wallet that you used to CoinJoin, if you send a mixed coin to another Wasabi Wallet of yours (hardware wallet or normal wallet) it will have an anonymity set 1 <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" /> because this wallet doesn't know that the coin was coinjoined.
```

2020-09-01 22:07 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +<img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonimity set" title="Wasabi Wallet green checkmark shield anonimity set" class="shield" />
```suggestion
<img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonymity set" title="Wasabi Wallet yellow shield anonymity set" class="shield" />,
<img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonymity set" title="Wasabi Wallet green shield anonymity set" class="shield" /> and
<img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" />
```

2020-09-01 22:07 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +It is advisable to limit the recombining of <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonimity set" title="Wasabi Wallet green checkmark shield anonimity set" class="
```suggestion
It is advisable to limit the recombining of <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" /> <img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonymity set" title="Wasabi Wallet green shield anonymity set" class="shield" /> <img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonymity set" title="Wasabi Wallet yellow shield anonymity set" class="shield" /> mixed coins because it can only decrease the privacy of these coins.
```

2020-09-01 22:07 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +Never consolidate <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonimity set" title="Wasabi Wallet red shield anonimity set" class="shield" /> unmixed coins with <img src="/ShieldCheckmark
```suggestion
Never consolidate <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" /> unmixed coins with <img src="/ShieldCheckmark.png" alt="Wasabi Wallet green checkmark shield anonymity set" title="Wasabi Wallet green checkmark shield anonymity set" class="shield" /> <img src="/ShieldGreen.png" alt="Wasabi Wallet green shield anonymity set" title="Wasabi Wallet green shield anonymity set" class="shield" /> <img src="/ShieldYellow.png" alt="Wasabi Wallet yellow shield anonymity set" title="Wasabi Wallet yellow shield anonymity set" class="shield" /> mixed coins, as this negates the privacy benefits of the CoinJoin.
```

2020-09-01 22:07 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +The most problematic type of change is what has `anonymity set 1` <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonimity set" title="Wasabi Wallet red shield anonimity set" class="shield"
```suggestion
The most problematic type of change is what has `anonymity set 1` <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="Wasabi Wallet red shield anonymity set" class="shield" />.
```

2020-09-01 22:14 UTC, yahiheb requested changes

2020-09-01 22:14 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +![Wasabi Wallet Observers label](/ReceiveLabelingRequired.png "Wasabi Wallet Observers label")
```suggestion
![Wasabi Wallet known by label](/ReceiveLabelingRequired.png "Wasabi Wallet known by label")
```

2020-09-01 22:14 UTC, yahiheb commented on docs/building-wasabi/TechnicalOverview.md
> +![Wasabi Wallet Observers label](/ReceiveLabelingRequired.png "Wasabi Wallet Observers label")
```suggestion
![Wasabi Wallet known by label](/ReceiveLabelingRequired.png "Wasabi Wallet known by label")
```

2020-09-01 22:14 UTC, yahiheb commented on docs/using-wasabi/Receive.md
> +![Set Observers in Wasabi Wallet](/ReceiveLabelingRequired.png "Set Observers in Wasabi Wallet")
```suggestion
![Set known by in Wasabi Wallet](/ReceiveLabelingRequired.png "Set known by in Wasabi Wallet")
```

2020-09-01 22:14 UTC, yahiheb commented on docs/using-wasabi/Receive.md
> +![Set Observers in Wasabi Wallet](/ReceiveLabelingRequired.png "Set Observers in Wasabi Wallet")
```suggestion
![Set known by in Wasabi Wallet](/ReceiveLabelingRequired.png "Set known by in Wasabi Wallet")
```

2020-09-01 22:16 UTC, yahiheb commented
I think this is now ready for merge.
`ReceiveLabelingRequired.png` should be updated because we changed `Observers` to `Known by`

2020-09-02 09:50 UTC, MaxHillebrand requested changes
@RiccardoMasutti please update README line 88, and resolve the conflicts.

Then it's ready to merge.

2020-09-02 10:01 UTC, RiccardoMasutti commented
@yahiheb I see that you modified/removed multiple alt and title tags. I inserted those for SEO reasons. Let's merge this PR for now, but I'll need I will take a look again in the future to reevaluate how to optimize keywords

2020-09-02 10:10 UTC, MaxHillebrand commented
@RiccardoMasutti thanks for adding the README. can you please still resolve the conflicts?

I'll merge then.

2020-09-02 10:22 UTC, MaxHillebrand approved these changes
ACK 58886ef

@yahiheb ACKed d7a5e6a.

Merging

Thanks @RiccardoMasutti

2020-09-02 10:22 UTC, merged

2020-09-02 14:13 UTC, yahiheb commented
> @yahiheb I see that you modified/removed multiple alt and title tags. I inserted those for SEO reasons. Let's merge this PR for now, it is already good. But in the future I will take a look again to evaluate if optimizing them again or not

Which ones did I remove? can you point them out?

2020-09-02 15:15 UTC, RiccardoMasutti commented
> > @yahiheb I see that you modified/removed multiple alt and title tags. I inserted those for SEO reasons. Let's merge this PR for now, it is already good. But in the future I will take a look again to evaluate if optimizing them again or not
> 
> Which ones did I remove? can you point them out?

Sorry I meant modified/removed multiple *keywords* inside alt and title tags. For example `Wasabi Wallet seed recovery words` -> `Wasabi Wallet recovery words`

2020-09-02 17:59 UTC, MaxHillebrand commented
seed is not the correct word here. however, it is commonly used to describe the recovery words.

I'm not sure if it's good practice to have factually wrong statements and prioritize SEO...