Update FAQ-Introduction.md
zkSNACKs/WasabiDoc pull request #940
Opened 2020-09-14 13:37 UTC by Trxlz

2020-09-14 13:48 UTC, MaxHillebrand submitted a review, later dismissed
that's a great PR, thanks @Trxlz!

ACK

2020-09-14 14:07 UTC, RiccardoMasutti requested changes

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +Coinjoin is a mechanism by which multiple participants combine their coins (or UTXOs, to be more precise) into one large transaction with multiple inputs and multiple outputs.
```suggestion
CoinJoin is a mechanism by which multiple participants combine their coins (or UTXOs, to be more precise) into one large transaction with multiple inputs and multiple outputs.
```

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> + Since Wasabi's CoinJoin implementation is trustless by design,there is no need for participants to trust each other or a third party.
```suggestion
 Since Wasabi's CoinJoin implementation is trustless by design, there is no need for participants to trust each other or a third party.
```

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +The Wasabi server merely coordinates the process of combining  each participant's input into one single transaction, but the Wasabi Wallet can neither steal your coins, nor figure out which outputs b
```suggestion
The Wasabi server merely coordinates the process of combining each participant's input into one single transaction, but the Wasabi Wallet can neither steal your coins, nor figure out which outputs belong to which inputs (look up “[Chaumian CoinJoin](/using-wasabi/CoinJoin.md)” if you want to know more).
```

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +For example, if you send a mixed coin to an already used address, then anyone can see that both coins are controlled by the same entity. More importantly, anyone who knows that the address belongs to
```suggestion
For example, if you send a mixed coin to an already used address, then anyone can see that both coins are controlled by the same entity.
More importantly, anyone who knows that the address belongs to you knows that you own that mixed coin.
```

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +For example, if you send a mixed coin to an already used address, then anyone can see that both coins are controlled by the same entity. More importantly, anyone who knows that the address belongs to
Every sentence must start in a new line.

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +Another deanonymizing scenario occurs  when you combine mixed outputs with unmixed ones when sending: a third party will be able to make the connection between them as belonging to the same sender.
```suggestion
Another deanonymizing scenario occurs when you combine mixed outputs with unmixed ones when sending: a third party will be able to make the connection between them as belonging to the same sender.
```

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +[Address reuse](/why-wasabi/AddressReuse.md) compromises  your privacy.
```suggestion
[Address reuse](/why-wasabi/AddressReuse.md) compromises your privacy.
```

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +The worst-case scenario  (through user’s negligence post-mix) may be that the level of your privacy stays the same as before the CoinJoin.
```suggestion
The worst-case scenario (through user’s negligence post-mix) may be that the level of your privacy stays the same as before the CoinJoin.
```

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> + It is difficult to determine a sufficient anonymity set since enough research hasn’t been conducted to provide a definitive answer.
```suggestion
It is difficult to determine a sufficient anonymity set since enough research hasn’t been conducted to provide a definitive answer.
```

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> + It is difficult to determine a sufficient anonymity set since enough research hasn’t been conducted to provide a definitive answer.
@yahiheb what do you think?

2020-09-14 14:07 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +This means that you rely on the [Wasabi backend](https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi.Backend) to provide  valid filters.
```suggestion
This means that you rely on the [Wasabi backend](https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi.Backend) to provide valid filters.
```

2020-09-14 14:14 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +It is difficult to determine a sufficient anonymity set since enough research hasn’t been conducted to provide a definitive answer.
@yahiheb what do you think? Maybe we should explain that the right anonimity set depends on threat model

2020-09-14 18:56 UTC, yahiheb requested changes

2020-09-14 18:56 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +Wasabi is used by individuals to receive and spend make everyday payments, to manage their hardware wallet long term hodlings, and to CoinJoin their sats for added privacy.
Is this what you meant?
```suggestion
Wasabi is used by individuals to make everyday payments, to manage their hardware wallet long term hodlings, and to CoinJoin their sats for added privacy.
```

2020-09-14 18:56 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +While kids may use Wasabi to stack the sats gifted by grandma, and they learn the importance of hodling.
```suggestion
While kids may use Wasabi to stack the sats gifted by grandma, and learn the importance of hodling.
```

2020-09-14 18:56 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +### Should I trust Wasabi with my coins?
Probably we shouldn't change this unless really necessary, because we might have passed this link https://docs.wasabiwallet.io/FAQ/FAQ-Introduction.html#do-i-need-to-trust-wasabi-with-my-coins somewhere and it won't work if we change it.

2020-09-14 18:56 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +However,the rough consensus among many privacy researchers is that an anonymity set above 50 could be considered sufficient.
```suggestion
However, the rough consensus among many privacy researchers is that an anonymity set above 50 could be considered sufficient.
```

2020-09-14 18:56 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +It is difficult to determine a sufficient anonymity set since enough research hasn’t been conducted to provide a definitive answer.
I agree.

2020-09-14 19:19 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-Introduction.md
> +### Should I trust Wasabi with my coins?
Agree.

2020-11-18 12:21 UTC, RiccardoMasutti approved these changes
ACK, waiting for @yahiheb's review

2020-11-18 13:50 UTC, yahiheb requested changes

2020-11-18 13:50 UTC, yahiheb commented on docs/FAQ/FAQ-Introduction.md
> +The right anonimity set depends on your own personal threat model.
```suggestion
The right anonymity set depends on your own personal threat model.
```

2020-11-18 13:51 UTC, yahiheb approved these changes

2020-11-18 13:52 UTC, merged