Add Tor process keep running after closing Wasabi FAQ
zkSNACKs/WasabiDoc pull request #943
Opened 2020-09-17 09:50 UTC by RiccardoMasutti

2020-09-17 13:41 UTC, yahiheb requested changes

2020-09-17 13:41 UTC, yahiheb commented on docs/FAQ/FAQ-GeneralBitcoinPrivacy.md
> +If an user closes Wasabi and then starts it again, he's already connected to Tor and he does not need to build a new Tor circuit.
```suggestion

If n user closes Wasabi and then starts it again, he's already connected to Tor and he does not need to build a new Tor circuit.
```

2020-09-17 13:41 UTC, yahiheb commented on docs/FAQ/FAQ-GeneralBitcoinPrivacy.md
> +That means that the Wasabi startup will be much faster, because the Tor circuit is already estabilished.
```suggestion
This means that the next Wasabi startup will be much faster, because the Tor circuit is already established.
```

2020-09-17 13:41 UTC, yahiheb commented on docs/FAQ/FAQ-GeneralBitcoinPrivacy.md
> +Regarding the privacy, this is done for avoiding time correlations attacks when opening Wasabi Wallet.
```suggestion
Regarding the privacy, this is done to avoid time correlation attacks when using Wasabi Wallet.
```

2020-09-17 13:41 UTC, yahiheb commented on docs/FAQ/FAQ-GeneralBitcoinPrivacy.md
> +
```suggestion
In fact, if a user creates a new Tor circuit every time he opens Wasabi Wallet, he would send a series of information to the Bitcoin network, which could allow a correlation and deanonymization of the user himself.
```

2020-09-17 13:50 UTC, yahiheb requested changes

2020-09-17 13:50 UTC, yahiheb commented on docs/FAQ/FAQ-GeneralBitcoinPrivacy.md
> +This means that the next Wasabi startup will be much faster, because the Tor circuit is already established.
```suggestion
This means that Wasabi's startup will be much faster, because the Tor circuit is already established.
```

2020-09-17 13:52 UTC, yahiheb approved these changes

2020-09-19 09:15 UTC, MaxHillebrand approved these changes
good one - surprised this isn't in the docs yet!

2020-09-19 09:15 UTC, merged