[FAQ] how to change coordinator hidden service
zkSNACKs/WasabiDoc pull request #946
Opened 2020-09-21 14:22 UTC by MaxHillebrand

This adds a quick FAQ about how to change the coordinator onion.

2020-09-21 14:29 UTC, RiccardoMasutti requested changes

2020-09-21 14:29 UTC, RiccardoMasutti commented on docs/FAQ/FAQ-UseWasabi.md
> +Open the `Conf.json`  file through the top menu bar.
```suggestion
Open the `Conf.json` file through the top menu bar.
```

2020-09-21 15:24 UTC, DanGould commented on docs/FAQ/FAQ-UseWasabi.md
> +Open the `Conf.json` file through the top menu bar.
change line to 2. From menu: File/Open/Config File.

`Conf.json` -> `Config.json`

2020-09-21 17:15 UTC, MaxHillebrand commented on docs/FAQ/FAQ-UseWasabi.md
> +Open the `Conf.json` file through the top menu bar.
```suggestion
Open the `Config.json` file through the top menu bar.
```

2020-09-21 17:26 UTC, yahiheb commented
Why should we add this to the docs?

2020-09-22 02:58 UTC, DanGould commented
@yahiheb because it answers a question that is asked frequently

2020-09-22 08:57 UTC, MaxHillebrand commented
@yahiheb because Wasabi =/ zkSNACKs.

although this repository ships a package that by default connects to the zkSNACKs coordinator, there are already and will continue to be other coordinators operated. That's a feature, not a bug!!

 Users can and will connect to different coordinators, so it ought to be explained how to do it properly, so to not mess up.

2020-09-22 09:07 UTC, RiccardoMasutti commented
> @yahiheb because Wasabi =/ zkSNACKs.
> 
> although this repository ships a package that by default connects to the zkSNACKs coordinator, there are already and will continue to be other coordinators operated. That's a feature, not a bug!!
> 
> Users can and will connect to different coordinators, so it ought to be explained how to do it properly, so to not mess up.

I agree on explaining how to change the coordinator variable, but I believe that the lack of liquidity in the current other coordinators can be a privacy issue and I would advise against most users to change it.

2020-09-22 09:09 UTC, MaxHillebrand commented
yes Riccardo, this is a concern, and notice that's the reason why I do not link to the onion of a different coordinator, as this would be a recommendation, and thus carefully ought to be considered.

Nevertheless, changing the coordinator onion, even if it's for your own setup on regtest, is useful information worthy to be in the docs.

2020-09-22 14:09 UTC, yahiheb commented
Yes Wasabi =! zkSNACKs, but the docs are about Wasabi stuff mainly, so why should we add anything not really related to Wasabi?
I mean does Wasabi have any other coordinator that users should manually connect to? AFAIK no, so there is no need for this addition.

> @yahiheb because it answers a question that is asked frequently

But that question is not related to Wasabi.
Don't get me wrong I am all in for chaincase but I don't think we should add this here just because people want to use Wasabi to connect to chaincase's coordinator.

2020-09-22 16:28 UTC, MaxHillebrand commented
> why should we add anything not really related to Wasabi?

Because changing the coordinator is a feature in the Wasabi client.

This is not the zkSNACKs documentation [although it's of course in the zkSNACKs repo, lol], but the Wasabi documentation. And the Wasabi client, is designed in such a way to connect to different than the default coordinator.

imho such a core architecture feature ought to be documented, specifically when there are real use cases for changing it.

> I mean does Wasabi have any other coordinator that users should manually connect to?

Yes, for example the mainchain coordinator of chaincase, and I know several users who connect to it with their Wasabi desktop client.

I think it's a reasonable assumption to see in the future new coordinators with unique round parameters.

2020-11-18 12:13 UTC, RiccardoMasutti commented
@MaxHillebrand @yahiheb What if we add a `:::warning` explaining that by changing the default coordinator, the user expose himself to a series of problems not related to the default coordinator? (eg. low liquidity, less privacy/anonset per round, etc.)

2023-08-23 11:12 UTC, closed without merging