Fix title, description and add h1 in glossary
zkSNACKs/WasabiDoc pull request #948
Opened 2020-09-22 13:53 UTC by RiccardoMasutti

The `<h1>` tag was missing because we used `##` (h2) for the title. I also optimized title and description.
(SEO)

2020-09-22 14:39 UTC, yahiheb requested changes

2020-09-22 14:39 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +  "description": "Explanations of common words regarding Bitcoin privacy. This is the Wasabi documentation, an archive of knowledge about the open-source, non-custodial and privacy-focused Bitcoin wa
```suggestion
  "description": "Explanations of common words regarding Wasabi and Bitcoin privacy. This is the Wasabi documentation, an archive of knowledge about the open-source, non-custodial and privacy-focused Bitcoin wallet for desktop."
```

2020-09-22 14:39 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
>    "title": "Privacy and Wasabi",
```suggestion
  "title": "Wasabi and Bitcoin privacy Glossary",
```

2020-09-22 14:39 UTC, yahiheb commented on docs/glossary/Glossary-GeneralBitcoin.md
> +# Bitcoin Glossary
Why did you remove the #?

2020-09-22 14:39 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +# Privacy and Wasabi Glossary
Why did you remove the #?

2020-09-22 14:40 UTC, yahiheb commented
Don't open new branches in the repo.

2020-09-22 14:44 UTC, RiccardoMasutti commented on docs/glossary/Glossary-PrivacyWasabi.md
> +# Privacy and Wasabi Glossary
Because we need to insert an h1 tag in the page, that's usually the title.

2020-09-22 20:57 UTC, MaxHillebrand approved these changes
~cACK~ 

---

edit, this removes the sidebar menu - that must be fixed!

2020-09-22 23:14 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +# Privacy and Wasabi Glossary
Why do we need that? With this PR we don't have the sub-titles in the side menu.

2023-08-23 07:30 UTC, MarnixCroes commented
There was no consensus here, closing.

2023-08-23 07:30 UTC, closed without merging