Update Why Wasabi
zkSNACKs/WasabiDoc pull request #982
Opened 2021-04-09 11:55 UTC by BTCparadigm

Reading through Docs. Here are some of my nitpicks about the wordings.
Added links to glossary when a weird word is used for the first time. For example "anonset" and "fungibility".
Feel free to throw out and edit anything you don't like or see as necessary.

2021-04-09 23:50 UTC, yahiheb commented
Aren't these changes the same as in #983?

2021-04-10 10:02 UTC, BTCparadigm commented
Yes they are. Closed that one and made a [new PR](#984) just for the README.md changes.

2021-04-10 12:56 UTC, yahiheb requested changes

2021-04-10 12:56 UTC, yahiheb commented on docs/why-wasabi/Coins.md
> +Because Wasabi requires users to label every receiving address, the history of each coin is clear for them at first glance.
For whom?

2021-04-10 12:56 UTC, yahiheb commented on docs/why-wasabi/Coins.md
> +This is why the CoinJoin change has only 1 [anonset](https://docs.wasabiwallet.io/glossary/Glossary-PrivacyWasabi.html) <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="W
Did you mean to add this link: https://docs.wasabiwallet.io/glossary/Glossary-PrivacyWasabi.html#anonymity-set-anonset

2021-04-10 12:56 UTC, yahiheb commented on docs/why-wasabi/LegalConcern.md
> +### Service providers obligations regarding privacy
Why this, it was correct no?

2021-04-10 12:56 UTC, yahiheb commented on docs/why-wasabi/LegalConcern.md
> +By the use of this tool, a custodial service provider can at least start to protect its users financial privacy.
Same as above

2021-04-10 12:56 UTC, yahiheb commented on docs/why-wasabi/LegalConcern.md
> +## Privacy perspective from the companies point of view
Same as above

2021-04-10 12:56 UTC, yahiheb commented on docs/why-wasabi/TransactionSurveillanceCompanies.md
> +Surveillance companies have been known to sybil- and eclipse attack the bitcoin network, and specific nodes, in order to try to find the source IP addresses of unconfirmed transactions.
```suggestion
Surveillance companies have been known to sybil and eclipse attack the bitcoin network, and specific nodes, in order to try to find the source IP addresses of unconfirmed transactions.
```

2021-04-10 12:56 UTC, yahiheb commented on docs/why-wasabi/TransactionSurveillanceCompanies.md
> +Without privacy, malicious parties have more ability to steal your identity, snatch your packages from your doorstep, or impersonate businesses you transact with. They also know exactly how much to t
```suggestion
Without privacy, malicious parties have more ability to steal your identity, snatch your packages from your doorstep, or impersonate businesses you transact with.
They also know exactly how much to try to scam you for.
```

2021-04-10 12:57 UTC, BTCparadigm commented on docs/why-wasabi/Coins.md
> +Because Wasabi requires users to label every receiving address, the history of each coin is clear for them at first glance.
The point was to clarify for newbies that the label is not visible to outsiders or in the chain, but only for the user.

2021-04-10 13:04 UTC, BTCparadigm commented on docs/why-wasabi/LegalConcern.md
> +### Service providers obligations regarding privacy
Not sure but to me they look weird. I think I only saw that pattern in LegalConcern.md but not in other pages .

2021-04-10 13:05 UTC, BTCparadigm commented on docs/why-wasabi/Coins.md
> +This is why the CoinJoin change has only 1 [anonset](https://docs.wasabiwallet.io/glossary/Glossary-PrivacyWasabi.html) <img src="/ShieldRed.png" alt="Wasabi Wallet red shield anonymity set" title="W
Good catch! Yes!
Fixed.

2021-04-10 13:07 UTC, BTCparadigm commented on docs/why-wasabi/TransactionSurveillanceCompanies.md
> +Surveillance companies have been known to sybil- and eclipse attack the bitcoin network, and specific nodes, in order to try to find the source IP addresses of unconfirmed transactions.
ACK

2021-04-10 13:39 UTC, BTCparadigm commented on docs/why-wasabi/LegalConcern.md
> +### Service providers obligations regarding privacy
I mean, I didn't saw it in other `Why Wasabi` pages. Removed them for consistency and because I don't think the grammar is wrong without them either.

2021-04-10 14:29 UTC, yahiheb commented on docs/why-wasabi/Coins.md
> +Because Wasabi requires users to label every receiving address, the history of each coin is clear for them at first glance.
`For them` doesn't tell me anything, why not say `for the user`?

2021-04-10 14:32 UTC, yahiheb commented on docs/why-wasabi/LegalConcern.md
> +### Service providers obligations regarding privacy
I think it was correct as it was. https://www.thepunctuationguide.com/apostrophe.html#:~:text=The%20general%20rule%20is%20that,ends%20in%20s%20or%20not.&text=The%20possessive%20of%20a%20plural,a%20letter%20other%20than%20s.

2021-04-10 15:05 UTC, BTCparadigm commented on docs/why-wasabi/Coins.md
> +Because Wasabi requires users to label every receiving address, the history of each coin is clear for them at first glance.
Works for me. Fixed.

2021-04-10 15:10 UTC, BTCparadigm commented on docs/why-wasabi/LegalConcern.md
> +### Service providers obligations regarding privacy
Ok. Added all the original signs back. 
Not sure if on purpose but the first 2 are ’ and the last one is '

2021-04-10 15:42 UTC, yahiheb commented on docs/why-wasabi/LegalConcern.md
> +### Service providers obligations regarding privacy
We should use one of them to be consistent, maybe `'`?

2021-04-10 16:07 UTC, BTCparadigm commented on docs/why-wasabi/LegalConcern.md
> +### Service providers obligations regarding privacy
Done

2021-04-10 23:37 UTC, yahiheb approved these changes
LGTM

2021-04-12 09:02 UTC, RiccardoMasutti approved these changes
ACK

2021-04-12 09:02 UTC, merged