Update README.md
zkSNACKs/WasabiDoc pull request #984
Opened 2021-04-10 08:27 UTC by BTCparadigm

Created 2 tables of content. Added a picture, some emojis and a link to Discussions instead of Issues, in WalletWasabi repo.

Separated README.md changes from [other changes](#982), which were combined in #983. 
Closing #983.

2021-04-10 10:57 UTC, MaxHillebrand commented on README.md
> +## VuePress
I think we use `###` because otherwise it does not show up in the left menu bar, but I'm not sure.

2021-04-10 11:03 UTC, yahiheb requested changes

2021-04-10 11:03 UTC, yahiheb commented on README.md
>  ## Build the Documentation Locally
This one should have only one `#`

2021-04-10 11:30 UTC, BTCparadigm commented on README.md
> +## VuePress
Isn't left menu bar only for the website? Does this README.md file show up in [docs](docs.wasabiwallet.io)?

2021-04-10 11:32 UTC, BTCparadigm commented on README.md
> +[![Build Status](https://dev.azure.com/zkSNACKs/WasabiDoc/_apis/build/status/zkSNACKs.WasabiDoc?branchName=master)](https://dev.azure.com/zkSNACKs/WasabiDoc/_build/latest?definitionId=4&branchName=ma
Okay. Was not sure what it's for but decided to move it upwards, like in many other repositories README.md.

2021-04-10 11:32 UTC, MaxHillebrand commented on README.md
> +## VuePress
yes, good point, disregard my above comment.

2021-04-10 11:37 UTC, BTCparadigm commented on README.md
>  ## Build the Documentation Locally
If it has only on `#`, then it's not visible in the table. That's why I decided to use `##`

2021-04-10 12:40 UTC, yahiheb commented on README.md
>  ## Build the Documentation Locally
It is not part of the `Contribute to the Documentation` section.

2021-04-10 13:21 UTC, BTCparadigm commented on README.md
>  ## Build the Documentation Locally
How about this? 

Removes `Build the Documentation Locally` from the lower table.
Moves `Build the Documentation Locally` section (and the subsection) under the lower table for better visibility.

https://github.com/BTCparadigm/WasabiDoc/tree/BTCparadigm-patch-2#readme

2021-04-10 14:34 UTC, yahiheb commented on README.md
>  ## Build the Documentation Locally
IMO it should be as it was before.

2021-04-10 15:17 UTC, BTCparadigm commented on README.md
>  ## Build the Documentation Locally
Done

2021-04-10 15:51 UTC, yahiheb commented on README.md
> -[![Build Status](https://dev.azure.com/zkSNACKs/WasabiDoc/_apis/build/status/zkSNACKs.WasabiDoc?branchName=master)](https://dev.azure.com/zkSNACKs/WasabiDoc/_build/latest?definitionId=4&branchName=ma
I was thinking about this again and maybe we should just add  them back, what do you think?

2021-04-10 16:00 UTC, BTCparadigm commented on README.md
> -[![Build Status](https://dev.azure.com/zkSNACKs/WasabiDoc/_apis/build/status/zkSNACKs.WasabiDoc?branchName=master)](https://dev.azure.com/zkSNACKs/WasabiDoc/_build/latest?definitionId=4&branchName=ma
I don't quite understand what is the function of it, but it doesn't look bad since it says "succeeded" :D

2021-04-10 23:35 UTC, yahiheb commented on README.md
> -[![Build Status](https://dev.azure.com/zkSNACKs/WasabiDoc/_apis/build/status/zkSNACKs.WasabiDoc?branchName=master)](https://dev.azure.com/zkSNACKs/WasabiDoc/_build/latest?definitionId=4&branchName=ma
It is used to indicate the status of the repository after each merge/commit.
I am not sure where it should be, maybe under the logo?

2021-04-11 09:02 UTC, BTCparadigm commented on README.md
> -[![Build Status](https://dev.azure.com/zkSNACKs/WasabiDoc/_apis/build/status/zkSNACKs.WasabiDoc?branchName=master)](https://dev.azure.com/zkSNACKs/WasabiDoc/_build/latest?definitionId=4&branchName=ma
IMHO it should be under the explanation of what is this repository for. So around row 19. 

I tried to mimic [WalletWasabi](https://github.com/zkSNACKs/WalletWasabi#readme)
![image](https://user-images.githubusercontent.com/51679301/114297969-95a3c800-9abc-11eb-8bc3-571a3d9fdaa6.png)
<br>
And [BTCpay](https://github.com/btcpayserver/btcpayserver#readme)
![image](https://user-images.githubusercontent.com/51679301/114298041-fe8b4000-9abc-11eb-93d2-70273ccbacbb.png)

2021-04-11 09:04 UTC, BTCparadigm commented on README.md
> -[![Build Status](https://dev.azure.com/zkSNACKs/WasabiDoc/_apis/build/status/zkSNACKs.WasabiDoc?branchName=master)](https://dev.azure.com/zkSNACKs/WasabiDoc/_build/latest?definitionId=4&branchName=ma
Our current explanation is a bit longer tho, but I don't see it as an issue.
Not sure it should be centered or not.

2021-04-11 10:23 UTC, yahiheb commented on README.md
> -[![Build Status](https://dev.azure.com/zkSNACKs/WasabiDoc/_apis/build/status/zkSNACKs.WasabiDoc?branchName=master)](https://dev.azure.com/zkSNACKs/WasabiDoc/_build/latest?definitionId=4&branchName=ma
ACK

2021-04-11 10:36 UTC, BTCparadigm commented on README.md
> -[![Build Status](https://dev.azure.com/zkSNACKs/WasabiDoc/_apis/build/status/zkSNACKs.WasabiDoc?branchName=master)](https://dev.azure.com/zkSNACKs/WasabiDoc/_build/latest?definitionId=4&branchName=ma
Added `Build status` back to row 19. Decided to leave it in the beginning of the row like it was, since the description text is also not centered.

2021-04-12 09:06 UTC, RiccardoMasutti requested changes
Looks OK, waiting for final review and then I will merge

2021-04-12 09:06 UTC, RiccardoMasutti commented on README.md
> +    <img src="https://user-images.githubusercontent.com/51679301/114181477-39209b80-994a-11eb-80c8-611c034b1252.png"/>
Please link resources from the documentation instead of githubusercontent.com

2021-04-14 09:23 UTC, BTCparadigm commented on README.md
> +    <img src="https://user-images.githubusercontent.com/51679301/114181477-39209b80-994a-11eb-80c8-611c034b1252.png"/>
Is it good now?

2021-04-14 10:01 UTC, yahiheb approved these changes
LGTM

2021-04-15 08:19 UTC, RiccardoMasutti approved these changes

2021-04-15 08:20 UTC, merged